### ISSUE TITLE
"react-materializecss": "^0.12.0" is out-dated

### ISSUE THREAD

**Issue by walter90920** [react-materialize/react-materialize#10]
The source code on git hub is using classname rather than joinClasss, but the version I'm getting from npm is still out-dated and doesn't work with react 0.14 that well. Can somebody help? Thanks a lot!

**Comment by isaiah** [comment]
see #11

**Comment by isaiah** [comment]
Please use the `react-materialize` package from now on. I've pushed a beta version to npm with react 0.14 support.
