### ISSUE TITLE
Button icon prop is superfluous

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#100]
I believe the `icon` property for the Button component is superfluous and that it doesn't add much to the component.

To me, `<Button icon="add">ADD</Button>` is better written as `<Button><Icon left>add</Icon>ADD</Button>` since it offers not only more control on the icon behaviour, but it's own configuration. It is not the button's contract to add a child element for an icon; it is a breach of responsibility.

**Comment by alextrastero** [comment]
This is not really an issue but more a suggestion, you can choose, either to use an icon as a prop or as a new component. The button needs to have this functionality so that it can work as a floating menu.
