### ISSUE TITLE
Select (Multiple) Does Not Select Multiple

### ISSUE THREAD

**Issue by ydax** [react-materialize/react-materialize#1001]
### Description

When using the `<Select multiple />` Component, it is impossible to select any of the options. See [this gif for a screen capture](https://media.giphy.com/media/eK1vMjEohqSqEYgv2z/giphy.gif).

### Steps to Reproduce

1. Use the `<Select multiple ... >` in a React UI Component
2. Attempt to select any of the dropdown options in a dev environment (e.g. `npm start`)

**Expected behavior:** Items selected in the dropdown are displayed as selected in the toggle box to the left.

**Actual behavior:** The dropdown closes without selecting anything.

### Versions

**react-materialize:** 3.5.9
**materialize-css:** 1.0.0
**react:** 16.13.0

**Comment by alextrastero** [comment]
Good catch! it seems like it only works if you add a `onChange` prop, can you try it out?
