### ISSUE TITLE
Implement Autocomplete

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#102]

**Comment by isaiah** [comment]
This is a nice feature actually, would you expect something like this?

`<Autocomplete name='country' data={this.getData} />`

**Comment by alextrastero** [comment]
this has been implemented

**Comment by jderose9** [comment]
There doesn't appear to be any way to set an initial value for the input, such as when returning to edit a record. Is that correct?

**Comment by alextrastero** [comment]
Hey @jderose9, would you expect this result? or the dropdown not opened?
![screen shot 2017-06-07 at 08 55 12](https://user-images.githubusercontent.com/4152819/26865906-13602c90-4b5f-11e7-9093-603174aedac4.png)

**Comment by jderose9** [comment]
I would expect it to be closed. The use case is basically editing a record. For instance, user creats a record, filling in the autocomplete input, and then saves it. When the user later returns to the form and the record is loaded, it doesn't seem that I can assign the existing value to the input.

**Comment by alextrastero** [comment]
I would then recommend having a if condition for that, if there's a record use a normal Input and if not use an Autocomplete, from the `materialize.js` if there's any value inside this input the dropdown will be triggered, so there's no way for us to not trigger it.

I could pass a don't autocomplete prop to autocomplete but then you would need to initialise the autocomplete on focus... don't like this approach

**Comment by jderose9** [comment]
If the user edits the existing value, the autocomplete should still work, so dynamically swapping for a regular input wont work.

You are saying that if the underlying input's value is set programmatically, the drop down is still expanded?

**Comment by alextrastero** [comment]
Yes, I added a screenshot above of what happens when you add value programmatically

**Comment by parthsuresh** [comment]
Has this been implemented? The documentation at [react-materialize forms](https://react-materialize.github.io/#/forms) doesn't show this option.

**Comment by alextrastero** [comment]
Hey, it's implemented but missing in the docs, `<Autocomplete ... />`

**Comment by stewmystre** [comment]
Having issues with the drop down list not showing up properly when minLength={0}, it is acting like minLength={1} any ideas?

**Comment by matas30rubliu** [comment]
would love to have an option to set ID for my Autcomplete element
