### ISSUE TITLE
How to use OnChange in a Modal ?

### ISSUE THREAD

**Issue by Louvivien** [react-materialize/react-materialize#1088]
Hi, 
I can't figure out how to use OnChange for my inputs inside my modal. Any key I enter would close the modal. 
What can I do so it will not close it ?
Here is my code 

<Modal
          
          actions={[
            <Button flat modal="close" node="button" waves="green">Close</Button>,
            <Button  className="blue darken-4" size="sm" onClick={() => this.addProd(producerName, producerShare)}  flat modal="close" node="button"
          >Enregistrer dans la blockchain</Button>
          ]}
          bottomSheet={false}
          fixedFooter={false}
          header="Modal Header"
          id="Modal-0"
          open={false}
          options={{
            dismissible: true,
            endingTop: '10%',
            inDuration: 250,
            onCloseEnd: null,
            onCloseStart: null,
            onOpenEnd: null,
            onOpenStart: null,
            opacity: 0.5,
            outDuration: 250,
            preventScrolling: true,
            startingTop: '4%'
          }}
          trigger={<Button node="button">MODAL</Button>}
        >
          <p>

          Veuillez saisir le nom du coproducteur et le pourcentage de ses parts dans le projet
          </p>
          <br></br>

          <TextInput id="producerName" placeholder="Nom" onChange={adresse => this.setState({producerName: adresse.target.value})} />{' '}
          <br></br>
          <TextInput  id="producerShare"placeholder="Part Producteur"  onChange={adresse => this.setState({producerShare: adresse.target.value})} />
          <br></br>
        </Modal>

**Comment by alextrastero** [comment]
This is more of a react question :) but... Once you call `this.setState` you are triggering a new `render`, therefore the `Modal` is being rendered once again with props.

If you have a prop that says `open={false}` the Modal will render not opened. Try removing that prop.
