### ISSUE TITLE
npm doesn't have latest release

### ISSUE THREAD

**Issue by eddiekollar** [react-materialize/react-materialize#11]
I just tried installing and as of the time of this post 0.12.0 is the latest version in npm.

**Comment by isaiah** [comment]
Yes, I'm working react 0.14 and the javascript components. I'll keep you posted.

**Comment by mez** [comment]
Noticed the package.json requires react 0.14. Is the 0.14 branch complete?

**Comment by isaiah** [comment]
Not yet, I am also trying to implement more components and add more features that are introduced to materializecss recently.

**Comment by isaiah** [comment]
I've pushed a beta version to NPM, please note that the package name has changed on NPM https://www.npmjs.com/package/react-materialize
