### ISSUE TITLE
Modal stops working after state update

### ISSUE THREAD

**Issue by tslima** [react-materialize/react-materialize#1100]
### Description
The Modal component stops working after a state update
### Steps to Reproduce
I've made a small code snippet to reproduce the problem.

First my dependencies in package.json

```javascript
"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "materialize-css": "^1.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-materialize": "^3.8.3",
    "react-scripts": "3.4.1"
  }
``` 
Code:
```javascript
import React, {useState} from 'react';
import './App.css';
import 'materialize-css/dist/css/materialize.min.css'
import 'materialize-css'
import {Button, Modal} from 'react-materialize'

function App() {

  const [text, setText] = useState('INITIAL')

  function changeText(){
    setText('AFTER')
  }

  return (    
    <div className="App">
    <p>{text}</p>
    <Button onClick={changeText}>CLICK ME</Button>
     <Modal
      header='Modal Header'
      trigger={<Button>MODAL</Button>}>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
  </Modal>      
    </div>
  );
}
export default App;

```
### Steps to Reproduce

1. Click on MODAL button, the modal content should be displayed;
2. Click on CLICK ME button, the text will be updated;
3. Click on MODAL button again, the modal will not be displayed.

**Expected behavior:** The modal should be displayed again

**Actual behavior:** Modal is not displayed

### Versions

**react-materialize:** 3.8.3
**materialize-css:** 1.0.0
**react:** 16.13.1

**Comment by alextrastero** [comment]
Question, are you using `next.js`? can you try passing a `root` prop?

**Comment by tslima** [comment]
> Question, are you using next.js? 
No

> can you try passing a root prop?

I'm really having a hard time dealing with this prop. Do you have any example how to define it without being document.body?

**Comment by alextrastero** [comment]
hmm, try this:
```jsx
<Modal root={document.getElementById('root')}>
```

**Comment by tslima** [comment]
Still stop working after state update.

``` javascript
import React, {useState, useEffect} from 'react';
import './App.css';
import 'materialize-css/dist/css/materialize.min.css'
import 'materialize-css'
import {Button, Modal} from 'react-materialize'

function App() {

  const [text, setText] = useState('INITIAL')
  const [anchdor, setAnchor] = useState();  

  function changeText(){
    setText('AFTER')
  }  

  return (    
    <div className="App">
    <p>{text}</p>
    <section></section>
    <div id="anchor"></div>
    <Button onClick={changeText}>CLICK ME</Button>
     <Modal
      header='Modal Header'
      trigger={<Button>MODAL</Button>}
      root={document.getElementById('root')}
      >
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
  </Modal>      
    </div>
  );
}

export default App;
```

**Comment by alextrastero** [comment]
What do you mean by `stop working` that the modal closes? that it never opened in the first place? with setState you are rerendering and therefor forcing the modal to be closed as in the beginning

**Comment by tslima** [comment]
Before a state update when I click on Modal button the Modal is displayed, then I close it, click again, open again, close again, everything is fine.

After a state update when I click on Modal button, the modal is not displayed.

**Comment by alextrastero** [comment]
Ok, gonna check it out, thx for the info!
