### ISSUE TITLE
Transparent navbar issue

### ISSUE THREAD

**Issue by AronWater** [react-materialize/react-materialize#1102]
### Description

[Description of the issue]
Is there a way to change the background property of my navbar component to transparent(so that the background image could show even in the navbar?

### 

` <nav position="static"  style={{ background: 'transparent', boxShadow: 'none'}} >`
 I have tried this, but not working at all.

### Versions

"react-materialize": "^2.3.3",
 "materialize-css": "^0.100.2",
    "react": "^16.0.0-alpha.13",

**Comment by alextrastero** [comment]
try using the latest materialize and react-materlize for start. Also can you paste here the DOM that gets rendered?

**Comment by alextrastero** [comment]
Closing for now, please reopen with steps to reproduce and if still an issue, thx!
