### ISSUE TITLE
StoryBook Component Example Site has 404 Error

### ISSUE THREAD

**Issue by keeysnc** [react-materialize/react-materialize#1109]
http://react-materialize.github.io/react-materialize/?path=/story/react-materialize--welcome

I checked the react-materialize example documentation and I'm getting a 404. If needed I can make a pull request and attempt to see whats up. Not sure if thats being worked on so I thought I'd mention =)

### Steps to Reproduce

1. Go to http://react-materialize.github.io/react-materialize/?path=/story/react-materialize--welcome

**Expected behavior:** Getting 404 error

**Actual behavior:** Getting 404 error

### Versions

**react-materialize:** x.x.x
**materialize-css:** x.x.x
**react:** x.x.x

**Comment by alextrastero** [comment]
@keeysnc thanks for reporting this, finally solved after 4 patches! gh-pages is normally hardly cashed, open it in incognito to see the working version.
