### ISSUE TITLE
Add support for modal events

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#111]
I am currently trying to find a way to be notified when the modal is triggered and ready, to set focus to an input element. However Materialize does not trigger any event (despite using jQuery....). 

It would be nice to have `onReady` and `onComplete` as props, two function callbacks, that could be passed to `openModal`.

**Comment by yanickrochon** [comment]
Or better yet, a prop `modalOptions`, an object, passed as is to `openModal`.

**Comment by alextrastero** [comment]
@yanickrochon #139  👀

**Comment by yanickrochon** [comment]
Excellent!!
