### ISSUE TITLE
Tooltip interface missing some properties

### ISSUE THREAD

**Issue by CloudPower97** [react-materialize/react-materialize#1113]
### Description

It seems that `TooltipOptions` `interface` is missing some properties:
- `transitionMovement`
- `inDuration`
- `outDuration`
- `enterDelay`
- `exitDelay`
- `margin`

Moreover,  the correct `html` type seems to be `string` and not `boolean`.

I'm soon going to open a related Pull Request to address this issue :smile:

### Versions

**react-materialize:** 3.8.10

**Comment by alextrastero** [comment]
Fixed in https://github.com/react-materialize/react-materialize/releases/tag/v3.9.0
