### ISSUE TITLE
Textarea onChange not firing callback @ 3.8.10

### ISSUE THREAD

**Issue by sunaryohadi** [react-materialize/react-materialize#1115]
Textarea onChange not firing callback @ 3.8.10

**react-materialize: 3.8.10
**materialize-css:** x.x.x
**react:** x.x.x

**Comment by alextrastero** [comment]
Just waiting on one PR and i'll create a new release

**Comment by alextrastero** [comment]
Thanks for reporting!

**Comment by alextrastero** [comment]
Fixed in https://github.com/react-materialize/react-materialize/releases/tag/v3.9.0
