### ISSUE TITLE
Select component not updating properly when this.props changes

### ISSUE THREAD

**Issue by CodyWHageman** [react-materialize/react-materialize#1116]
### Description

I am making a react/redux/firestore app. When I have a list of objects come in from my firestore database I cannot get the Select component to render them in the dropdown.

### Steps to Reproduce

1. Connect your react app to firestore database using redux. There a lots of youtube/blogs that show you how to do this. [Here's a pretty good tutorial](youtube.com/watch?v=Oi4v5uxTY5o&list=PL4cUxeGkcC9iWstfXntcj8f-dFZ4UtlN3)
2. In your mapStateToProps function add the firestore collection of choice. In my example i am using a collection called clients.

`<Select id="id" value={this.state.client.id} label="Client" s={12} onChange={this.handleChange}>`
        `    <option disabel key="1" value="">Choose a client</option>`
       `    {this.renderClientSelectList(this.props.clients)}`
    `</Select>`

`renderClientSelectList = clients => {`
       `return clients`
   ` ? clients.map(c => <option key={c.id} value={c.id}>{c.lastName || ""}, {c.firstName || ""}</option>)`
            `: [];`
`}`

**Expected behavior:** Dropdown should show "Choose a client" option along with all the clients 

**Actual behavior:** Dropdown only displays the "Choose a client" option.

![](https://files.gitter.im/react-materialize/react-materialize/pNVq/image.png)

### Versions

**react-materialize:** ^3.8.5
**materialize-css:** ^1.0.0-rc.2
**react:** ^16.13.1

**Comment by alextrastero** [comment]
Yes, this could be because the `Form.init` is not called when new children arrive. Can you edit `Select.js` and add `children` as a dependency on https://github.com/react-materialize/react-materialize/blob/master/src/Select.js#L47?

**Comment by alextrastero** [comment]
Yes, this solved it, updating library

**Comment by alextrastero** [comment]
Fixed in https://github.com/react-materialize/react-materialize/releases/tag/v3.9.0
