### ISSUE TITLE
Is it possible to have decimal numbers for the range input ?

### ISSUE THREAD

**Issue by Louvivien** [react-materialize/react-materialize#1118]
HI, 

Is it possible to have decimal number for the range input ?
It does not seem to work when I change the minimum and maximum with decimal numbers 
Thanks 

`> <Range max="100"min="0" name="percentage" value={rnpp.percentage} onChange={this.handleRnppNameChange(idx)} />`

**Comment by alextrastero** [comment]
I think so, try adding a `step` prop of say "0.25", if this works please create a PR to add this prop to the component :)

**Comment by alextrastero** [comment]
But in your example you could always round the `rnpp.percentage` and you might achieve what you want.

**Comment by alextrastero** [comment]
Fixed in https://github.com/react-materialize/react-materialize/releases/tag/v3.9.0
