### ISSUE TITLE
Modal destroy by TextInput

### ISSUE THREAD

**Issue by MartinDanielCP** [react-materialize/react-materialize#1123]
### Description

The modal is destroyed when I'm trying to update a state by TextInput.

```
const [nombreUsuario, setNombreUsuario]=useState('');
    const [password, setPassword]=useState('');

    const handleUserNameChange=(event)=>{
        setNombreUsuario(event.target.value);
    }

    const handlePasswordChange=(event)=>{
        setPassword(event.target.value);
    }
```

```
<Modal
                header='Iniciar Sesión'
                open={false}
                options={{
                    dismissible: true,
                    endingTop: '10%',
                    inDuration: 250,
                    onCloseEnd: null,
                    onCloseStart: null,
                    onOpenEnd: null,
                    onOpenStart: null,
                    opacity: 0.5,
                    outDuration: 250,
                    preventScrolling: true,
                    startingTop: '4%'
                }}
                root={document.getElementById('root')}
            >
                    <TextInput
                        icon="email"
                        id="login-useremail"
                        label="Usuario o Email"
                        value={nombreUsuario}
                        onChange={handleUserNameChange}
                    />
                    <TextInput
                        icon="lock"
                        id="login-pass"
                        label="Password"
                        password
                        value={password}
                        onChange={handlePasswordChange}
                    />
            </Modal>
```

### Steps to Reproduce

1. Open Modal.
2. Write any letter and the modal will close and can't reopen.

**Expected behavior:** Can write and update the states.

**Actual behavior:** Modal is destroyed.

### Versions

**react-materialize:** ^3.9.0
**materialize-css:** ^1.0.0
**react:** ^16.13.1

**Comment by jpremmel** [comment]
I'm having a similar issue with modal that I've reproduced using the code in [Modal.js](https://github.com/react-materialize/react-materialize/blob/master/src/Modal.js) from the react-materialize source code. Not sure if this is helpful, but it looks like the only difference between v3.8.11 and v3.9.0 is on line 45.

v3.9.0:

`  useEffect(() => {
    const modalRoot = _modalRoot.current;
    _modalInstance.current = M.Modal.init(_modalRef.current, options);

    return () => {
      root.removeChild(modalRoot);
      _modalInstance.current.destroy();
    };
  }, [options, root, children]);`

v3.8.11:

`  useEffect(() => {
    const modalRoot = _modalRoot.current;
    _modalInstance.current = M.Modal.init(_modalRef.current, options);

    return () => {
      root.removeChild(modalRoot);
      _modalInstance.current.destroy();
    };
  }, [options, root]);`

I tried removing `children` from the array on line 45 and it seems to have fixed the issue for me. (The child paragraph still shows up in the modal.)

**Comment by alextrastero** [comment]
Thank you both for reporting this issue, `children` was added as a dependency to all JS components so that if children changes the component is reinitialised, but truth is that in `Modal` this breaks functionality. Fixing!

**Comment by alextrastero** [comment]
`3.9.1` will fix this

**Comment by alextrastero** [comment]
@MartinDanielCP, please try `3.9.2`

**Comment by MartinDanielCP** [comment]
3.9.2 fixed it. Thanks.
