### ISSUE TITLE
Support for the "feature discovery" component

### ISSUE THREAD

**Issue by Accumulative** [react-materialize/react-materialize#1126]
### Description

I would like to use https://materializecss.com/feature-discovery.html in my project.
Has anyone had any luck implementing it before?

### Versions

**react-materialize:** 3.9.2
**materialize-css:** 1.0.0
**react:** 16.13.1

### What I've tried
I've tried to implement it similarly to the existing react-materialize components:

```
import React, { useEffect, useRef } from 'react';

const FeatureDiscovery = (props) => {
  const { id, title, description } = props;
  const ref = useRef(null);
  const instance = useRef(null);

  useEffect(() => {
    if (ref.current) {
      if (!instance.current) {
        instance.current = M.TapTarget.init(ref.current);
        instance.current.open();
      }
      return () => { instance.current.destroy(); };
    }
  }, []);

  return (
    <>
      <div ref={ref} className="tap-target" data-activates={id}>
        <div className="tap-target-content">
          <h5>{title}</h5>
          <p>{description}</p>
        </div>
      </div>
    </>
  );
};

export default FeatureDiscovery;
```

But I'm getting the error
TypeError: Window.getComputedStyle: Argument 1 is not an object.

**Comment by alextrastero** [comment]
Hi @Accumulative, this feature hasn't been implemented yet. However looking at your implementation you're nearly there!

You would need to pass an object `options` as the second argument
`M.TapTarget.init(ref.current, options);`

**Comment by alextrastero** [comment]
Actually I'm wrong. The default `options` would be used in that case.

**Comment by alextrastero** [comment]
Have a look at this sample on how this could work https://codesandbox.io/s/practical-star-mkdpn

**Comment by Accumulative** [comment]
Thank you very much! Works like a charm. Looks like the difference was using `data-target` rather than `data-activates`.
