### ISSUE TITLE
ProgressBar forced indeterminate prop

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#113]
Currently, the `ProgressBar` component forces the `indeterminate` CSS class when `progress` is falsy. This is an undesirable behaviour, and if `indeterminate={false}` is passed, the component should *not* be in an indeterminate state.

**Comment by yanickrochon** [comment]
This resolves the issue

```jsx
const ProgressBar = ({ indeterminate, progress, className }) => {
  let style;
  const classes = {
    indeterminate: indeterminate || (indeterminate !== false && !progress),
    determinate: !indeterminate && !!progress
  };
  if (progress) {
    style = {
      width: progress + '%'
    };
  }

  return (
    <div className={cx('progress lighten-5', className)}>
      <div className={cx(classes, className)} style={style} />
    </div>
  );
};
```

**Comment by alextrastero** [comment]
Hey @yanickrochon, help me understand, why shouldn't it be `indeterminate` if there is no progress?

**Comment by yanickrochon** [comment]
For my use case, a progress bar display quantities of certain items over an ideal amount. The progress bar gives the user a visual cue of the value in range, among a list of items in a table. Having an indeterminate progress bar when the value is 0 is not only odd, but not visually pleasing. And I would rather not have to use something like `Math.max(qty, 0.000001)` or something. Forcing `indeterminate={false}` ensures that, given any value, the progress bar will not be animated.

**Comment by yanickrochon** [comment]
So.... should I make a PR? This proposal should not break anything (or is trivial to fix).

**Comment by alextrastero** [comment]
But this is not materialize behaviour is it? in Materializecss you either have a progress or you have a indeterminated progress bar, right?

**Comment by yanickrochon** [comment]
AFAIK the prop is there to be set, and I can set it (i.e. `indeterminate={false}`) as I please. However, this will simply ignore the prop and automatically guess it for me, which is contrast with the phiolosophy of material design, as I understand it. To me, having a progress of 0% does **not** mean an indeterminate value, it means a progress at 0%. If I mean an indeterminate state, I can just specify it (i.e. `indeterminate={true}`) manually.

The change that I am proposing does not remove the existing behaviour of automatically setting the indeterminate state automatically, but also allows specifying it for such cases where the progress is determinate, even if it is at 0%.

"Guessing" what the user means without allowing to specify it is just wrong.

**Comment by yanickrochon** [comment]
So, what is the conclusion on this? Can this non-breaking change be pushed to the source code of the progress bar component?

**Comment by alextrastero** [comment]
Lemme look at this again

**Comment by alextrastero** [comment]
ok @yanickrochon #140

**Comment by yanickrochon** [comment]
This is acceptable :smile:
