### ISSUE TITLE
Chips save state

### ISSUE THREAD

**Issue by bajinho** [react-materialize/react-materialize#1139]
### Description

Chips not save state when onChange() event in other components.

### Steps to Reproduce

1. Install React-Materialize
2. Import Chips from 'react-materialize'
3. Copy and paste this example http://react-materialize.github.io/react-materialize/?path=/story/components-chip-javascript-plugin--autocomplete
4. Copy and paste this example http://react-materialize.github.io/react-materialize/?path=/story/components-textinput--default for to use onChange() event

**Expected behavior:** save state value 

**Actual behavior:** does not exist

### Versions

**react-materialize:** 3.9.2
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by alextrastero** [comment]
Hey @bajinho, yes the shared autocomplete options is a bit messy for these components.

If you want to react to when you add a chip do:
```
<Chip options={{
  onChipAdd: function() {
    console.log('hello')
  }
...
```

**Comment by bajinho** [comment]
Yes, I can add Chip in Chips, but when an onChange event occurs in other components, the Chip's disappear.
