### ISSUE TITLE
ReferenceError: M is not defined - only when executing jest tests

### ISSUE THREAD

**Issue by hb0** [react-materialize/react-materialize#1141]
### Description

We currently import `react-materialize` and `materialize-css` the following way:

1. `package.json`

```
  "dependencies": {
    "react-materialize": "^3.9.2"
    // no "materialize-css" here as everything worked without it **until now** and with it bugs occurred.
   }
```

2. `index.html`

```
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
```

**Problem**

(I think) As soon as we added the react-materialize components `DatePicker` and `Range` executing out jest tests suddenly fail with:

```
ReferenceError: M is not defined
(...)
The above error occurred in the <Range> component
(...)
The above error occurred in the <DatePicker> component
(...)
The above error occurred in the <TextInput> component
(...)
```

**Workaround which fixes tests but makes React-Materialize buggy**

When I add the `materialize-css` dependency to the `package.json` nothing changes.

But when I add `import M from 'materialize-css'` in the code somewhere suddenly:

a) The tests run through without the error
b) The React-Materialize components, e.g. a `Button` starts to behave weirdly:

When I click on a button the light-effect does not recover to it's normal background color but turns the background color slightly more brighter. When I click often on a button, the background color eventually turns white.

### Steps to Reproduce

1. Checkout `master` in this [sample project](https://github.com/hb0/react-materilize_bug_materialize-css-import).
2. Execute `npm install`
3. Execute `npm test a` --> in the master branch the "workaround" mentioned above is integrated, i.e. the test runs through
4. Execute `npm start` ---> browser should open on localhost:3000
5. Click multiple times on the button in the test app --> it turns white
6. Checkout branch `fix-bug_but-tests-fail_without-materialize-css-import`
7. Execute `npm install`
8. Execute `npm test a` --> the "workaround" mentioned above is reversed, i.e. the test produce the error mentioned above
9. Execute `npm start` ---> browser should opens localhost:3000
10. Click multiple times on the button in the test app --> all good, normal click "light" effect

**Expected behavior:**

The `Button` component works as expected (does not turn white)
and the Jest test does not throw the exception.

**Actual behavior:**

Ether the `Button` component works (`fix-bug_but-tests-fail_without-materialize-css-import` branch)
or the Jest test runs without exception (`master` branch).

### Versions

**react-materialize:** 3.9.2
**materialize-css:** 1.0.0
**react:** 16.13.1

-----

If the sample app is still too confusing, please let me know. I'll try to simplify it further.

**Comment by alextrastero** [comment]
We add a mock for M like this https://github.com/react-materialize/react-materialize/blob/master/test/setup.js, maybe this will help

**Comment by kingram6865** [comment]
> We add a mock for M like this https://github.com/react-materialize/react-materialize/blob/master/test/setup.js, maybe this will help

Where does this fit into the code? It's almost 2024 and I'm getting this error as soon as I converted my input to Textinput.

**Comment by kingram6865** [comment]
When I added `global.M = require('materialize-css');` to the component, the error message went away.

**Comment by alextrastero** [comment]
Hey @kingram6865, yes exactly materialize.css needs a global variable `M` defined. This can be achieved by adding their script to index.html or importing their library via ES modules

**Comment by alextrastero** [comment]
Also, @kingram6865 this issue is regarding JEST, are you getting this error from within tests?

**Comment by kingram6865** [comment]
> Also, @kingram6865 this issue is regarding JEST, are you getting this error from within tests?

Yes it was happening within a test.
