### ISSUE TITLE
Doesn't work in Gatsby.

### ISSUE THREAD

**Issue by karenheyn** [react-materialize/react-materialize#1146]
Everything looked great in development mode but a dependency of this package doesn't allow server-side deployment (I'm using gatsby). I forgot the name of the package since this happened 4 hours ago and I cannot find the err in my command line history, but it was a Jquery substitute.  Really disappointed because I was excited to use materialize in my project but glad I test deployed before adding more components.

**Comment by taufardh** [comment]
@karenheyn I try in gatsby too and so far so good, maybe you include materializecss not properly...

**Comment by alextrastero** [comment]
This is strange, please let us know if you manage to reproduce
