### ISSUE TITLE
Custom Error or Success Messages

### ISSUE THREAD

**Issue by bijoutrouvaille** [react-materialize/react-materialize#115]
materializecss allows setting [Custom Error or Success Messages](http://materializecss.com/forms.html?) for input fields, but looking at the docs and the source I don't see a way to do that. Is this something that's still in the plans for this lib or just not in the docs yet?

**Comment by yanickrochon** [comment]
I would personally recommend using [jquery-validation](https://jqueryvalidation.org/documentation/) It is fully compatible with Materialize and work quite well, even inside Modals

**Comment by bijoutrouvaille** [comment]
Thanks @yanickrochon. It seems though that the whole point of using a react UI lib is so one wouldn't have to use jquery, which makes unit testing, among other things, complicated. Besides jquery-validation has all this extra validation functionality. What I need from a UI component is to display the error message that I send to it.

I tried adding an error message by hacking the node_modules of the boilerplate, but it didn't show. I guess there's a difficulty. Otherwise it would probably be there already, as an `error` prop or something.

**Comment by alextrastero** [comment]
Hey @bijoutrouvaille check this out #116

**Comment by bijoutrouvaille** [comment]
@alextrastero thanks for pointing out the pull request. That's what I tried before in the hacky way and it didn't show. Just to be sure, I cloned your branch as well with the same result. The `data-error` attribute shows up with the message, but the actual message is not showing up. Am I doing something wrong?

I've modified the boilerplate code a bit,
```
class App extends React.Component {
  constructor(p) {super(p); this.state={text:''}}
  onChange(e) { this.setState({text: e.target.value}) }
  render() {
    return ( 
    <Input 
      value={this.state.text} 
      onChange={this.onChange.bind(this)} 
      label="hello" error={this.state.text.length > 4 ? "wrong wrong" : null}/>
           )

  }
}
```

**Comment by alextrastero** [comment]
yar! error is a prop of the `<Input />` ;)

**Comment by bijoutrouvaille** [comment]
I got it. You need to add the `valid` or `invalid` classes to the input itself. This is how I got it to show, using your code (Input.js line 80),

```
    let inputClasses = {
      validate,
      invalid: !!error,
      valid: !!success,
      'browser-default': browserDefault && this.isSelect()
    };
```

**Comment by alextrastero** [comment]
Yeah, the error and success only seem to work if it's a html5 validation, so if it's type email and you add the `error` and `success` props it works well

**Comment by bijoutrouvaille** [comment]
@alextrastero they say so in the docs, but it's not necessary because in their CSS they check for the class `.invalid` and `.valid` also. You can check: if you modify your pull request to include the code above, it should work without HTML5 validation. I set `validate={false}` on the `<Input/>

**Comment by alextrastero** [comment]
top notch @bijoutrouvaille ! thanks for that, updated #116

**Comment by yanickrochon** [comment]
@bijoutrouvaille it seems ironic that you would avoid using jQuery as Materialize requires it as dependency anyway. Besides, since the mentioned plugin allows for localization and setting multiple validations for the same input, putting the validation logic directly unto the component itself is exactly something that I would avoid myself; when an input has 3 or more validation rules, when different localized messages, having a `error={ condition1 ? condition2 ? condition3 ? null : error3 : error2 : error1 }` (or something) is everything but pretty. 

Sure, I am being sarcastic, a little, but the concept is part of engineering design patterns of separation of responsibility.

**Comment by bijoutrouvaille** [comment]
Haha, @yanickrochon. It seems that your pentiary error conditional could benefit from a little engineering concept called refactoring. jquery is a DOM manipulation library, and mixing that with business logic is the antithesis of separation of concern. If you use shallow rendering for unit testing, it's okay if a dependent UI kit requires jquery internally; it is never reached by the renderer.
