### ISSUE TITLE
autocomplete disappearing

### ISSUE THREAD

**Issue by Bill0197** [react-materialize/react-materialize#1163]
### Description
autocomplete is displaying dropdown only for fraction of a second and disappear. When you focus in the input field, it displays stays until you click

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/50979326/100052984-edf56880-2e40-11eb-8124-616cde43ec55.png)
this is the onChange function
![image](https://user-images.githubusercontent.com/50979326/100053039-09f90a00-2e41-11eb-9027-976ab37108bb.png)

**Expected behavior:** [What you expect to happen]
the dropdown should display when you type

**Actual behavior:** [What actually happens]
the dropdown only display on focus in the input
![image](https://user-images.githubusercontent.com/50979326/100053105-28f79c00-2e41-11eb-9e8b-14a3cf44648f.png)

### Versions

   "react-materialize": "^3.9.3",
   "materialize-css": "^1.0.0-rc.2",
 "react": "^16.13.1",

**Comment by alextrastero** [comment]
Hey @Bill0197, I'm afraid this is because of your onChange handler, it's probably rerendering the component (setState) and therefor the dropdown is closed.

**Comment by Bill0197** [comment]
Oh I see, excuse me for bothering you. 
I know I should not ask you but do you have any idea to fix it? I have been dealing with this simple issue for hours :(
Thank you!
--
Sent from Mail.ru app for Android Tuesday, 24 November 2020, 00:57PM +05:00 from Alexander Odell  notifications@github.com :

**Comment by alextrastero** [comment]
Without looking at the code I would tend towards making it a [controlled component](https://reactjs.org/docs/forms.html#controlled-components).

The autocomplete should receive `data` from app state, on change fire any api call and update that state, the component should rerender with new data.

**Comment by Bill0197** [comment]
Thank you very much! You helped a lot!
--
Sent from Mail.ru app for Android Tuesday, 24 November 2020, 01:50PM +05:00 from alextrastero  notifications@github.com :
