### ISSUE TITLE
Can't use React `ref` on `TextInput` component with TypeScript

### ISSUE THREAD

**Issue by dmitrij-borchuk** [react-materialize/react-materialize#1176]
### Description

Can't use React `ref` on TextInput component with TypeScript

### Steps to Reproduce

```
const Component = () => {
	const inputRef = useRef(null)

	return <TextInput ref={inputRef} />
}
```

**Expected behavior:** I expect to be able to use `ref` on the `TextInput` component

**Actual behavior:** I see a TS error
```
Type '{ ref: MutableRefObject<null>; }' is not assignable to type 'IntrinsicAttributes & TextInputProps & { children?: ReactNode; }'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & TextInputProps & { children?: ReactNode; }'.
```

### Versions

**react-materialize:** 3.9.5
**materialize-css:** 1.0.0-rc.2
**react:** 17.0.1

**Comment by NickGeek** [comment]
I'm also running into this
