### ISSUE TITLE
Invalid types path in 3.9.6

### ISSUE THREAD

**Issue by rjkz808** [react-materialize/react-materialize#1177]
Just installed `react-materialize@3.9.6`, but noticed types are not being loaded. As I see in this project's `package.json` file, type definitions should be at the root of `lib` folder:

```json
"types": "./lib/index.d.ts"
```

But when I opened the corresponding `react-materialize` folder in my `node_modules`, I saw that all the types are actually located in `lib/types/components` folder. So, I think the `types` field in `package.json` should be fixed to point to the right directory.

**Comment by rjkz808** [comment]
Quick fix for someone who's also facing this issue - simply add this to your root `.d.ts` file:

```ts
declare module 'react-materialize' {
  export * from 'react-materialize/lib/types/components';
}
```

**Comment by alextrastero** [comment]
Thanks for reporting this @rjkz808, this was introduced in #1172, fixing now
