### ISSUE TITLE
Add support for open state in Modal

### ISSUE THREAD

**Issue by jhernandezme** [react-materialize/react-materialize#119]
Right now you can only open a modal if there is a button trigger that actually opens the modal, but for example if this modal is participating in a route like `/some/url/to/modal` it will be needed to have a initial state that tells to open the modal when the route loaded.

I actually do this by extending the OverlayTrigger into a custom OverlayTrigger,  and a new Dialog component that uses this trigger.

```
  componentDidMount() {
   //A callback is passed to be executed after the render is complete, in this case show the overlay.
    this._renderOverlay(() => {
      this.showOverlay(); 
    });

  }
  _renderOverlay(cb) {
    if (!this._overlayTarget) {
      this._mountOverlayTarget();
    }

    // Save reference to help testing
    this._overlayInstance = ReactDOM.unstable_renderSubtreeIntoContainer(this, this.renderOverlay(), this._overlayTarget, cb); 
  }
```

Is there any plan to support this?

**Comment by isaiah** [comment]
@jhernandezme do you mean you need the ability to inject a callback for the `showOverlay` event?

**Comment by alextrastero** [comment]
Hey @jhernandezme please reopen this issue if not fixed, cheers
