### ISSUE TITLE
Unknown property in OverlayTrigger

### ISSUE THREAD

**Issue by jhernandezme** [react-materialize/react-materialize#120]
[OverlayTrigger.js](https://github.com/react-materialize/react-materialize/blob/master/src/OverlayTrigger.js#L24)
```
return React.cloneElement(this.props.overlay, {onRequestHide: this.toggle, id: this.overlayID});
```

onRequestHide is not a property of OverlayTrigger nor Overlay component which causes a warning.
<img width="964" alt="screen shot 2016-08-24 at 9 49 44 pm" src="https://cloud.githubusercontent.com/assets/3452489/17956145/c422c1ac-6a44-11e6-9cd2-9f2a7573de6b.png">

**Comment by alextrastero** [comment]
This should be fix when I apply #139
