### ISSUE TITLE
Tab missing ID and thus not working

### ISSUE THREAD

**Issue by a-koka** [react-materialize/react-materialize#122]
First of all, thank you for building this. It is an amazing piece of art!

I'm on `React 15.2` and looks like the `div` for a `Tab` isn't being assigned an ID and thus the tabbing functionality isn't working. I'd love to help if someone can point me in the right direction. I'm still relatively new to `React`.

Thank you!

**Comment by alextrastero** [comment]
Hey @a-koka, that should be fixed now in `0.15.2`
