### ISSUE TITLE
Modal reusability

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#124]
Given a list of item, each have a part defined as

``` jsx
<a href="#itemModal" data-id={ item._id ">{ item.name }</a>
```

and the modal is manually defined as

``` jsx
<div id="itemModal" className="modal modal-fixed-footer">
  <div className="modal-content">
    <h4>Edit Model</h4>
    <form> ... </form>
  </div>
  <div className="modal-footer">
    <a href="#!" className="modal-action modal-close waves-effect waves-green btn-flat ">Close</a>
  </div>
</div>
```

At the moment, the `Modal` component seem to require a `trigger` prop.

How can this component be reusable? I don't want to create 500 if I have 500 items in my list.

**Edit**

A suggestion could be to have `trigger` be optional, and allow a `selector` prop to use when initializing the overlay with Materialize's `leanModal`.

**Comment by alextrastero** [comment]
Hey @yanickrochon, once again I can't understand you 100%. You are saying that because the Modal requires a trigger this component is not reusable?
If I wanted to create multiple Modals I would do it like this:
```
class App extends Component {
  render () {
    const items = [
      { name: 'A', id: 1 },
      { name: 'B', id: 2 },
      { name: 'C', id: 3 },
      { name: 'D', id: 4 },
      { name: 'E', id: 5 }
    ];

    return (
      <div>
        {
          items.map(item =>
            <Modal key={item.id} trigger={<p>Edit {item.name}</p>}>
              <p>Content {item.name}</p>
            </Modal>
          )
        }
      </div>
    );
  }
}
```

**Comment by yanickrochon** [comment]
@alextrastero exactly the opposite, actually! One use case (with fictional props and callbacks)

```jsx
class CustomModal extends Component {
  updateState(event) {
    // see other proposal here : https://github.com/Dogfalo/materialize/issues/3590
    // set component state, not implemented in this snippet for clarity...
  }
  applyData() {
    const itemId = ...get from state, not implemented in the snippet for clarity...;
    const data = ... get from state, not implemented in this snippet for clarity ...;
    Meteor.call('item.update', itemId, data, function (err) {
      err && Materialize.toast(err.message);
    });
  }
  render() {
    return (
      <Modal onReady={ this.updateState.bind(this) }
        header="Edit Item"
        actions={
          <section>
            <Button waves='light' flat className="modal-action modal-close">Dismiss</Button>
            <Button waves='light' className="modal-action modal-close blue" onClick={ this.applyData.bind(this) }>Apply</Button>
          </section>
        }
      >
        <form>... form elements update component state ...</form>
      </Modal>
    )
  }
}

class App extends Component {
  getItems() {
    return ItemsCollection.find();
  }
  render () {
    const items = getItems();   

    return (
      <div>
        <CustomModal id="itemModal" />
        {
          items.map((item, idx) =>
            <a kye={ idx } href="#itemModal" data-item-id={ item._id }>{ item.name }</a>
          )
        }
      </div>
    );
  }
}
```

... well, I'm writing this from the top of my head, not tested of course, but the point is there; I don't want to create a `Modal` for each item, but reuse the same one.

**Comment by alextrastero** [comment]
Ok, so then why not create one Modal and make the be read from the state...
```JS
<Modal...>
  <p>{ this.state.modalContent }</p>
</Modal>
...
setState({
  modalContent: form...
})
```

**Comment by yanickrochon** [comment]
That would create `n` triggers and `n` content... and would not resolve the issue that `Modal` *requires* that `trigger` prop be set.

**Comment by yanickrochon** [comment]
Any development on this? The point of this issue is, really, to have the `trigger` prop optional. Basically, render a modal component, not visible, without any trigger.

What's the point? Well, that is to the developer. Without a trigger, indeed a modal is meaningless, this is why it needs to have an `id` prop / html attribute and have it be triggered from multiple external triggers.

For example, something like :

```jsx
<Modal id="fooModal" title="Show Foo Info"
   modalOptions={ { ready: this.updateModalState.bind(this) } }
>
  <form><Row><Input s={12} value={ this.state.modal.fooValue } /></Row></form>
</Modal>
{ items.map( (item) => (
  <a key={ item._id } href="#fooModal" className="modal-trigger" data-item-id={ item._id }>{ item.name }</a>
) ) }
```

(**Note:** following my [feature request](https://github.com/Dogfalo/materialize/issues/3590), the `ready` callback now has the `modal` instance and the `trigger` element as arguments)

**Comment by yanickrochon** [comment]
Bump.

**Comment by isaiah** [comment]
@yanickrochon So the only requirement is to make the `trigger` property optional, right? We can make it happen.
