### ISSUE TITLE
Preserve Modal id when specified

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#128]
Currently, the `OverlayTrigger` component overrides the overlay's id by an auto-generated value. If an id is specified, it should be used instead.

That is, instead of

```
this.overlayID = `overlay_${idgen()}`;
```

it should be

```
this.overlayID = this.props.overlay.props.id || `overlay_${idgen()}`;
```

Since `this.props.overlay` is mandatory, and `props` is always an object, this should work in very cases.

**Comment by alextrastero** [comment]
@yanickrochon check out #138

**Comment by alextrastero** [comment]
merged
