### ISSUE TITLE
CollectionItem doesn't allow any attributes

### ISSUE THREAD

**Issue by jumbosushi** [react-materialize/react-materialize#133]
CollectionItem does not allow any attributes, so onClick or even using links with href doesn't work :/

**Comment by yanickrochon** [comment]
I have the same problem. Currently, I get around this by setting an `id` attribute to it's parent (ex: `<Col s={12} id="listContainer"> ... </Col>`, then I listen to click events on children elements once the component has been rendered / updated

```
$('#listContainer').on('click', 'a.collection-item', function (e) {
  e.preventDefault();   // does not change URL
  e.stopPropagation();  // prevent event from bubbling up

  const id = $(e.currentTarget).attr('href').substr(1);  // skip # sign

  // ...
});
```

**Comment by alextrastero** [comment]
Hey @jumbosushi, check out #135 for a fix

**Comment by alextrastero** [comment]
cc @yanickrochon

**Comment by yanickrochon** [comment]
:+1:

**Comment by jumbosushi** [comment]
Awesome. Thanks @alextrastero !
