### ISSUE TITLE
Button component does not allow custom props

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#134]
```jsx
<Button flat node="a" href="#foo">Foo</Button>
```

* Expected : `<a class="btn btn-flat" href="#foo">Foo</a>`
* Actual : `<a class="btn btn-flat">Foo</a>`

The component is missing the `...others` props.

**Comment by alextrastero** [comment]
Hey @yanickrochon check out #136

**Comment by yanickrochon** [comment]
:+1:
