### ISSUE TITLE
Pagination is stateful, and the state doesn't always update when needed

### ISSUE THREAD

**Issue by rulatir** [react-materialize/react-materialize#143]
Currently Pagination is stateful - it stores currentPage in the state. This state sometimes doesn't update when the corresponding property changes:

![image](https://cloud.githubusercontent.com/assets/677694/18264674/03baddfa-7412-11e6-8da3-776c777ec572.png)

Another case (note the nonsense state that means "page 2 of 1"; a component should take care to never hold nonsense state, therefore I consider this a bug):

![image](https://cloud.githubusercontent.com/assets/677694/18264882/0a74fb98-7413-11e6-99df-9341b6707765.png)

The workaround is to force re-rendering every time with `key={"paginator_"+this.paginatorSeq++}` but it's an ugly hack.

**Comment by alextrastero** [comment]
Hey @rulatir, you mean that when you paginate the state doesn't update? For me it works fine, what version are you using? Also, I can see in your screenshot that you only have 1 item

**Comment by rulatir** [comment]
I paginate through a "search store" that holds filter parameters sent to the listing's server endpoint; those parameters also include the page number for pagination. That same page number from the search store is also passed as activePage prop to the Pagination component.

I understand that `items` in `Pagination` parlance actually mean pages - is my understanding wrong? (If it were to *actually* mean "items", then `Pagination` would need to know the items-per-page value, and there's nothing about that in `Pagination` docs). It is perfectly valid to have just one page of results, and I believe it makes sense to display the pagination widget anyway in this case.

I edited the original report to emphasize the nonsensical state held by the component in the second case, and to clarify that these are two distinct screenshot of two different component states.

**Comment by alextrastero** [comment]
I see, thanks for the explanation, would this work? #144

**Comment by rulatir** [comment]
I think this is even worse. You look at `this.props` and silently apply a correction if they are nonsensical, hiding an error in application logic. You might have a different approach to this, but I would be inclined to at least issue a warning.

My code *never* passes "page 2 of 1" props to `Pagination` - please look at the props in the screenshots. Instead this state *emerges* within `Pagination` because `items` is taken directly from props but `activePage` is held in the state and isn't updated when the props change - there is no `componentWillReceiveProps` in `Pagination`.

The actual problem seems to be that `Pagination` does not support controlled operation and we can't compatibly switch to the `defaultValue` idiom. I will live with `key` bumping for now.

**Comment by alextrastero** [comment]
I understand, the fact that I'm checking the props initially is so it renders nicely.
I have added another lifecycle to listen to new props. Which will update the state accordingly.
However it still handles wrong values passed, ie. activePage needs to be in range with [0...items].
Have another look at the PR.

**Comment by rulatir** [comment]
I think I will post my own PR later today.

I'm afraid your proposed change is backwards incompatible: it will probably break code that *assumes* `activePage` is held in state. Currently `activePage` works similarly to `Input`'s `defaultValue`, and your change makes it work like `value`.

What I want is the ability to use `Pagination` as a "controlled input", but without breaking existing apps. This can be accomplished with a simple wrapper that bumps the `key` property on the wrappee when either `activePage` or `items` change.

**Comment by alextrastero** [comment]
Currently you can use the Pagination as a controlled input, if you pass a new activePage it will update. Please submit your PR and we'll have a look.

**Comment by alextrastero** [comment]
Closing waiting for @rulatir's PR

**Comment by viadrew** [comment]
Was a PR ever submitted? Ran into the same issue. My quick solution was just to copy the Pagination / PaginationButton components and add:

```javascript
componentWillReceiveProps(nextProps) {
  if (nextProps.activePage != this.props.activePage) {
    this.setState({activePage: nextProps.activePage})
  }
}
```

I can quickly make my own PR later if a previous PR hasn't been submitted.

**Comment by alextrastero** [comment]
Hey @viadrew please submit it and we'll check :)
