### ISSUE TITLE
[v0.16.2] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#145]
This is what I get whenever I modify any input field in my app 

![selection_093](https://cloud.githubusercontent.com/assets/78461/18274599/312898c8-7411-11e6-934b-57959db1437c.png)

I'm not sure what it means... no values (i.e. no prop values) are not null or undefined.

**Comment by alextrastero** [comment]
Updated, check again

**Comment by yanickrochon** [comment]
:+1:
