### ISSUE TITLE
Add icon to select input

### ISSUE THREAD

**Issue by arcifius** [react-materialize/react-materialize#147]
This one should be simple, i could even do it by myself if i got some extra time... Like on input texts I would like to see icons on select inputs too, this will make forms more styleable and following the same line of design... This isn't very important but i really think it will make difference.

**Comment by alextrastero** [comment]
👍

**Comment by alextrastero** [comment]
I'm afraid this can't be done on our side, it's part of Materializecss, you should raise an issue with them.
