### ISSUE TITLE
[0.16.4] You are manually calling a React.PropTypes validation

### ISSUE THREAD

**Issue by smeijer** [react-materialize/react-materialize#148]
> Warning: You are manually calling a React.PropTypes validation function for the `s` prop on `Input`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

I get this error on a lot of other properties as well.

Code triggering this error:
```jsx
import { Input, Row } from 'react-materialize';

// ...

<form onSubmit={this.handleSubmit}>
  <Row>
    <Input s={12} label="username" defaultValue={username} 
      onChange={this.handleUserNameChange} />
  </Row>
</form>
```

**Comment by alextrastero** [comment]
This is a new one... can you paste the js that produces this error?

**Comment by rulatir** [comment]
DON'T DO ANYTHING!!! EVERYTHING IS AN ANTIPATTERN!!! EVERYTHING IS DEPRECATED!!!

... just React being its usual self.

**Comment by smeijer** [comment]
@alextrastero, sorry. Added to the opening post.

**Comment by smeijer** [comment]
Errors are gone after updating react from `0.14.x` to `15.x.x`.
