### ISSUE TITLE
Can not close Horizontal FAB on mobile and tablet

### ISSUE THREAD

**Issue by nazarposhta** [react-materialize/react-materialize#153]
Hello! I have a problem with this https://monosnap.com/file/Kllz7CTA8grwByrgHESHAbWVwFXAVj
When I open this FAB and click to some one link my URL is changing - because "single page app" but how I can to close this FAB?  Problem is on mobiles and tablets only - on the computer hover event is working fine.

**Comment by alextrastero** [comment]
Hi @nazarposhta, I'm afraid that's an issue with `Materializecss`

**Comment by alextrastero** [comment]
They mention you can close it with `$('.fixed-action-btn').closeFAB();`

**Comment by nazarposhta** [comment]
Very good but... if we use React we don't want to include jQuery

**Comment by nazarposhta** [comment]
Is that possible to to put some state (opened / closed) to this FAB?

**Comment by alextrastero** [comment]
Firstly, Materializecss requires jQuery, so it's already included.
Secondly, the animation happens when the FAB gets an `active` class, which is onHover. So I can't really remove it without making a few hacks. 

I would go with the `closeFAB()`

**Comment by nazarposhta** [comment]
It works. Thanks.
