### ISSUE TITLE
Button icon property has wrong alignment

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#155]
This component

```
<Button className="red" waves="light" icon="delete">{ i18n.__('delete') }</Button>
```

is rendered as
![selection_095](https://cloud.githubusercontent.com/assets/78461/18932522/dfe41cd6-859e-11e6-872e-7a10618e9e1c.png)

However, if the icon had `className="left"`, it would render as

![selection_096](https://cloud.githubusercontent.com/assets/78461/18932547/f0b22b16-859e-11e6-9d0c-3441b8539297.png)

**Comment by isaiah** [comment]
Which is the preferred style?

**Comment by alextrastero** [comment]
Hey @yanickrochon please reopen if this is not fixed
