### ISSUE TITLE
Click-only FAB problem

### ISSUE THREAD

**Issue by nazarposhta** [react-materialize/react-materialize#157]
I decided to make FAB with "Click-only FAB". Is that possible?
According to materialize doc.  In original version it's possible:

> Click-only FAB
> If you want to disable the hover behaviour, and instead toggle the FAB menu when the user clicks on the large button (works great on mobile!), just add the click-to-toggle class to the FAB.

**Comment by reesmanp** [comment]
@nazarposhta This should work now. Please let us know so we can close this issue.
