### ISSUE TITLE
CollapsibleItem : allow node type in header prop

### ISSUE THREAD

**Issue by jhernandezme** [react-materialize/react-materialize#159]
CollapsibleItem only allow `PropTypes.string` but one of my use cases adds an icon along the header 
 `<CollapsibleItem  header={(<span>Settings <i className="material-icons right">arrow_drop_down</i></span>)}`

which causes a warning, maybe using `oneOfType([PropTypes.string, PropTypes.node])`

**Comment by alextrastero** [comment]
Hi @jhernandezme, you can use the icon prop of CollapsibleItem,
`<CollapsibleItem header='First' icon='filter_drama'>`.

Cheers

**Comment by jhernandezme** [comment]
Hi @alextrastero thanks! this does works but I can not pass down the icon class like 'right' for right alignment, so should be there an iconClass prop?
