### ISSUE TITLE
Card element`s title not supporting element

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#163]
I am currently using the `Card`'s `header` prop to set my title, which contains formatting and UI elements, because `title` only accept a string.

It should be possible to do

```
<Card
  title={ <CustomElement /> }
>
  Some content
</Card>
```

**Comment by alextrastero** [comment]
Hi @yanickrochon, please specify a use case for this to help me understand. So far, I know that materializecss instead this only to be a string because you should only add a simple title, any other element would break the design.

**Comment by yanickrochon** [comment]
That `<CustomElement />` may be adding a badge component (i.e. a `<span>` node) and an italic formatting element (i.e. `<em>`) for a suffix. Hardly any breaking threat. The restriction is simply unnecessary.

**Comment by isaiah** [comment]
I think a better solution will be allow specify of the text style, it's currently hardcoded to the same as the materializecss.com style.

https://github.com/react-materialize/react-materialize/blob/master/src/Card.js#L33
