### ISSUE TITLE
Smooth Scrolling Props with Collapsible

### ISSUE THREAD

**Issue by reesmanp** [react-materialize/react-materialize#166]
This is definitely an enhancement and I can code this if there is any interest in this.

If there is a lot of content within a CollapsibleItem Accordion, clicking on the next item will collapse the currently open item and expand the clicked one (which is what we want) but it leaves the viewpoint where the user clicked on the item which may be quite a bit ways down the page forcing the user to scroll up to read from the top.

I think that we should be able to send props in that does a smooth scroll to the top of the item when it is clicked.

**Comment by yanickrochon** [comment]
My view on this is that, while it may seem useful, this is user land in regard to this package, and there are many more priorities to implement, first.

**Comment by reesmanp** [comment]
I agree that this isn't a priority right now but I do think that this should be part of the framework. As a user of the package, I would assume that this item should handle this inherently.

So priority should be low but not necessarily thrown into user land for implementation.

**Comment by isaiah** [comment]
@reesmanp sounds interesting, if you can provide a PR :)

**Comment by reesmanp** [comment]
@isaiah I'll get right on it.

**Comment by reesmanp** [comment]
This seems to be working correctly.
