### ISSUE TITLE
Webpack + Babel build error

### ISSUE THREAD

**Issue by LifeIsALesson** [react-materialize/react-materialize#17]
I'm getting the following error while trying to build my project

    ERROR in ./~/react-materialize/src/index.js
    Module parse failed: /home/foo/.../node_modules/react-materialize/src/index.js Line 1: Unexpected token
    You may need an appropriate loader to handle this file type.
    | export Button from './Button';
    | export Card from './Card';
    | export CardTitle from './CardTitle';

What could I do wrong? Any ideas how to fix this?

webpack 1.12.4
babel@6.1.18

**Comment by iafiawik** [comment]
I have the exact same issue on my end. Unfortunately, I have no idea how to fix it.

Trying to use the Materialize button:

    import React from 'react';
    import {Button} from 'react-materialize';

The webpack output is this:

    ERROR in ./~/react-materialize/src/index.js
    Module parse failed: ./node_modules/react-materialize/src/index.js Line 1: Unexpected token
    You may need an appropriate loader to handle this file type.
    | export Button from './Button';
    | export Card from './Card';
    | export CardTitle from './CardTitle';
     @ ./src/Component.jsx 13:24-52`

Versions:
**react@0.14.2**
**webpack@1.12.5**
**babel@6.1.18**

**Comment by isaiah** [comment]
I'll take a look ASAP.

**Comment by iafiawik** [comment]
@isaiah Thanks! :)

**Comment by isaiah** [comment]
@iafiawik @LifeIsALesson I pushed a new version `0.14.0-beta2` to npm, could you try again?

**Comment by iafiawik** [comment]
@LifeIsALesson Seems to be working for me :+1:
