### ISSUE TITLE
Modal trigger submit form on click

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#170]
The function [`showOverlay`](https://github.com/react-materialize/react-materialize/blob/master/src/OverlayTrigger.js#L29) should receive the `event` object and prevent the trigger's default behavior.

```js
  showOverlay (event) {
    event.preventDefault();

    $(`#${this.overlayID}`).openModal(this.props.modalOptions);
  }
```

**Comment by alextrastero** [comment]
please reopen if this is not fixed
