### ISSUE TITLE
Modal not working in 0.97.7 or 0.97.8

### ISSUE THREAD

**Issue by dacgray** [react-materialize/react-materialize#171]

**Comment by yanickrochon** [comment]
It works fine in 0.97.7, however version 0.97.8 introduce a [refactor in the Modal API](https://github.com/Dogfalo/materialize/commits/3be5561ea1a63f9c0580f9cf109376944324935a/js/modal.js) and requires that react-materialize need to be refactored also to reflect the changes.

If you issue is strictly with 0.97.7, then you'll have to be more precise on what's "not working".

**Comment by alextrastero** [comment]
Yeah, they refactored a bit. I'll need to have a look and see what's changed

**Comment by alextrastero** [comment]
This is fixed with https://github.com/react-materialize/react-materialize/commit/eaf85b7d4b71386ece4dca5eac16b23decde08b0
