### ISSUE TITLE
Can't change <Navbar/> link

### ISSUE THREAD

**Issue by Peakdrum** [react-materialize/react-materialize#172]
Hello,

I want the <Navbar /> logo to change the link or making it link to nothing. What should I do? Thanks

**Comment by isaiah** [comment]
Do you mean the `href` of the logo? it's hardcoded unfortunately :(

https://github.com/react-materialize/react-materialize/blob/master/src/Navbar.js#L49

A PR is welcome :)

**Comment by reesmanp** [comment]
@Peakdrum this issue should now be fixed. Please let us know.
