### ISSUE TITLE
Collapsible is comparing the internal key of children to activeKey

### ISSUE THREAD

**Issue by mihaibogdan10** [react-materialize/react-materialize#174]
I don't think we're supposed to access the `key` property of a component. As far as I understand it, that's for React's internal use only.

The problem I just ran into is that React added keys with a `.` prefix (to elements for which I didn't specify `key` at all). I don't know why it chose to do this, as it doesn't in other places of the app where I use Collapsible.

Here's a log of the props at the end of the renderItem method:
```js
Object {key: ".0", ref: null, eventKey: ".0", expanded: false}
```

activeKey compares for exact value against the child key, so it looks like I would have to guess when the `.` is added, and use defaultActiveKey=".0" in that case (anti-patern alert!)

Why React adds in the `.` is besides the point IMO, I don't think Collapsible should look at the `key` in the first place.

**Comment by mihaibogdan10** [comment]
cc @isaiah, it looks like you were the original author here: https://github.com/react-materialize/react-materialize/commit/9e0ab4f17d1f5a500a4e5a329e6d125b094dcca2

**Comment by isaiah** [comment]
@mihaibogdan10 I think that's a bug, it's supposed to be `eventKey` instead of `key`, so when one uses `defaultActiveKey`, the `eventKey` for each entry should be provided.

**Comment by mihaibogdan10** [comment]
I see. 
The thing is, with the current code, this stuff works sometimes (when React decides to use the `key` without the `.`, which is most of the time in my experience)
```js
<Collapsible defaultActiveKey={0} accordion>
  <PositionItem />
  <BackgroundItem />
</Collapsible>
```

So fixing this will break this behavior. It's true that it shouldn't have worked at all, but I'm slightly worried a fix would break some people's code.

**Comment by yanickrochon** [comment]
If the underlying issue is with React, there is not much we can do. I have looked at the code and it does what it's supposed to do. I would recommend reporting this instead of trying to create a fix, and ask that React generate keys consistently instead.

Also, it might be preferable to add the notice to the docs, that using `defaultActiveKey` is recommended to specify `CollapsibleItem`s' `eventKey` props.

There is nothing wrong with the code AFAIK. This [line](https://github.com/react-materialize/react-materialize/blob/master/src/Collapsible.js#L40) is perfectly fine, and should not use `eventKey`, as it is the `key` to identify the child within the array of `Collapsible` children.

**Comment by isaiah** [comment]
@yanickrochon If you post a second later, I would have posted my wrong comment :). I totally agree with the document part, it should be clearer. Is this behavior varies between react versions or even it's different within the same version of react?

**Comment by yanickrochon** [comment]
I'll refer to @mihaibogdan10 for that question :smile: He is the one pointing out that React sometimes prefix with `.` and sometimes it doesn't. I have not contributed to that one project, yet.

**Comment by mihaibogdan10** [comment]
I am super sorry about this guys, the problem was on my end.
I had an internally modified version of Collapsible.js, that did
```js
props.expanded = props.key === this.state.activeKey;
```
instead of
```js
props.expanded = child.props.eventKey === this.state.activeKey;
```

And yeah, this was a hack that relied on React generating keys without a `.` prefix.
I got the latest version of Collapsible.js and everything works fine now.

@yanickrochon I think the previous owner of the codebase that I'm working on didn't figure out that he should add `eventKey` to all children to get the accordion to work. I'll follow up with a pull request to update the documentation on that.

Thanks a lot for your help.

P.S. On an unrelated note, looking at the [React docs](https://facebook.github.io/react/docs/react-api.html#cloneelement), setting `key` and `ref` in cloneElement shouldn't have any effect. So I think lines 40-41 have no effect here:
https://github.com/react-materialize/react-materialize/blob/master/src/Collapsible.js#L40

**Comment by mihaibogdan10** [comment]
@isaiah it looks like the documentation is there already, but I wasn't able to get the docs generation to work 😢

**Comment by isaiah** [comment]
@mihaibogdan10 I check the doc site, it doesn't say that when you use `defaultActiveKey`, you have to provide the `eventKey` property.

**Comment by isaiah** [comment]
@mihaibogdan10 the doc generation is broken for a while, the issue is here https://github.com/jquense/react-component-metadata/issues/6. I'll take a look.

**Comment by isaiah** [comment]
http://react-materialize.github.io/collapsible.html site updated. @mihaibogdan10 you should be able to generate the document again.
