### ISSUE TITLE
CSS is broken on the website

### ISSUE THREAD

**Issue by jumbosushi** [react-materialize/react-materialize#175]
<img width="1120" alt="screen shot 2016-11-23 at 1 24 35 pm" src="https://cloud.githubusercontent.com/assets/9669739/20579187/3a596470-b180-11e6-86ef-28576fd92057.png">

**Comment by nazarposhta** [comment]
I need to read that docs..... and s*** what to do?

**Comment by alextrastero** [comment]
Yes, sorry guys. We are using css from `node_modules/materializecss...` In order for this folder and vendor we needed to create a `.nojekyll` file. Which basically tells the server to not ignore these folders.

More info here: https://www.bennadel.com/blog/3181-including-node-modules-and-vendors-folders-in-your-github-pages-site.htm

**Comment by alextrastero** [comment]
cc @nazarposhta @jumbosushi
