### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by anaganisk** [react-materialize/react-materialize#177]
I've seen the earlier issues on this but now the date picker is not working at all
I tried
`<Input className='datepicker' type='text' />`
and
`<Input className='datepicker' type='date' />`

**Comment by isaiah** [comment]
@anaganisk we don't have a explicit support for datepicker, from the materializecss.com website, it requires an explicit initialization:

http://materializecss.com/forms.html#date-picker

```javascript
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
```

**Comment by anaganisk** [comment]
Thanks for the reply, Tried that but it wont work, datepicker works fine on non react websites, will find some work around and will get back.

**Comment by GGross5213** [comment]
@anaganisk Did you find a work around for the datepicker?

**Comment by anaganisk** [comment]
@GGross5213 No, I ended up building my own.

**Comment by isahgaga** [comment]
@anaganisk I am having thesame issue. Can I get any help? I can't build my own

**Comment by alextrastero** [comment]
This does work:
```js
class App extends React.Component {
  componentDidMount () {
    $('.datepicker').pickadate({
      selectMonths: true, // Creates a dropdown to control month
      selectYears: 15 // Creates a dropdown of 15 years to control year
    });
  }

  render () {
    return (
      <Input type='date' className='datepicker' />
    )
  }
};
```

**Comment by yurikilian** [comment]
Hi. What module I need to import to get this working? 

I tried:
```

import React from 'react';
import {Input} from 'react-materialize';
import $ from 'jquery';
import 'materialize-css';

export default class DatePicker extends React.Component {

    componentDidMount() {
        $('.datepicker').pickadate({
        selectMonths: true,
        selectYears: 15
        });
    }
    render() {
        return (
            <Input type="date" className="datepicker"
            s={12} label="Informe sua data de nascimento"/>);
    }

}
```

But get no success. Error: Uncaught TypeError: (0 , _jquery2.default)(...).pickadate is not a function
