### ISSUE TITLE
Better integration with react-router

### ISSUE THREAD

**Issue by isaiah** [react-materialize/react-materialize#188]
Just checked the issues backlog, seems there are quite a few issues with `react-router` users, mostly focused on the `modal` component, if there is anything else, please comment in this thread.

**Comment by nfatah** [comment]
I get this error when using `react-router-dom`'s rr version 4 `NavLink` which basically has an anchor tag. To make my navbar links work with RR4 and still be aligned on the navbar I have to place `NavLink` inside `react-materialize`'s NavItem component which also returns an anchor tag. Hence this warning

`warning.js:36 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See HeaderNav > NavItem > a > ... > NavLink > Route > Link > a.
`

**Comment by alextrastero** [comment]
hey @nfatah, you could also use it like this:
```js
          <Navbar brand='logo' right>
            <li>
              <NavLink className="" to="get-started">Getting started</NavLink>
            </li>
            <li>
              <NavLink className="" to="components">Components</NavLink>
            </li>
          </Navbar>
```

**Comment by alextrastero** [comment]
Closing, please reopen if not fixed :)

**Comment by CloudPower97** [comment]
@alextrastero What about the brand? How can I use react-dom in this case? I tried without succes.

**Comment by mlembke1** [comment]
I have mirrored that functionality that @alextrastero has suggested: 
`<SideNavItem className="border-bottom" waves>
        <li><Link className="link" to="/">Home</Link></li>
  </SideNavItem>
  <SideNavItem className="border-bottom" waves>
         <li><Link className="link" to="/portal">Portal</Link></li>
  </SideNavItem>`

However, this only gives me the new error of: 
`validateDOMNesting(...): <li> cannot appear as a descendant of <li>`


Any advice here? Thanks in advance!
