### ISSUE TITLE
Font Awesome icons

### ISSUE THREAD

**Issue by mikeschaekermann** [react-materialize/react-materialize#190]
In the docs, there is an example of a button using a Font Awesome icon:

```
<Button floating fab='vertical' faicon='fa fa-plus' className='red' large style={{bottom: '45px', right: '24px'}}>
```

When I try to run the code myself, however, the icon doesn't show up. Has the syntax changed for Font Awesome?

**Comment by alextrastero** [comment]
Did you add the html markup like in the README ? Is there any error on the
console ?

**Comment by mikeschaekermann** [comment]
Yes, I added all the html markup, and there is no error in the console. It
seems like the `faicon` prop that I pass into `<Button ... >` is just
ignored. Searching the entire `react-materialize` repo for `faicon` didn't
really retrieve any occurrence of this term in the implementation. So, I
wonder if this feature is actually implemented?

**Comment by alextrastero** [comment]
If you look in src/Button.js you can find some node with fa class

**Comment by mikeschaekermann** [comment]
I just looked at the file, but couldn't find a Font Awesome class being
used anywhere. Could you point me to the line in the file?

**Comment by alextrastero** [comment]
Button has an icon prop, pass a icon name as the value to see it in action

**Comment by mikeschaekermann** [comment]
It seems to me that the `Icon` component only supports icons from the `material-icon` family though. Is there a way to use Font Awesome icons with it?

**Comment by alextrastero** [comment]
As far as I understand the material icons are font awesome icons, maybe
there's a specific one that doesn't work for you?

**Comment by mikeschaekermann** [comment]
Oh I see. There is not a specific icon I was missing. I just realized that some of the Font Awesome icons either have different names or look different than the material icons.

**Comment by alextrastero** [comment]
Yeah, they're actually material design icons
http://materializecss.com/icons.html

**Comment by mikeschaekermann** [comment]
Ok, makes sense. Thanks for your help! :)
