### ISSUE TITLE
No bower package? 

### ISSUE THREAD

**Issue by ezmiller** [react-materialize/react-materialize#2]
I was looking to see if this could be installed via bower, but didn't find a package. Would be great to have one.

**Comment by isaiah** [comment]
Working on it now, it would be great if you can help a bit, I'm not expert on JS build tools (there are too many of them )

**Comment by ezmiller** [comment]
I'd be happy to as time permits. I've not got much experience with JS build tools either. Might not be until next month or so that I could help. What have you done so far?
