### ISSUE TITLE
placement inside <Slide> doesn't work, here's the fix

### ISSUE THREAD

**Issue by BkunS** [react-materialize/react-materialize#210]
I think there's a small bug in the Slide.js code where I've installed through npm that causes placement="center/right" not working. 

After looking at the source code installed through npm, fix is simple:
In this piece of code (around line 59 in ^0.17.7): 
...
value: function renderCaption() {
      var _props = this.props,
          title = _props.title,
          className = _props.className,
          alignment = _props.alighment,  // <-change this to alighment = _props.placement;
          children = _props.children,
          props = _objectWithoutProperties(_props, ['title', 'className', 'alignment', 'children']);

      delete props.placement;
...

Hope it helps.

**Comment by alextrastero** [comment]
Hey @davidsunsbk would you like to submit a PR with your fix?

**Comment by davidsunsbk** [comment]
Here's the fix I've just submitted: #244
