### ISSUE TITLE
Ability to pass options to Navbar javascript initialiser

### ISSUE THREAD

**Issue by lloydwatkin** [react-materialize/react-materialize#211]
As per http://materializecss.com/side-nav.html#options I'd like to pass options in to the initialisation. I'd imagine this would be quite easy via a prop `sideNavOptions` or similar. Code would need to go here: https://github.com/react-materialize/react-materialize/blob/master/src/Navbar.js#L14

Creating an issue in case someone would like to pick up else I'll submit a PR when I get to this piece of work in a few weeks :)

**Comment by alextrastero** [comment]
hey @lloydwatkin I just merged 0.17.8 which includes a new SideNav from @richmeij, would you mind checking it out and seeing if this is possible now?
ref: https://github.com/react-materialize/react-materialize/blob/master/src/SideNav.js#L12

**Comment by lloydwatkin** [comment]
Thanks @alextrastero, however I'm using `<Navbar/>` rather than `<SideNav/>` and allowing materialize to do the work of handling navigation. Therefore this change isn't really of use to me until it gets implemented in `Navbar.js#14`.

**Comment by alextrastero** [comment]
Hey @lloydwatkin, NavBar doesn't accept options:
http://materializecss.com/navbar.html

Closing

**Comment by lloydwatkin** [comment]
HI @alextrastero, I'm off this project so not 100% on the context, but from what I can remember the side nav is rendered using children via the navbar (https://github.com/react-materialize/react-materialize/blob/master/src/Navbar.js#L10) but I needed to pass options to that rendered sidebar.
