### ISSUE TITLE
Modal close button

### ISSUE THREAD

**Issue by williamfelippe** [react-materialize/react-materialize#216]
Is there a way to show modal without the close button?

**Comment by alextrastero** [comment]
hey @williamfelippe, actions is the modal prop you are looking for, it's supposed to be a `node`, try passing an empty object or maybe even a `&nbsp;`, for now...

**Comment by williamfelippe** [comment]
I have tried the empty object but did not work. The &nbsp; worked. I'd never imaginate that!
Thank you @alextrastero !
