### ISSUE TITLE
PaginationButton will go to index page when i use react-router's hashHistory.

### ISSUE THREAD

**Issue by shtyboy** [react-materialize/react-materialize#217]
I use a Pagination component but it can't set href. It will go to index page when i use react-router's hashHistory at the same time. So i think it maybe  better to delete href if it didn't exist.

**Comment by alextrastero** [comment]
@shtyboy how did you solve this?

**Comment by alextrastero** [comment]
please reopen if not

**Comment by shtyboy** [comment]
@alextrastero
