### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by johhansantana** [react-materialize/react-materialize#219]
Hello

I recently did a PR #218 but I couldn't test it directly via npm installing it from github. I had to copy/paste manually the `lib` folder into the `node_modules/react-materialize` since it was missing when doing `npm install <my github fork> --save`

I haven't done a lot of repository fork when I do install it directly from github it installs correctly but it doesn't seem to work, keeps saying that `react-materialize` is missing and when I check the node_modules folder it's missing some folders compared to when I install it normally as in `npm install react-materialize`

**Comment by alextrastero** [comment]
Hey @johhansantana, if you clone the project then cd into `react-materialize` and then `npm install` it should work?

**Comment by johhansantana** [comment]
Yes it does but for the moment, until and if the PR gets acepted, I would like to use my fork when deploying my app and `npm install` directly from the fork doesn't seem to work or I need to do some configuration changes to the `package.json` of the forked repository which I'm not really sure.

**Comment by wedneyyuri** [comment]
Hi Johhan, maybe `npm link` can make it work for you!
https://docs.npmjs.com/cli/link

____________________________________________________________
___________________
*Wédney Yuri | **Web Developer*
Tel: +55 21 98092 0692 | Github <https://github.com/wedneyyuri> |
Stackoverflow <http://stackoverflow.com/users/3738720/w%C3%A9dney-yuri>
Campo Grande | Rio de Janeiro, Brazil


2017-02-18 12:37 GMT-02:00 Johhan Santana <notifications@github.com>:

**Comment by dancork** [comment]
You can add a github repo to your package.json to use a fork. e.g. `"react-materialize": "username/react-materialize",`. This is what I've done whilst waiting for PRs to get merged on other projects.
