### ISSUE TITLE
SideNav is not working on demo website

### ISSUE THREAD

**Issue by nvana** [react-materialize/react-materialize#222]
SideNav is not working on demo website (`https://react-materialize.github.io/sidenav.html`) but it's working on localhost. I have no idea why.

**Comment by pricetula** [comment]
Its not working on their website too
![screenshot from 2017-03-16 12-39-08](https://cloud.githubusercontent.com/assets/3857337/23990015/bb8d42aa-0a45-11e7-9c7e-31902fc4c0be.png)

**Comment by alextrastero** [comment]
yeah we are aware, will try and fix asap, have you tried the `sideNav` on another project?

**Comment by ahmad2smile** [comment]
I build the source for the docs & It works there. Is anyone working on it? No PR that I see.. and the site demo still no working.

**Comment by alextrastero** [comment]
#239 fixes this
