### ISSUE TITLE
.sideNav() is not a function in SideNav.js

### ISSUE THREAD

**Issue by rennitir08** [react-materialize/react-materialize#227]
Uncaught TypeError: $(...).sideNav is not a function
    at SideNav.componentDidMount (SideNav.js:47)

getting this error while pulling this library in from the react module.

![screen shot 2017-04-07 at 3 22 52 pm](https://cloud.githubusercontent.com/assets/25062273/24815957/07d9958a-1ba5-11e7-8e1b-edccbc52ebb5.png)
![screen shot 2017-04-07 at 3 23 10 pm](https://cloud.githubusercontent.com/assets/25062273/24815958/07de2e88-1ba5-11e7-8c0a-485b881c3db0.png)

**Comment by alextrastero** [comment]
Hey @rennitir08 could you paste here your `index.html`?

**Comment by rennitir08** [comment]
Hi, sure!

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <title>Commuter</title>
  </head>
  <body>
    <div id="root"></div>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
  </body>
</html>

**Comment by rennitir08** [comment]
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <title>Commuter</title>
  </head>
  <body>
    <div id="root"></div>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
  </body>
</html>

**Comment by alextrastero** [comment]
Seems like the `materialize.min.js` is broken, try replacing with the CDN version
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
```

**Comment by rennitir08** [comment]
that absolutely worked, thank you!
