### ISSUE TITLE
NavBar automatically hides items on medium or lower for mobile in place of a SideNav.

### ISSUE THREAD

**Issue by JamesHealdUK** [react-materialize/react-materialize#228]
This is fine for some use cases but its not always ideal, especially if youre only dealing with a few icon buttons in your nav.

Itd be a good idea to add a prop for enabling and disabling it.

**Comment by reesmanp** [comment]
I can get behind this.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
