### ISSUE TITLE
Accessing PropTypes via the main React package for autocomplete component

### ISSUE THREAD

**Issue by ingin** [react-materialize/react-materialize#233]
As you've fixed this for other components, could you please fix it for autocomplete component ?
Tks,
Best regards

**Comment by caritosteph** [comment]
The Autocomplete file still generating the following: 

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

could you please fix it, please?

**Comment by alextrastero** [comment]
fixed in 0.18.3
