### ISSUE TITLE
Accessing Values from Inputs

### ISSUE THREAD

**Issue by hermano360** [react-materialize/react-materialize#236]
In the traditional React inputs in forms, you are able to access the values with this.refs.title.value, for example. Is there a simple way to access the values that are written by the user? Thanks!

**Comment by alextrastero** [comment]
Hey @hermano360 if you've added a `ref` to the `Input` you can get the input value with:
```js
this.refs.title.state.value
```

**Comment by alextrastero** [comment]
please reopen if this is not solved
