### ISSUE TITLE
Mobile Responsive Navbar should be closed programmatically

### ISSUE THREAD

**Issue by antoinedejonckheere** [react-materialize/react-materialize#237]
Would it be possible to implement a way to close the SideNav that is rendered in the mobile version of the NavBar in a programmatic way.

Use case:
 I'm using a NavBar as navigation menu for a react website using react-router.
When on mobile view, when I click on a menu item, I get redirected but the SideNav remains open.

I would be great to have an option to automatically close the SideNav OR having a programmatic way to do it.

What are your thoughts?

**Comment by alextrastero** [comment]
Hi @antoinedejonckheere, if you add a `ref` to the `SideNav` you can close it with:
```js
$(this.refs.mySideNav).sideNav('hide');
```

please reopen if it's not solved :)

**Comment by antoinedejonckheere** [comment]
@alextrastero how can I do this specifically with the `NavBar`, since i'm not directly handling the `SideNav`?

**Comment by alextrastero** [comment]
You can use it for the `NavBar` too, give it a ref and use the jquery method

**Comment by alextrastero** [comment]
the method being: $(this.refs.myNavBar).sideNav('hide');

**Comment by pleopardi** [comment]
You can also use the [options](http://materializecss.com/side-nav.html#options) object: `<Navbar options={{ closeOnClick: true }}>`
