### ISSUE TITLE
Text input label misbehavior

### ISSUE THREAD

**Issue by IonutLaceanu** [react-materialize/react-materialize#24]
Hi!

When are you planning to publish the current codebase in npm?

There is a problem in the current npm package, with the behavior of the label when I provide a `defaultValue`. 
![screenshot 2016-01-08 23 53 12](https://cloud.githubusercontent.com/assets/2991577/12210550/75e13536-b663-11e5-9cce-6cee8dc5da4b.png)

The problem dissapears when I first click on the Input.
![screenshot 2016-01-08 23 53 19](https://cloud.githubusercontent.com/assets/2991577/12210556/80e45efe-b663-11e5-8284-e3e5d97bb0c0.png)

This is fixed when I'm using the `Input` component from the current master branch.
![screenshot 2016-01-08 23 58 56](https://cloud.githubusercontent.com/assets/2991577/12210614/e131bd88-b663-11e5-80c2-359ff06ccc98.png)

Keep up the good work!

**Comment by isaiah** [comment]
@IonutLaceanu yes, this problem is fixed in master.

**Comment by isaachinman** [comment]
@isaiah Also wondering when you plan to publish the current codebase to the npm package.

**Comment by isaiah** [comment]
@isaachinman @IonutLaceanu I just pushed 0.14.0-beta4 to npm. Please let me know if you find any problems.

**Comment by isaiah** [comment]
@isaachinman @IonutLaceanu there is a problem with the previous package, bumped to `0.14.0-rc1`
