### ISSUE TITLE
Add Toast to DOCS

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#245]
Currently there's no examples for the `Toast` component in the docs, it would be great if someone could grab this.

**Comment by isaiah** [comment]
The original `Toast` is very jQuery heavy, if we could implement one without jQuery would be fanstastic!

**Comment by brainzest** [comment]
@alextrastero  Hi! Can you please review the commit?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
