### ISSUE TITLE
Opening modals programatically?

### ISSUE THREAD

**Issue by jordanwallwork** [react-materialize/react-materialize#246]
I need to use a modal without having a specific trigger button, this this possible?

To clarify my use case, if a user is logged in and tries to do something requiring login a modal with a registration/login form pops up in a modal, so I need to be able to trigger it programmatically as there are multiple possible triggers throughout the application

**Comment by alextrastero** [comment]
Hey @jordanwallwork, this is how I get it working:
```js
import React from 'react';
import { Modal } from './react-materialize';

class App extends React.Component {
  constructor () {
    super()
    this.showModal = this.showModal.bind(this);
    this.id = 'yo'
  }

  showModal () {
    $(`#${this.id}`).modal('open');
  }

  render () {
    return (
      <div>
        <a onClick={this.showModal}>Show Modal</a>
        <Modal id={this.id} modalOptions={ { dismissible: true, inDuration: 30 } }><p>sup</p></Modal>
      </div>
    )
  }
};

export default App;

```

**Comment by alextrastero** [comment]
please reopen if it's still an issue

**Comment by tamal-appsbee** [comment]
Still there issue   $(`#${this.id}`).modal('open'); not working

**Comment by alextrastero** [comment]
@tamal-appsbee what version of `react-materialize` are you using?

**Comment by zjacek12** [comment]
I am having the same problem and I am using "react-materialize": "^1.0.4", The error says $ isnt defined.

**Comment by alextrastero** [comment]
Hey @zjacek12, can I see your `index.html`

**Comment by zjacek12** [comment]
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  
  <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  
  <title>React App</title>
</head>
<body>
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
<div id="root"></div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

</body>
</html>

**Comment by zjacek12** [comment]
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  
  <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  
  <title>React App</title>
</head>
<body>
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
<div id="root"></div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

</body>
</html>
`

**Comment by zjacek12** [comment]
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  
  <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  
  <title>React App</title>
</head>
<body>
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
<div id="root"></div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

</body>
</html>

**Comment by zjacek12** [comment]
```
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <!--
    manifest.json provides metadata used when your web app is added to the
    homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
  -->
  <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  <!--
    Notice the use of %PUBLIC_URL% in the tags above.
    It will be replaced with the URL of the `public` folder during the build.
    Only files inside the `public` folder can be referenced from the HTML.

    Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
    work correctly both with client-side routing and a non-root public URL.
    Learn how to configure a non-root public URL by running `npm run build`.
  -->
  <title>React App</title>
</head>
<body>
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
<div id="root"></div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
<!--
  This HTML file is a template.
  If you open it directly in the browser, you will see an empty page.

  You can add webfonts, meta tags, or analytics to this file.
  The build step will place the bundled scripts into the <body> tag.

  To begin the development, run `npm start` or `yarn start`.
  To create a production bundle, use `npm run build` or `yarn build`.
-->
</body>
</html>

```

**Comment by alextrastero** [comment]
Thanks! so where are you loading the javascript that includes `react-materialize` ?

**Comment by alextrastero** [comment]
ideally you should load the javascripts in this order
- jquery
- materialize
- bundle.js (bundled javascript which requires/includes reac-materialize)

**Comment by zjacek12** [comment]
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <!--
    manifest.json provides metadata used when your web app is added to the
    homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
  -->
  <link rel="manifest" href="/manifest.json">
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  <!--
    Notice the use of  in the tags above.
    It will be replaced with the URL of the `public` folder during the build.
    Only files inside the `public` folder can be referenced from the HTML.

    Unlike "/favicon.ico" or "favicon.ico", "/favicon.ico" will
    work correctly both with client-side routing and a non-root public URL.
    Learn how to configure a non-root public URL by running `npm run build`.
  -->
  <title>React App</title>
</head>
<body>
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
<div id="root"></div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
<!--
  This HTML file is a template.
  If you open it directly in the browser, you will see an empty page.

  You can add webfonts, meta tags, or analytics to this file.
  The build step will place the bundled scripts into the <body> tag.

  To begin the development, run `npm start` or `yarn start`.
  To create a production bundle, use `npm run build` or `yarn build`.
-->
<script type="text/javascript" src="/static/js/bundle.js"></script></body>
</html>

```

I think this is what you were looking for. Once compiles the bundle script tag is inserted

**Comment by alextrastero** [comment]
maybe `react-create-app` has some mechanism for adding external libraries that isn't through to `index.html`

**Comment by alextrastero** [comment]
this only happens with the `Modal` ? can you try the `Dropdown`?

**Comment by zjacek12** [comment]
I dont see how using a different component would change anything since the error I get is that $ isn't defined

**Comment by zjacek12** [comment]
fixed using npm package react-async-script

**Comment by alextrastero** [comment]
Yeah, so the problem is react-create-app

**Comment by mcopley08** [comment]
Hey @zjacek12, do you have example code of how you got it working with "react-async-script"?

Also, is there no way to use things like: `$("$id").modal('open');` in a react component without having an npm package to load it?

I can include the JS file in index.html and have it accessible in the client webpage, but I feel like there's definitely a way to add the Materialize.js functions to use in components...

I also started my app using the `create-react-app` command, I'm not sure if that's still the issue or not. Thanks so much for any guidance!

**Comment by tamal-appsbee** [comment]
@alextrastero It is working now.
Thanks

**Comment by iMerica** [comment]
Modals don't work at all for me on React 16. I'm essentially doing the same thing as https://github.com/react-materialize/react-materialize/issues/246#issuecomment-301704260;

**Comment by alextrastero** [comment]
Hey @iMerica, are you getting any errors in the console?

**Comment by bachskeys** [comment]
why havent they added a bool props to open and close your componentes geez it be way easier.

**Comment by alextrastero** [comment]
There is https://github.com/react-materialize/react-materialize/blob/master/src/Modal.js#L156

**Comment by amyfang3** [comment]
@zjacek12 @alextrastero How do you use npm package react-async-script to fix it? Do you have a code example?
