### ISSUE TITLE
Any plans to implement the Materialize datepicker?

### ISSUE THREAD

**Issue by isaachinman** [react-materialize/react-materialize#25]
Hi, any plans to rewrite the [Materialize datepicker](http://materializecss.com/forms.html) (which depends on pickadate) as a React component?

**Comment by isaiah** [comment]
There is not so much to do for this component, since this library already requires that `materializecss.js` loaded in global namespace, I imagine you can create the datepicker with

```jsx

<Input className='datepicker' />
```

Could you try this out?

**Comment by isaachinman** [comment]
Yes it works, but it doesn't seem to fire any onChange events.
