### ISSUE TITLE
Trigger a modal with a Card

### ISSUE THREAD

**Issue by gustavo-depaula** [react-materialize/react-materialize#274]
Is that possible?

**Comment by gustavo-depaula** [comment]
I made it. It's possible.

**Comment by tiempham** [comment]
How can you? Explain me please.

**Comment by alextrastero** [comment]
Hey @tiempham, if you check the docs, on the Modal there's an example of no trigger, there you can find how it's done :)

**Comment by tiempham** [comment]
Thank @alextrastero! I found it.
