### ISSUE TITLE
Input uncrotrolled switch to controlled

### ISSUE THREAD

**Issue by mathieusanchez** [react-materialize/react-materialize#276]
I have this probleme and i don't know how to solve it, someone can help me ?

"Warning: Input is changing an uncontrolled input of type date to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. "

**Comment by atpyatt** [comment]
This is because both the value and defaultValue properties of the component have been set. You should either just set defaultValue and let the component maintain it's own state, or just set value and have the parent control the state of the child component.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
