### ISSUE TITLE
Getting rid of jQuery dependency

### ISSUE THREAD

**Issue by cemremengu** [react-materialize/react-materialize#277]
I believe one of the main tasks should be getting rid of the jquery dependency for this library. (I know that's genius :smile: )

Any roadmaps for this? Let's start an epic so it can gain contributor traction slowly and help shape the ideas.

**Comment by isaiah** [comment]
Good initiative, we've always have that in mind TBH, but that's not an easy task, maybe we can implement jQuery components in parallel, and the user can choose their preferred ones.

**Comment by jeromepeters** [comment]
Any updates on this?

**Comment by alextrastero** [comment]
Hey @jeromepeters, `react-materialize` is just a react wrapper for `materializecss` which requires jQuery, it would require lots of effort and time to do this, so for now, it's not been planed.

**Comment by friek108** [comment]
MaterializeCss 1.0 alpha has been released which has no jQuery dependency.. http://next.materializecss.com 

Not sure how this would be constructed but certainly looks like a possibility for the roadmap?

**Comment by alextrastero** [comment]
thanks @friek108, it sure does look promising

**Comment by alextrastero** [comment]
Done
