### ISSUE TITLE
Collapsible resetting child's states when reopening

### ISSUE THREAD

**Issue by fredericocurti** [react-materialize/react-materialize#288]
Hey there, I've been really enjoying using the library, and the collapsible component is awesome, but it has a critical flaw: for some reason, any CollapsibleItem's children states are not kept when you reopen it, making the component unusable for any more complex application other than showing text. I've tried fixing it by setting the component's renderBody function to show a state.children array instead of the props.children initially, and refreshing manually from its wrapper, with no success. I've also tried getting a ref from the CollapsibleItem and manually trying to set it's state.children to it's instance children, also without success. Is this really a issue or i'm the only one experiencing it? Could it be getting a fix anytime soon?

**Comment by isaiah** [comment]
https://github.com/react-materialize/react-materialize/pull/286 will fix it.
