### ISSUE TITLE
Button color props

### ISSUE THREAD

**Issue by jaburcodes** [react-materialize/react-materialize#291]
Today to change the Button component color we have to do:
<Buttton className="red">

It would be much more user friendly if we could do:
<Buttton color="red">

In other words add a 'color' props.

I would like to work on it if possible :)

**Comment by alextrastero** [comment]
This prop would only pass his value to `className`, why not just use `className`?

**Comment by alextrastero** [comment]
Current solution:
`<Button waves='light' className='pink lighten-1'>EDIT ME<Icon left>save</Icon></Button>`
Proposed solution:
`<Button waves='light' color='pink lighten-1'>EDIT ME<Icon left>save</Icon></Button>`

I'm not sure it adds any value

**Comment by alextrastero** [comment]
If you would like to contribute there's a label in `issues` called `help-wanted` :)

**Comment by jaburcodes** [comment]
Yes, i would love to contribute and i'll check them.

Using a color props is much more user friendly, but ok, its up to u. haha.

**Comment by alextrastero** [comment]
For now, i'll leave it as is, if someone else comments we'll see...
