### ISSUE TITLE
how to focus an input 

### ISSUE THREAD

**Issue by hrishikhanapure** [react-materialize/react-materialize#292]
Need a help to focus an input component of react-materialize.

**Comment by alextrastero** [comment]
You can accomplish this by adding an id or ref to the `<Input />` and then in `componentDidMount()` you can focus on it.

**Comment by DoubleHub** [comment]
This is not true. If you attach a ref to a `<Input />` component you still do not have access to the `focus()` function (just tried now).

**Comment by madnight** [comment]
Yup, that's because you get a ProxyComponent from ref which does not have the function `focus()`.  
Same problem here.

**Comment by alextrastero** [comment]
Ok, how about with `id`?

**Comment by madnight** [comment]
yup
```js
  componentDidMount() {
        document.getElementById("test").focus()
    }

  <Autocomplete id={"test"}/>
```
works, ty

**Comment by danny-faith** [comment]
@madnight , isn't that accessing the DOM, which is not advised with React?

**Comment by CloudPower97** [comment]
@madnight Did you read the [documentation](https://reactjs.org/docs/refs-and-the-dom.html)? 
It's the first example.

**Comment by danny-faith** [comment]
@CloudPower97  - that first example doesn't apply to Materialize / React components. For some reason it looks like Materialize didn't include the focus() method.
