### ISSUE TITLE
Update to the current version (0.99.0) of MaterializeCSS

### ISSUE THREAD

**Issue by 1eddy87** [react-materialize/react-materialize#296]
Does anybody know if this project is going to be updated so that we can get some of the new goodies of MaterializeCSS? @isaiah @alextrastero

**Comment by alextrastero** [comment]
@1eddy87 what goodies are you referring to?
You can decide which version of `materializecss` you want to use in your `index.html`

**Comment by alextrastero** [comment]
Closing issue, let me know if any further issues
