### ISSUE TITLE
Is the library compatible with a browser? 

### ISSUE THREAD

**Issue by extend1994** [react-materialize/react-materialize#314]
Hi! I am a member from CDNJS and in charge of adding this library according to https://github.com/cdnjs/cdnjs/issues/11546. In README.md, there is one line 
>  <script src="path/to/your/bundle.js"></script>

So I think this library should be bundled first and then can be used in a browser, right?
Or you can build the bundled file(s) for this library so that I can add this library to our CDN?
Thanks!

**Comment by crobinson42** [comment]
@extend1994 This library will support your request when #315 is completed.

**Comment by extend1994** [comment]
Thanks @crobinson42 :+1:
