### ISSUE TITLE
Add webpack or rollup module bundler

### ISSUE THREAD

**Issue by crobinson42** [react-materialize/react-materialize#315]
Refactor build process to use webpack or rollup module bundler and produce a UMD build to support:

-  script tag use in browser pages (ie: codepen or jsfiddle use cases)

- no longer need to include the css/js tags in the head off html

- bundle splitting imports for consumers of the library

**Comment by crobinson42** [comment]
@ruediste @alextrastero What do you guys think about supporting this feature? I'm happy to contribute and get a PR going to start a discussion on fine tuning this feature.

I see a major benefit with this being the script tags don't need to be included in the head and can be instead included in `react-materialize`'s bundling process which would allow the library to be consumed via imports. This pattern would give the library performance benefits in the manner of projects who consume it then get bundle splitting out of the gate if their project is setup for that.

**Comment by isaiah** [comment]
@crobinson42 Correct me if I'm wrong, `react-materialize` has implicit dependency on `materializecss`, which to my knowledge doesn't comfort to any module system. cc: @alextrastero

**Comment by crobinson42** [comment]
@isaiah Publishing via webpack using css-modules which import the css into the chunks will satisfy your concern regarding the dependency on stylesheets.
