### ISSUE TITLE
Modal Options not working

### ISSUE THREAD

**Issue by kartboy16** [react-materialize/react-materialize#317]
Anyone else having an issue where modalOptions does not work?  I set dismissible, ready and complete and they used to work but now they don't.  

EDIT:  Using MeteorJS 1.5.1 which forces the use of Materialize 0.99.0 which for some reason modalOptions not working.  Materialize 0.100.1 seems to work but waiting for Meteor fix; [Materialize issue #5010](https://github.com/Dogfalo/materialize/issues/5010).

FIX:  For Meteor users, move to the NPM version.

**Comment by aravind1078** [comment]
@kartboy16  mine is react 15.6.2 react-materialize 1.0.10 meteor version  1.5.2.2 modalOptions not working 
`<Modal
        id='VideoPlayer'
        modalOptions={{ dismissible: false,
          complete: this.handleClose }}
        trigger={
          <VideoPlay
            className='modal-close'
            onClick={this.handleTrigger}
            id='myBtn3'
            style={{ marginBottom: '0px',
            }}
          > PLAY VIDEO
          </VideoPlay>}>
        <div id='overlay' className='modal-close modal-action' data-toggle='VideoPlayer' onClick={this.handleClose}>
          <i className='material-icons close'>close</i>
        </div>
        <div className='flowplayer'>
          <video id='Player1'>
            <source type='video/webm' src='//edge.flowplayer.org/bauhaus.webm' />
            <source type='video/mp4' src='//edge.flowplayer.org/bauhaus.mp4' />
          </video>
        </div>
      </Modal>
`

**Comment by alextrastero** [comment]
Hey @AleF83, how did you en up solving this? Thanks!

**Comment by maximelb** [comment]
Using 0.100.2 and problem still seems to be existing.

**Comment by alextrastero** [comment]
@maximelb what issue exactly?

**Comment by alextrastero** [comment]
If you pass modalOptions prop to Modal: https://github.com/react-materialize/react-materialize/blob/master/src/Modal.js#L26

**Comment by alextrastero** [comment]
Hey @maximelb, first you need to make sure `modalOptions` has the same format as specified in the materialize-docs site: http://archives.materializecss.com/0.100.2/modals.html

I had the same issue as you because I was using an older version of materialize-css
![screen shot 2018-04-02 at 1 22 40 pm](https://user-images.githubusercontent.com/4152819/38194641-f9756a60-3678-11e8-83de-27cdfb30ccd3.png)

**Comment by maximelb** [comment]
Ah! Thank you, that was it I was using the 1.0 beta option on the 0.100. The old (non-beta) parameter was "complete" and not "onCloseStart".
