### ISSUE TITLE
Modal Style

### ISSUE THREAD

**Issue by kartboy16** [react-materialize/react-materialize#319]
When creating the `<Modal>` with `style={{ height: '95%', maxHeight: '95%', width: '70%', margin: '0px auto' }}` works fine the first time I click the trigger.  If I close and click again, the style goes back to the default style.  

I'm assuming it's cause Materialize rewrote Modal.  Anyone else?  

```
React-Materialize 1.0.6
Materialize 0.100.1
```

**Comment by alextrastero** [comment]
Hey @kartboy16 if you check in the docs, you can add that prop to the editable textarea, seems to work fine there

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
