### ISSUE TITLE
Unable to Use Two <Tabs/> on the Same Page

### ISSUE THREAD

**Issue by strin** [react-materialize/react-materialize#325]
To reproduce, simply 

```
<Tabs className='tab-demo z-depth-1'>
		<Tab title="Test 1">Test 1</Tab>
		<Tab title="Test 2" active>Test 2</Tab>
</Tabs>

<Tabs className='tab-demo z-depth-1'>
		<Tab title="Test 1">Test 1</Tab>
		<Tab title="Test 2" active>Test 2</Tab>
</Tabs>
```

It seems the <Tab/> element renders with an `id` to be `tab-0`, `tab-1`, `tab-2`, ... Therefore, the scope is the same for both elements.

**Comment by raullarosa** [comment]
I reproduced on my local machine and I am experiencing the same issue. Even after rendering one <Tabs /> in the parent component and the second <Tabs /> in the child component. The <Tabs /> that was rendered first is the one with the "higher power" and rendering the second Tabs useless.

I will look into the documentation and see if there is a way to fix this, if you need this urgently, I would recommend falling back to the jQuery version from materialize.

**Comment by alextrastero** [comment]
Hey @strin @raullarosa, could you have a look at the linked PR, this will solve the init issue

**Comment by strin** [comment]
@alextrastero thanks for solving this issue! Is this on npm yet?

**Comment by alextrastero** [comment]
Yeah sure it is :)
