### ISSUE TITLE
Missing Components

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#33]
### Components
- [x] Badges
- [x] Buttons
- [x] Breadcrumbs
- [x] Cards
- [x] Chips
- [x] Collections
- [x] Footer
- [x] Forms
- [x] Icons
- [x] Navbar
- [x] Pagination
- [x] Preloader

### JS
- [x] Collapsible
- [ ] Dialogs
- [x] Dropdown
- [x] Media
- [x] Modals
- [ ] Parallax
- [ ] Pushpin
- [ ] ScrollFire
- [ ] ScrollSpy
- [ ] SideNav
- [x] Tabs
- [x] Transitions
- [x] Waves

**Comment by isaiah** [comment]
Updated a few, the `icon` component is already there, i think `transition` and `wave` are effect, not component.

**Comment by richmeij** [comment]
Are there any plans yet to implement the SideNav component?

**Comment by evgenosiptsov** [comment]
Is there carousel component?

**Comment by jsbranco** [comment]
@evgenosiptsov  Not sure if you were able to find down if there is such component. I don't see anything in the code which has it.
