### ISSUE TITLE
SideNav does not work

### ISSUE THREAD

**Issue by mehdipourfar** [react-materialize/react-materialize#330]
When I want to trigger sidenav, I get this error:
e.velocity is not a function

**Comment by eXo5** [comment]
Can you leave the part of the code that is giving you the error?

**Comment by alextrastero** [comment]
It seems this is a known issue: https://github.com/Dogfalo/materialize/issues/1229
It seems Aguego has the solution :)

**Comment by mehdipourfar** [comment]
It worked. Thanks.
But it seems that there should be a good document on integrating this package with create-react-app

**Comment by alextrastero** [comment]
Ah I see, we should add a known issues section to the readme, what other issues did you run into? how did you fix this issue?

**Comment by mehdipourfar** [comment]
The other issue was including the scss files to the library. I've added this script
`"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src/scss/ --include-path ./node_modules/materialize-css/sass/ src/scss/ -o src/css/ --watch --recursive"`
and imported library scss components to my main scss file.
