### ISSUE TITLE
Parallax example has a typo

### ISSUE THREAD

**Issue by TaisukeYasuda** [react-materialize/react-materialize#331]
Although Parallax is not described in https://react-materialize.github.io/#/, I wanted to use it and found the source in `src` and the example in `example`. The example did not work, but that was just because it had a typo and used the prop `imgSrc` instead of `imageSrc`. I was able to use `import { Parallax } from 'react-materialize'` in my project, so perhaps you could fix this very quickly and add it to the documentation so more people can use it.

**Comment by alextrastero** [comment]
Hey @TaisukeYasuda, PR's are welcome :) but yes, thanks for pointing that out

**Comment by isaiah** [comment]
fixed by #333
