### ISSUE TITLE
collapsible item or dropdown in topNav/SideNav

### ISSUE THREAD

**Issue by Gunnar34** [react-materialize/react-materialize#332]
I've been playing around with the components for awhile and I can't seem to implement anything that would be a dropdown in Top nav but converts to collapsible in sideNav. I also wasn't able to get anything to work inside the NavItem tag except for button or dropdown. Am i missing something obvious?

**Comment by isaiah** [comment]
Not sure if I got your problem correctly, sounds like you have to implement the top nav and side nav separately, while you can share the data structure that supports both. For the second question, `NavItem` is simply a syntax wrap around `<li><a /></li>`

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
