### ISSUE TITLE
Carousel Initialization and Autoscroll

### ISSUE THREAD

**Issue by bcf3ah** [react-materialize/react-materialize#337]
Hello! 

Is there an autoscroll option for the carousel? I didn't see one in the options link you provided (for regular MaterializeCSS), and I'm getting an error if I try use a carousel() method with jquery in componentDidMount(). Right now, I'm doing this:

`  componentDidMount(){
    var counter = 0;
    setInterval(() => {
      if(counter === 4){
        counter = 0;
      }
      counter++;
      var selector = counter.toString();
      $(`.${selector}`).trigger("click");
    }, 5000);
  }`

I'm just simulating a click on each of my 4 carousel children, but obviously this is a bit of a hack. Any thoughts? Thanks!

**Comment by alextrastero** [comment]
@bcf3ah https://stackoverflow.com/questions/36581504/materialize-carousel-slider-autoplay

**Comment by alextrastero** [comment]
Closing as it's not a react-materialize issue
