### ISSUE TITLE
Collapsed Navbar seems to be broken in the latest version

### ISSUE THREAD

**Issue by lloydwatkin** [react-materialize/react-materialize#342]
Its a possibility that the API has changed but I haven't found anything to support this.

My Navbar is set up as follows (for example):

```javascript
return (
      <div className='navbar-fixed teal lighten-1'>
        <Navbar brand='OLIO' right data-role='navigation'
          className='teal lighten-1' options={{ closeOnClick: true }}>
          <NavItem className={this.getClassIfActive('/articles')}
            onClick={this.props.refreshAndBrowse}>
            <Icon left>view_list</Icon>
            <span>{t('BROWSE')}</span>
          </NavItem>
)
```

Previously when making the browser narrower the menum would collapse into:

![screenshot from 2017-08-22 15-11-02](https://user-images.githubusercontent.com/271622/29569673-219a9df8-874c-11e7-8bef-03494fc78475.png)

Which it still does, however when I click this I am no longer presented with my menu options, but the following:

![screenshot from 2017-08-22 15-11-55](https://user-images.githubusercontent.com/271622/29569717-419d134c-874c-11e7-8254-16dc18009872.png)

It looks possibly like the menu isn't being generated or dragged over?

**Comment by lloydwatkin** [comment]
I can see the HTML gets generated by the component

![screenshot from 2017-08-22 15-32-53](https://user-images.githubusercontent.com/271622/29570736-401c7a0a-874f-11e7-9d84-01a99dfacbe0.png)

**Comment by lloydwatkin** [comment]
I've done a little more digging... 

The generated HTML seems very similar to that in the materialize docs. 
Its missing the <a> wrapper which if I add gets me the menu items, seems to caused here https://github.com/react-materialize/react-materialize/blob/master/src/NavItem.js#L5 (although its the same issue as the main nav too which doesn't cause a problem).

In order to get the sidebar to stand out above the overlay I have to reduce the overlay's z-index from 997  to something less.

**Comment by lloydwatkin** [comment]
Linked to #289, however there's still a bug if you don't have the `<a/>` tag.

**Comment by lloydwatkin** [comment]
If I change my `<NavItem/>` syntax to:

```jsx
          <NavItem className={this.getClassIfActive('/articles')}>
            <a onClick={this.props.refreshAndBrowse}>
              <Icon left>view_list</Icon>
              <span>{t('BROWSE')}</span>
            </a>
          </NavItem>
```

This solves one issue, I don't like it but it works. 

Just need to see if the workarounds solve the overlay issue for me.

**Comment by alextrastero** [comment]
Hi @lloydwatkin, you're right, we need to add a bit more logic to `NavItem` to support this.
The change happened here: https://github.com/react-materialize/react-materialize/pull/328, to fix this issue: https://github.com/react-materialize/react-materialize/issues/326
Need to find another solution though...

**Comment by lloydwatkin** [comment]
```css
#sidenav-overlay {
  z-index: 996;
}
```

worked for me

**Comment by alextrastero** [comment]
yeah, but it doesn't solve the `NavItem` issue

**Comment by lloydwatkin** [comment]
No, agreed. There's a workaround short term, so I can continue working and hopefully others can benefit.  A fix can come with time :)

**Comment by tomscholz** [comment]
This is actually an issue with materialize. The sidenav ul needs to be moved  outside of its wrappers. See https://github.com/Dogfalo/materialize/issues/3844

**Comment by JFernandoGomez** [comment]
this Issue should be fixed if using ReactPortal, not only for Overlay.js like mentioned here
https://github.com/react-materialize/react-materialize/issues/434
but also for the SideNav, will try to create a PR for this

**Comment by JFernandoGomez** [comment]
@alextrastero I could help you there too, maybe having the fix on both versions (actual and new one) would be good

**Comment by alextrastero** [comment]
Sure, make sure to have a look at there upgrade guide for the Sidenav: https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md#sidenav

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
