### ISSUE TITLE
What do the s,m,l props for the <col> component do? Why are they needed>

### ISSUE THREAD

**Issue by davidfufu** [react-materialize/react-materialize#343]
Docs are unclear. Isn't the point of a responsive grid to conform to any screen size? Why have three sizes?

**Comment by alextrastero** [comment]
Hi @davidfufu, it's a 12 column grid system, maybe it's clearer in these docs: http://materializecss.com/grid.html. But the idea is that you can specify how many columns you want a component to occupy on each breakpoint:
```js
<Section s={12} m={6} l={3}>
  // content
</Section>
```

**Comment by davidfufu** [comment]
Thanks, I get it now. Stupid question.

**Comment by alextrastero** [comment]
No such thing as a stupid question :-)
