### ISSUE TITLE
options prop does not work for Dropdown

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#347]
options prop does not work for Dropdown.

```
                    <Dropdown trigger={<Button>Search</Button>}
                            options={{constrainWidth:false,belowOrigin:true}}
                        >
                        <NavItem>Everything</NavItem>
                    </Dropdown>
```

**Comment by alextrastero** [comment]
Try with `{hover: true}`, the options are passed, but `belowOrigin` changes the position, maybe there's some CSS that we need to add separately

**Comment by alextrastero** [comment]
Strange, `options={{belowOrigin: true, hover: true}}` works but not `options={{belowOrigin: true}}` can you confirm?

**Comment by weasteam** [comment]
Confirmed. `options={{belowOrigin: true, hover: true}}` works for me. 

But without `{hover: true}`. The options do not work.

**Comment by weasteam** [comment]
`{hover: false}` also does not work.

**Comment by alextrastero** [comment]
That seems like an issue with materializecss because all we do is pass the props to the dropdown init function

**Comment by weasteam** [comment]
materializecss works for me. But I am using the newest version. `0.100.2`.

The [documentation](https://react-materialize.github.io/#/), use `0.98.0`

**Comment by alextrastero** [comment]
Closing, let me know if this is still an issue

**Comment by desirelabs** [comment]
Having the same issue : 
```
options={{alignment: 'right'}}
```
Needs `hover: true` to work.
Using react-materialize v1.0.14 and materialize 0.100.2

I used the v0.98.0 and same issue.

**Comment by alextrastero** [comment]
True, it seems that if hover is set, the dropdown is placed after initialisation: 
https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js#L74
I'm not sure yet how to solve this

**Comment by victor-priceputu** [comment]
I can also replicate, when using the `hover: false` option, then no other options are taken into account, but the defaults; `origin` is empty when the options check is done.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
