### ISSUE TITLE
container class for Navbar?

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#348]
`container` is a class to limit the width of page display. 

Is there any way to add `container` class to Navbar? Just like Github Navbar. 

When I add the `container` to the Navbar directly, it cut off the background, which is not pretty.

**Comment by alextrastero** [comment]
Hey @weasteam, `container` class is limiting the page display, and that's why the NavBar is cut off, because of `container`. Why do you want to add container class to Navbar? why not add another class and style yourself?

**Comment by weasteam** [comment]
May be I did not describe my requirement clear enough:

What I want is to limit the content of Navbar (and still keep the background of it), not limiting the whole Navbar. See the Github as an example. If you have a big screen, the logo and the buttons do not go all the way to the edge. It stays in the middle.

Currently, if I put the `container` to Navbar, it will limit the whole Navbar. It would be great if it goes to `nav-wrapper`. 

The [Materializecss](http://materializecss.com/grid.html) already have such function, I think it is easier to use the resource that already available.

```
<nav>
          <div class="nav-wrapper container">
            <div class="col s12">
              <a href="#!" class="brand-logo">Logo</a>
              <ul class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">JavaScript</a></li>
              </ul>
            </div>
          </div>
        </nav>
```

**Comment by alextrastero** [comment]
Did you manage to solve this?

**Comment by weasteam** [comment]
I think so, I can close it. I just use the materilizedcss to resolve the problem.

**Comment by hnoor** [comment]
I had the same issue. so I added a container props, the same way you use the fixed props, to the navbar class. works perfectly for me. looks like this 

`  render () {
    const {
      brand,
      className,
      fixed,
      left,
      right,
      href,
      container, //container prop
      ...other
    } = this.props;

    delete other.options;

    let classes = {
      right: right,
      'hide-on-med-and-down': true
    };

    let brandClasses = {
      'brand-logo': true,
      right: left
    };

    let wrapper = 'nav-wrapper';

    if (container) {
      wrapper = 'nav-wrapper container'; //add container to the nav-wrapper
    }

    let content = (
      <nav {...other} className={className}>
        <div className={wrapper}>
          <Col s={12}>
            <a href={href} className={cx(brandClasses)}>{brand}</a>
            <ul className={cx(className, classes)}>
              {this.props.children}
            </ul>
            {this.renderSideNav()}
            <a className='button-collapse' href='#' data-activates='nav-mobile'>
              <Icon>view_headline</Icon>
            </a>
          </Col>
        </div>
      </nav>
    );

    if (fixed) {
      content = <div className='navbar-fixed'>{content}</div>;
    }

    return content;
  }
}

Navbar.propTypes = {
  brand: PropTypes.node,
  children: PropTypes.node,
  className: PropTypes.string,
  left: PropTypes.bool,
  right: PropTypes.bool,
  href: PropTypes.string,
  /**
   * Makes the navbar fixed
   */
  fixed: PropTypes.bool,
/**
 * adds container to Navbar
 */
  container: PropTypes.bool,`

**Comment by alextrastero** [comment]
Formatted:

```jsx
render () {
  const {
    brand,
    className,
    fixed,
    left,
    right,
    href,
    container, //container prop
    ...other
  } = this.props;

  delete other.options;

  let classes = {
    right: right,
    'hide-on-med-and-down': true
  };

  let brandClasses = {
    'brand-logo': true,
    right: left
  };

  let wrapper = 'nav-wrapper';

  if (container) {
    wrapper = 'nav-wrapper container'; //add container to the nav-wrapper
  }

  let content = (
    <nav {...other} className={className}>
      <div className={wrapper}>
        <Col s={12}>
          <a href={href} className={cx(brandClasses)}>{brand}</a>
          <ul className={cx(className, classes)}>
            {this.props.children}
          </ul>
          {this.renderSideNav()}
          <a className='button-collapse' href='#' data-activates='nav-mobile'>
            <Icon>view_headline</Icon>
          </a>
        </Col>
      </div>
    </nav>
  );

  if (fixed) {
    content = <div className='navbar-fixed'>{content}</div>;
  }

  return content;
}

Navbar.propTypes = {
  ...
  /**
   * Makes the navbar fixed
   */
  fixed: PropTypes.bool,
  /*
   * adds container to Navbar
   */
  container: PropTypes.bool
```

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
