### ISSUE TITLE
Select onChange getting fired twice

### ISSUE THREAD

**Issue by w3nisar** [react-materialize/react-materialize#350]
Hi There,
  I am unable to figure out why a select onChange event triggers twice, please check the code

`import React, { Component } from 'react';
import '../css/Dashboard.css';
import { Preloader,Button,Icon,Modal,Row,Input } from 'react-materialize';

const Dashboard = React.createClass({

    checkResourceAccess(){
        alert("s");
    },

    render(){

        return (
            <div> 
                <Row>
                    <Input s={12} type='select' label="Select Transaction type" className="browser-default" onChange={this.checkResourceAccess}>
                      <option value="null">Select</option>
                      <option value="Select 1">Select 1</option>
                      <option value="Select 2">Select 2</option>
                      <option value="Select 3">Select 3</option>
                      
                    </Input>
                </Row>  
            </div>
        )
    }

});

export default Dashboard;`

**Comment by alextrastero** [comment]
Looking into this :)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
