### ISSUE TITLE
Any plans to create an Data Table?

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#355]
A data table would be very helpful. See below two for as examples:

https://react-md.mlaursen.com/components/data-tables

https://react-mdl.github.io/react-mdl/components/datatable/

**Comment by alextrastero** [comment]
This project is supposed to be just a react port of materializecss, we already have https://github.com/react-materialize/react-materialize/blob/master/src/Table.js which is a Table layout
