### ISSUE TITLE
Materialize.toast is not defined

### ISSUE THREAD

**Issue by italopessoa** [react-materialize/react-materialize#362]
How can I use `Materialize.toast` without install react-materialize?
I've already added materialize css and js to my project, works great, but if I try to execute a toast, I get an error

![image](https://user-images.githubusercontent.com/9323529/30108888-899565de-92da-11e7-8a07-150b27ac1184.png)

**Comment by alextrastero** [comment]
This doesn't seem like a `react-materialize` issue. But it seems you might have issues with react-create-app

**Comment by dennisja** [comment]
use `window.Materialize.toast("My toast", 4000)`

**Comment by italopessoa** [comment]
@dennisja You're awesome man. Thank you!

**Comment by mritunjaymusale** [comment]
> use `window.Materialize.toast("My toast", 4000)`

This has now been updated to 

`window.M.toast({ html: 'Toast!' }, 1000)`

**Comment by anuljain23** [comment]
still not working for me

> > use `window.Materialize.toast("My toast", 4000)`
> 
> This has now been updated to
> 
> `window.M.toast({ html: 'Toast!' }, 1000)`

still not working for me
