### ISSUE TITLE
add componentWillUnmount() for jQuery inits

### ISSUE THREAD

**Issue by crobinson42** [react-materialize/react-materialize#365]
Should we add `componentWillUnmount()` destory methods for instances where a jQuery initializer is firing in cdm, ie: https://github.com/react-materialize/react-materialize/blob/master/src/Parallax.js#L7

I think that there is still an initialized instance in the DOM when we don't cleanup this type of initialization from jQuery/cdm.

**Comment by alextrastero** [comment]
Is this still an issue?
