### ISSUE TITLE
create-react-app example

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#372]
Maybe in the docs? Many people seem to be having problems including 3rd party JS/CSS into their apps when using create-react-app. A how-to would be great.

**Comment by alsaydali** [comment]
A problem with what? can you specify? 
I am using it with Create React App

**Comment by alextrastero** [comment]
Hey @alsaydali, it would be great to have a section in the readme explaining what issues appear when using this with `create-react-app`, like how you add jquery and materializecss libraries

**Comment by alextrastero** [comment]
more info: https://github.com/react-materialize/react-materialize/issues/381

ping @alsaydali ?? :)

**Comment by Pechalka** [comment]
I create test project with latest version react-materialize and 
$ create-react-app --version
1.4.1
https://github.com/Pechalka/create-react-app__react-materialize
It work for me.

How I can reproduce problem?

**Comment by onluiz** [comment]
I think was the problema 

> #4000 Fix escaping $ in environment variables. 

It was solved in create-react-app react-scripts 1.1.1. Here is the release notes: https://github.com/facebook/create-react-app/releases

I will try to test it more, but if the bug with $ is solved in this version of create-react-app, should I make a PR updating README.md?

**Comment by alextrastero** [comment]
Nice, closing if this is not an issue no more
