### ISSUE TITLE
show modal with No trigger requires jquery to work?

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#374]
As the example demonstrated at [https://react-materialize.github.io/#/modals](https://react-materialize.github.io/#/modals)

```
<div>
	<Button onClick={() => {
		$('#foo').modal('open')
	}}>Show Modal</Button>
	<Modal
		id='foo'
		header='Modal Header'>
		Lorem ipsum dolor sit amet
	</Modal>
</div>;
```

I get the error of `not found $`. It looks like I need to add `jquery` to my react. Please suggest:

1. Is there any method to make it work without using jquery?
2. If the jquery is absolutely necessary (I already included the script `<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>`), it would be great if the guidelines on how to make jquery work inside react component functions can be provided.

**Comment by weasteam** [comment]
I think this might be helpful to resolve my problem: [https://github.com/react-materialize/webpack-boilplate](https://github.com/react-materialize/webpack-boilplate)

**Comment by alextrastero** [comment]
Hey @weasteam,
1. `react-materialize` is just a react wrapper around materializecss. Materializecss depends on jquery, so yes. jQuery is absolutely necessary.

2. If you are using webpack out the box, you can include the script in your index.html. If you are using create-react-app, let me know

**Comment by alextrastero** [comment]
I would use https://github.com/alextrastero/react-webpack-boilerplate which is more up to date

**Comment by konfayakun** [comment]
For anyone uses react-create-app this issue may be helpful [issue2203](https://github.com/facebook/create-react-app/issues/2203)

**Comment by AwaMelvine** [comment]
You can do it without using jQuery in your react:

How about you programmatically trigger a click event on the Modal's display-none trigger property. Like so:

```
<Modal
  trigger={
<Button style={{ display: 'hidden' }} ref={button => this.modalButton = button}>MODAL</Button>
}
>
  Lorem ipsum ...
</Modal>
```
Now anywhere in your component, you can programmatically click that hidden [trigger] button without needing to use jQuery. 
Like so:
`this.modalButton.click().`

This works perfect for me.

**Comment by bflickinger** [comment]
@AwaMelvine You the real hero, thanks.
