### ISSUE TITLE
Card reveals broken since v1.0.11

### ISSUE THREAD

**Issue by stan-sack** [react-materialize/react-materialize#376]
Hey, just noticed that card reveals have broken in my app. Clicking on the image shows the ripple but doesn't display the reveal. Can confirm that this is occurring on your website: [https://react-materialize.github.io/#/cards](https://react-materialize.github.io/#/cards)

**Comment by stan-sack** [comment]
I was able to fix by downgrading to v1.0.10

**Comment by alextrastero** [comment]
Yes, it broke here: https://github.com/react-materialize/react-materialize/pull/336, we'll fix ASAP

**Comment by alextrastero** [comment]
This is now solved in `1.0.14`
