### ISSUE TITLE
Switching from select input to text input results in uncaught DOMException

### ISSUE THREAD

**Issue by TedJani** [react-materialize/react-materialize#380]
I'm creating a component that changes it's input type based on some properties.
The components work as expected when the Input is changed from a text type to a select type, but not vice-versa.
It seems that the DOM Node cannot be removed when attempting to change back:

DOMChildrenOperations.js:65 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

I've created a sample app using create-react-app to demonstrate:

```javascript
const OPTIONS = [{key: "RD", display: "Red"}, {key:"BL", display: "Blue"}, {key: "GR", display: "Green"}, {key: "YL", display: "Yellow"}]

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {inputVal: "", selectVal: "" }
    this.onChange = this.onChange.bind(this)
    this.renderOption = this.renderOption.bind(this)
  }

  onChange(name, event) {
    this.setState({...this.state, [name]: event.target.value})
  }

  renderOption(option) {
    return <option key={option.key} value={option.key}>{option.display}</option>
  } 

  render() {
    return (
      <div className="App">
        <Row>
          <Input s={6} type="text" value={this.state.inputVal} onChange={e => this.onChange("inputVal", e)} />

          <Input s={6} type={this.state.inputVal === "select" ? "select" : "text"} onChange={e => this.onChange("selectVal", e) } value={this.state.selectVal} >
            {this.state.inputVal === "select" ? OPTIONS.map(option => this.renderOption(option)) : null }
          </Input>
        </Row>
      </div>
    );
  }
}
```

**Comment by alextrastero** [comment]
This doesn't seem like an issue with `react-materialize`, in my opinion it's not a good idea to change a component's type based on an input `onChange`, maybe add a select with ['select', 'text'] and then onChange render a different type? or render both and hide and show depending on the state... ?

**Comment by TedJani** [comment]
The changing of the input type was just an example. A more real world use case would be a parent component setting the the property dictating wether the input should be a select or text.
Also, if I use an html select element instead of the react-materialize Input, everything works as expected. I believe that there is a bug here, since when the select Input component unmounts, it results in a DOMException, indicating a change is not reflected between the React Component and the underlying DOM model.

**Comment by alextrastero** [comment]
Hey @TedJani, would you like to give it a go and try to submit a PR? Maybe if you write a spec with your expected behaviour then it would be easier to solve, WDYT?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
