### ISSUE TITLE
React.js dependency should be peerDependencies?

### ISSUE THREAD

**Issue by uryyyyyyy** [react-materialize/react-materialize#384]
Hi.
My product wants to update `React.js` to v16.0, but `react-materialize` depends on v15.x.

Would you have plan to support v16.0? if so, I want to bring React.js to peerDependencies.
(in my case, use react-v16.0 with react-materialize works fine)

**Comment by alextrastero** [comment]
Hey @uryyyyyyy, we don't support React16 just yet, a couple components will need to be rewritten for that.
