### ISSUE TITLE
Controlled input in Autocomplete

### ISSUE THREAD

**Issue by dmitry-yudakov** [react-materialize/react-materialize#388]
Autocomplete component seems to support only uncontrolled input - the value is kept inside its internal state and I see no clear way of knowing when it's changed and also when the auto-complete  actually occurs.

I'll post a PR addressing this issue.

**Comment by harishrohokale** [comment]
@alextrastero Is this fix available in latest release? I am also not able to get the value once autocomplete is done. Or atleast need an event which will tells us that autocomplete is done.

I tried onChange and onAutocomplete but both did not work when autocomplete is done

**Comment by harishrohokale** [comment]
```<Autocomplete name='resource' onAutocomplete={this.onUpdateResource.bind(this)} title="Resource" s={12} data={this.RESOURCES}></Autocomplete>```

**Comment by harishrohokale** [comment]
I have pulled down from └── react-materialize@1.0.16  (git://github.com/react-materialize/react-materialize.git#544429c5c3d1efa1317cd01fe08994d1951d4aa2)

**Comment by alextrastero** [comment]
Did that make it work?

**Comment by matas30rubliu** [comment]
@alextrastero id is hardcoded for Autocomplete = creating multiple Autocomplete fields creates them with the same ID, please allow it to set as a prop.

https://github.com/react-materialize/react-materialize/blob/master/src/Autocomplete.js#L103

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
