### ISSUE TITLE
CardPanel does not accept inline styles

### ISSUE THREAD

**Issue by CoveTechnologyAus** [react-materialize/react-materialize#39]
There seems to be an issue when wanting to change the width of CardPanel with inline styles.
For example, if I have this: 
```
<Row id="login-page">
          <Col s={12}>
            <CardPanel className="center" style={{width:300px'}}  >
         </Col>
</Row>
```
the CardPanel still expands to the whole width of the column and inspecting the element style in Chrome I notice there is no "width" style on the CardPanel. The other components I have tried seem to accept inline styles.

Any ideas?

**Comment by isaiah** [comment]
The extra properties are not used for the `CardPanel` component, we could add that if really needed.
