### ISSUE TITLE
Does Dropdown and Modal conflicted to each other?

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#395]
I am trying to have each dropdown item to trigger one same model (Use No trigger method), the content of model will be updated from `onClick` event. 

I got these errors.

1) The first time to trigger model via clicking the dropdown list, only model background show up (the page get a little bit dark), the actual model does not pop out. 
2) The second time to click the dropdown, the dropdown menu does not show up.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
