### ISSUE TITLE
Select not working on react v16.0.0

### ISSUE THREAD

**Issue by jakemonton** [react-materialize/react-materialize#396]
I am using react-materialize v.1.0.14 and select is not working. Seems like there's a version mismatch since I am using v16.0.0 and react-materialize is still using v15.6.2. 

<img width="1262" alt="screen shot 2017-10-10 at 8 46 16 pm" src="https://user-images.githubusercontent.com/2330966/31387316-8e3f5e86-adfc-11e7-890c-04fcacd0ca09.png">

**Comment by alextrastero** [comment]
Yes, migrating to react16 is not trivial, we still haven't got round to do it :)

**Comment by jakemonton** [comment]
Yeah, I understand. Is there a workaround aside from downgrading the react version to 15.6.2?

**Comment by alextrastero** [comment]
I'm afraid not, `npm i -S react@15.x` is the only solution :)
