### ISSUE TITLE
Autocomplete returns null when minLength=0

### ISSUE THREAD

**Issue by stewmystre** [react-materialize/react-materialize#397]
Having issues with the drop down list not showing up properly when minLength={0}, it is acting like minLength={1} 

I believe I know where the issue is in the code ... Autocomplete.js line 34:

if (minLength && minLength > value.length || !value) {
      return null;
}

The "!value" will always return true for a string length of 0 regardless if minLength is set to 0

Recommend removing the '|| !value'

Maybe also make minLength default to 1 so that if users want the functionality of minLength 0 they must set it.

**Comment by stewmystre** [comment]
I can see why the ||!value was used as without this it will render the dropdown all the time with an empty string ... it is missing ... only activate when the input field has focus or is selected. This is what materializecss does. Not sure how to add that into the code ... is there an isSelected function maybe that can checked?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
