### ISSUE TITLE
Time Picker is not in documentation and doesn't appear to be implemented.

### ISSUE THREAD

**Issue by chris-gooley** [react-materialize/react-materialize#398]
Is the Time picker implemented? 

Materialize CSS reference: http://materializecss.com/forms.html#time-picker

**Comment by chris-gooley** [comment]
Okay, seems the materialize-css package needs to be updated to at least v0.99 before this can be done.

**Comment by chris-gooley** [comment]
#400 

Created pull request to upgrade materialize-css package and implement time picker.

**Comment by alextrastero** [comment]
Merged! `1.0.16`

**Comment by alextrastero** [comment]
p.s. please continue contributing!! :)
