### ISSUE TITLE
Input component placeholder and label collide

### ISSUE THREAD

**Issue by alexgsummer** [react-materialize/react-materialize#399]
- Visit https://react-materialize.github.io/#/forms
- Click the `first name` field and enter some text
- Backspace and remove the text
- Tab or click another field to make `first name` field lose focus
- Notice that the placeholder and label are now rendered on top of each other (see screenshot)
<img width="537" alt="screen shot 2017-10-12 at 11 04 44 pm" src="https://user-images.githubusercontent.com/1727086/31528524-caeab0be-afa1-11e7-8aa2-4b2805c7a948.png">

**Comment by alexgsummer** [comment]
I found a potential solution. From [materialize-css documentation](http://materializecss.com/forms.html):

"If you are having trouble with the labels overlapping prefilled content, Try adding class="active" to the label."

**Comment by usrivastava91** [comment]
@alexgsummer Thanks for the idea man. That's exactly the solution I was thinking. I think they applied it for default values, but not for labels.

PR : https://github.com/react-materialize/react-materialize/pull/509

**Comment by lazzy07** [comment]
Manually add "active" class to the label
example:
<label **className={props.active ? "active" : ""}** htmlFor={props.id}>

**Comment by huxaiphaer** [comment]
This is really so sad ☹️,

**Comment by ivofrancisco** [comment]
From what I've figured out it happens only when there is input field with type Password. And this is the best solution I came across:
autoComplete="new-password"

**Comment by alextrastero** [comment]
I just checked, this is fixed in `react-materialize@3.x`

**Comment by babehoney** [comment]
> I found a potential solution that you guys might be able to use. From [materialize-css documentation](http://materializecss.com/forms.html):
> 
> "If you are having trouble with the labels overlapping pre-filled content, Try adding class="active" to the label."

thank you
