### ISSUE TITLE
Logo poistion

### ISSUE THREAD

**Issue by clario** [react-materialize/react-materialize#4]
![skjermbilde 2015-06-24 kl 21 54 45](https://cloud.githubusercontent.com/assets/264754/8340023/fc4eff48-1abb-11e5-9658-eb0461926ae2.png)
Logo position is not good.

**Comment by isaiah** [comment]
This is an upstream issue, the materializecss site also have this problem. http://materializecss.com/navbar.html#icons

**Comment by yanickrochon** [comment]
Why is this an enhancement? It should be "wont fix" referring to the Materialize repo, no?
