### ISSUE TITLE
TextArea

### ISSUE THREAD

**Issue by jjbluesky** [react-materialize/react-materialize#402]
I'm missing the <TextArea> component. Is it planned to implement it in the future for react-materialize? Or is it available now and I just don't see it?

**Comment by alextrastero** [comment]
`<Input type="textarea"/>` should work :)

**Comment by ThatBrianDude** [comment]
Maybe we can add this to the docs? For a moment I thought it was skipped when porting to react.

I cant find it here: https://react-materialize.github.io/#/forms

**Comment by alextrastero** [comment]
Thanks @ThatBrianDude, will add asap
