### ISSUE TITLE
SideBar class text color on span

### ISSUE THREAD

**Issue by DiegoCorrea** [react-materialize/react-materialize#403]
Hi,
I search on documentation and try some things to make work, but nothing work.
I want change the exit:
`<a href="#!name"><span class="white-text name">asdasd</span></a>`
To:
`<a href="#!name"><span class="black-text name">asdasd</span></a>`

when i use:
<SideNavItem userView
          user={{
            background: `${'/images/place/painel/userBackgroundImage.png'}`,
            image: `${"/images/place/painel/logo-gray.png"}`,
            name: `${"asdasd"}`,
            email: `${"jdandturk@gmail.com"}`
          }}
        />
Any idea?

**Comment by alextrastero** [comment]
Hey @DiegoCorrea, i'm not sure I understand this well. You want to change the exit? asdasd to asdasd?

**Comment by DiegoCorrea** [comment]
Sorry for my bad explain. The GitHub read the HTML and embeed it. Sorry.
I what to change the class on span. Automatic the sidebar put "white-text" and i want to change it to another color, like black. 
"
<a href="#!name"><span class="white-text name">asdasd</span></a>
To:
<a href="#!name"><span class="black-text name">asdasd</span></a>
"

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
