### ISSUE TITLE
Modal - ReferenceError: Can't find variable: $

### ISSUE THREAD

**Issue by jjbluesky** [react-materialize/react-materialize#404]
I've tried to implement the basic modal example (https://react-materialize.github.io/#/modals). But when I click on the button, I just get an "ReferenceError: Can't find variable: $" (showOverlay OverlayTrigger.js:73). 

I'm using the current version of react-materialize.
Does anyone know why this could happen?

**Comment by alextrastero** [comment]
This can be because you are using `create-react-app`. If not, do you have an `index.html` including the jquery script?

**Comment by jjbluesky** [comment]
Yes, unfortunately I'm using create-react-app. Is there any fix for this? Including the jquery script didn't do the trick.

**Comment by alextrastero** [comment]
I see, have a look at these comments: https://github.com/facebookincubator/create-react-app/issues/679

**Comment by jjbluesky** [comment]
After adding jquery I've got another error and this helped: [](https://github.com/react-materialize/react-materialize/issues/381)

**Comment by ThatBrianDude** [comment]
@jjbluesky Which error was that? I am getting .modal() is not a function after importing jquery properly. I dont see how it should work
