### ISSUE TITLE
CollapsibleItem expanded doesn't work.

### ISSUE THREAD

**Issue by sfcgeorge** [react-materialize/react-materialize#405]
CollapsibleItem doesn't open initially even if `expanded` is set to true. I know the prop is being set properly because if I change it to "foo" then React complains that it's not a boolean, true or false it is happy with. But the collapsible doesn't initialize open as it should.

I can't obviously see the problem but it must be around here https://github.com/react-materialize/react-materialize/blob/544429c5c3d1efa1317cd01fe08994d1951d4aa2/src/CollapsibleItem.js#L18

If I set className that goes through correctly, but the "active" class doesn't get added.

**Comment by alextrastero** [comment]
@sfcgeorge thanks, did you manage to solve this?

**Comment by sfcgeorge** [comment]
Nope. I tried lots of things but I just can't get it to respect the expanded prop. It expands and contracts when clicked so I know it's not completely broken, it just won't start open.

**Comment by alextrastero** [comment]
Ok, i'll have a look asap

**Comment by haddyo** [comment]
Any Updates on this Issue?

**Comment by sfcgeorge** [comment]
Yay thank you, can confirm it works :D

**Comment by alextrastero** [comment]
@sfcgeorge woohoo, please continue reporting bugs ❤️
