### ISSUE TITLE
Errors when rendering Select control with React 16

### ISSUE THREAD

**Issue by adamdriscoll** [react-materialize/react-materialize#406]
I am receiving the following errors when attempting to render a Select control in React 16. Running version ^1.0.16 of react-materialize. 

![image](https://user-images.githubusercontent.com/1256531/31775079-2d3386f0-b4ad-11e7-9bf7-394d80787843.png)

![image](https://user-images.githubusercontent.com/1256531/31775133-5f3bb9f6-b4ad-11e7-8105-e3228a7d7165.png)

**Comment by alextrastero** [comment]
Hey @adamdriscoll, no react16 support yet :)
