### ISSUE TITLE
How can I change the logo text for the Navbar?

### ISSUE THREAD

**Issue by Itagiba** [react-materialize/react-materialize#407]
There does not appear to be a way to change the text Logo `<Navbar brand='logo' right>` for the [Navbar.js](https://github.com/react-materialize/react-materialize/blob/master/src/Navbar.js#L49) unless you modify the actual core JS file, how can I make this an editable prop?

**Comment by alextrastero** [comment]
Hey @Itagiba, `brand` prop is set to node, what do you mean by make the prop editable?

**Comment by davis016** [comment]
Hey @alextrastero, how i can set the brand prop? i want to change the logo.

**Comment by alextrastero** [comment]
Hi @davis016, 
```jsx
<Navbar brand={<span className="brand">my logo</span>} right>
	<NavItem href='get-started.html'>Getting started</NavItem>
	<NavItem href='components.html'>Components</NavItem>
</Navbar>
```
brand prop can be any node
