### ISSUE TITLE
Change `Tabs` lifecycle initialise 

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#408]
Ref: https://github.com/react-materialize/react-materialize/issues/392

Currently the tabs are only initialised on mount, this should happen on receive props if they've changed.

**Comment by Visovsiouk** [comment]
Can I try to resolve this issue?

**Comment by alextrastero** [comment]
Of course @Visovsiouk :)

**Comment by dmitry-yudakov** [comment]
@Visovsiouk Have you managed to make any progress here? I could try to address this issue in #607 for 3.0.0

**Comment by alextrastero** [comment]
👍 @dmitry-yudakov

**Comment by alextrastero** [comment]
Fixed in #634
