### ISSUE TITLE
Unknown prop 'onAutocomplete'

### ISSUE THREAD

**Issue by iamjosan** [react-materialize/react-materialize#409]
I'm getting the following error while trying to use the `Autocomplete` component:

`Warning: Unknown prop onAutocomplete on <div> tag. Remove this prop from the element.`

I am using `React 15.6.1` and `react-materialize 1.0.16`.

Any idea how to resolve this?

Edit
I just checked the source code for the Autocomplete component and it appears that the 'onAutocomplete' prop does not exist even though the docs list it as a prop.

**Comment by alextrastero** [comment]
I wouldn't worry to much about warnings, it's something we need to fix on our end :)
As per that prop: https://github.com/react-materialize/react-materialize/blob/master/src/Autocomplete.js#L99
