### ISSUE TITLE
Translate the Date Picker

### ISSUE THREAD

**Issue by fsolar** [react-materialize/react-materialize#410]
Hi guys, any way to translate the Date Picker? and set the start day to Monday. I tried in many ways but I did not succeed.

Thanks.

**Comment by alextrastero** [comment]
I believe you can pass options to the initialise method, here are the options: http://amsul.ca/pickadate.js/date/#options

**Comment by fsolar** [comment]
I solved it by inserting the translate file (available here: https://github.com/amsul/pickadate.js/tree/3.5.6/lib/translations) in the index.html after jquery and materialize.min.js file.

Thanks.
