### ISSUE TITLE
Reset select input after form submit?

### ISSUE THREAD

**Issue by fsolar** [react-materialize/react-materialize#414]
Hi guys, I'm managing a form with states, I create a handleSubmit function to sincronize with firebase with onSubmit event. The thing is that regular type="text" inputs are easy to set the state to ' ' but i cant resolve how to change the select inputs to the the default option after submit process.

**Comment by alextrastero** [comment]
Hey @fsolar, I don't fully understand this.

You have a Select with a default value like so:
```js
    <Input s={12} type='select' label="Materialize Select" defaultValue='2'>
		<option value='1'>Option 1</option>
		<option value='2'>Option 2</option>
		<option value='3'>Option 3</option>
	</Input>
```
You then `setState` when clicking one of those options, but the defaultValue doesn't change?

**Comment by aqumus** [comment]
@fsolar May be you could try setting `value=""` if you want to reset the input select value.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
