### ISSUE TITLE
Fixed (always visible) SideNav

### ISSUE THREAD

**Issue by MatheusVellone** [react-materialize/react-materialize#416]
[Materialize SideNav docs](http://materializecss.com/side-nav.html#variations) (last example) tells about adding a `fixed` class in addition to `side-nav` to create a always visible SideNav.
Tried to accomplish this behavior with the lib, but couldn't.
I've searched docs, issues, SO questions, but didn't find anything.

Looks like this feature is missing in the lib.

**Comment by alextrastero** [comment]
True, this is not implemented yet, adding a `help-wanted` label incase anyone want's to pick this up:
https://github.com/react-materialize/react-materialize/blob/master/src/SideNav.js
Adding fixed prop should add class to 'side-nav'

**Comment by MatheusVellone** [comment]
I'm not too experienced with React, but I can work on a PR to fix it.

Just need some opinions (because I'm new with React)
If the `fixed` prop exists, then `trigger` shouldn't be required (doesn't need a `trigger` prop because the side-nav is always visible). So I was thinking about [this package](https://github.com/evcohen/react-proptype-conditional-require) to conditionally set the `required` rule for the `trigger` option. What do you think about it ?

**Comment by alextrastero** [comment]
Hey @MatheusVellone, thank you! As for the package, I would rather not add another dependency but favour adding the prop `trigger` as optional instead of required, what do you say?

**Comment by MatheusVellone** [comment]
IMO, I like the idea of `trigger` being required when `fixed` is false.
Because when someone try to use it without `fixed` and without `trigger`, at least a prop validation will be shown.

As this won't add/remove any functionality and add another dependency, if you're ok with it, I'll skip it.
Is skipped, I think in a message in the docs to warn possible incorrect usages is a good

**Comment by Jiab77** [comment]
Hi all, I'll try to help on this as I'm using your in mine. Thanks for your great job, saved me a lot.

**Comment by alextrastero** [comment]
Thanks @Jiab77

**Comment by Jiab77** [comment]
@alextrastero You're welcome. Do you have some guidelines to modify your project ?

**Comment by alextrastero** [comment]
@Jiab77 not really, we have some eslint rules, but that's it :)

**Comment by alextrastero** [comment]
Hey @Jiab77 are you still up for this? :)

**Comment by Jiab77** [comment]
Sorry, yes I'm still on, just having a work that taking me a lot of time. I took time to read the sourcecode, I've cloned your repository and started studying the way to include this features among other missing ones.
I was also busy on my personal project, had to rework the design completely and some personal issues to finish lol anyway, yes I'm still insterested by helping on this project, just having a f... busy life :sweat_smile: 
I'm really sorry for the waiting...

**Comment by Jiab77** [comment]
also thanks for your guidelines :+1:

**Comment by lyssareba** [comment]
Is there a work around for the trigger prop being required? Has anyone been able to get this working?

**Comment by alextrastero** [comment]
Closing this thanks to @lyssareba's PR
