### ISSUE TITLE
change class of CollapsibleItem header

### ISSUE THREAD

**Issue by weasteam** [react-materialize/react-materialize#419]
How can I change the class of CollapsibleItem header?

When I add a class name to CollapsibleItem, it applies the class to the body, not header.

**Comment by alextrastero** [comment]
Hey @weasteam, header prop should contains a node with a className for this to work:
```js
<CollapsibleItem header={<p className="red">RED</p>}>
```

**Comment by alextrastero** [comment]
Let me know if this doesn't work :)

**Comment by weasteam** [comment]
Not working, because the header only highlights the text. It does not highlight the `header` or icon that come with it.

```
<CollapsibleItem header={Activities (${this.props.count})`} icon='notifications' onSelect={this.handleOnSelect}>
```

This is ideal html, it would be great if the classname can be pass to `collapsible-header` like bellow.
```
<div class="collapsible-header red"><i class="material-icons">filter_drama</i>First</div>
```

**Comment by alextrastero** [comment]
How about:
```js
<CollapsibleItem header={<div className='blue-text'>header</div>}>
  Some content
</CollapsibleItem>
```

**Comment by weasteam** [comment]
Nop, that is not working.

It only results in the first picture. I want the result looks like in the second picture.

![screen shot 2017-11-08 at 10 00 06 am](https://user-images.githubusercontent.com/6238854/32567210-7153e5a6-c46f-11e7-9803-dd19c1fda4f6.png)
![screen shot 2017-11-08 at 10 00 44 am](https://user-images.githubusercontent.com/6238854/32567213-73d446fe-c46f-11e7-907a-27a195a418a7.png)

**Comment by gabriel216** [comment]
<CollapsibleItem header={(<div className='blue-text'>header</div>)}>
  Some content
</CollapsibleItem>
You must place the parentheses before the tag. This works

**Comment by KingBrado** [comment]
Hello, did anyone solve this issue? The version of @gabriel216 does not work either for me

**Comment by alextrastero** [comment]
Can you provide a small code sample to test?

**Comment by KingBrado** [comment]
I think the best is to send you an example of what I'd like to achieve.

```
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<title>Collapsible Example</title>
</head>
<body>

	
	<div class="container" style="margin-top: 40px;">
    <ul class="collapsible z-depth-0 guides" style="border: none;">
      <li>
        <div class="collapsible-header red lighten-2">Title</div>
        <div class="collapsible-body red lighten-4">Lorem ipsum dolor sit amet.</div>
      </li>
      <li>
        <div class="collapsible-header red lighten-2">Title</div>
        <div class="collapsible-body red lighten-4"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
      <li>
        <div class="collapsible-header red lighten-2">Title</div>
        <div class="collapsible-body red lighten-4"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
      <li>
        <div class="collapsible-header red lighten-2">Title</div>
        <div class="collapsible-body red lighten-4"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
    </ul>
  </div>
	<script
	src="https://code.jquery.com/jquery-3.3.1.min.js"
	integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	crossorigin="anonymous">
		
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script>
		var items = document.querySelectorAll('.collapsible');
  		M.Collapsible.init(items);
  </script>
</body>
</html>
```
In plain HTML/CSS/Javascript it is possible to pass materialize-css classes to both collapsible-header and collapsible-body. 
After posting here yesterday, I checked the source for react-materialize and, as far as I can see, it is not possible to pass such classes to the collapsible-header. So I proposed a solution in a pull request, not sure if it is ideal. Please let me know if I oversaw something.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
