### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by przbadu** [react-materialize/react-materialize#420]
![screen shot 2017-11-02 at 10 43 39 pm](https://user-images.githubusercontent.com/4189129/32339323-90bcfcd8-c01f-11e7-89e5-9155dc925f94.png)

**Comment by alextrastero** [comment]
Hey @przbadu, does this help: https://github.com/react-materialize/react-materialize#create-react-app

**Comment by przbadu** [comment]
@alextrastero: Yep, but I am trying to build electron app, which will be available for offline use. But the solution was simple. If you are using create-react-app, you can do:

`src/index.js`

```js
import React from 'react';
import ReactDOM from 'react-dom';

import 'bootstrap/dist/css/bootstrap.css';
import './index.css';

import App from './screen/App';
import registerServiceWorker from './registerServiceWorker';

// make bootstrap work with jquery
import jQuery from 'jquery';
window.jQuery = jQuery;
require('bootstrap');

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

Hope this will be helpful to someone looking for similar solution.
