### ISSUE TITLE
Radio group Input not working correctly when one is "checked" by default

### ISSUE THREAD

**Issue by nya1** [react-materialize/react-materialize#422]
Hi,
I'm having issues with 2 radio input, when one is automatically checked (via the "checked" property) the other one requires 2 clicks to be checked

```
// 'A' radio input is checked
<Input name='group1' type='radio' value='A' label='A' checked={true}/>

// 'B' is not checked and it requires 2 clicks to work
<Input name='group1' type='radio' value='B' label='B' />
```

If I add onClick to the 'B' input I can see the event is triggered but visually is not checked

**Comment by alextrastero** [comment]
True! good catch, I'll mark this as `help-wanted` incase anyone wants to pick it up, @nya1 u up for it?

**Comment by nya1** [comment]
Sorry, I cannot help on this

**Comment by alextrastero** [comment]
Hey @nya1, is it because of time or lack of knowledge, I could help you out on the latter :)

**Comment by nya1** [comment]
They are both, sorry

**Comment by alextrastero** [comment]
No worries @nya1 :)
