### ISSUE TITLE
Navbar always collapse in mobile

### ISSUE THREAD

**Issue by dougneves** [react-materialize/react-materialize#423]
Hello everybody,

I'm writing a cordova react app, using react-materialize for the front-end, and I want to use the SideNav component for a better looking mobile menu.
But I can't put the component as a NavBar item because the NavBar always collapse in mobile.
Is there a way to turn off NavBar collapse?

Thanks!

**Comment by yuzhakovvv** [comment]
@dougneves I use this as a temporary solution in my CSS:
`.hide-on-med-and-down {
  display: block !important;
}
#nav-mobile {
  display: none;
}
.button-collapse {
  display: none;
}`

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
