### ISSUE TITLE
How can i use Toast component whitout Button

### ISSUE THREAD

**Issue by juan-carlos-correa** [react-materialize/react-materialize#428]
I want to use Toast Component when i get the http response of a api and show the message.

Some like 

Materialize.toast('I am a toast!', 4000)

Just javascript code. Whithout button. Any idea?

**Comment by alextrastero** [comment]
Hey @juan-carlos-correa, did you manage to solve this? Is there any improvements to the documentation you think is needed to solve this for others? Cheers!

**Comment by dennisja** [comment]
call it as 
`window.Materialize.toast('I am a toast!', 4000)`

**Comment by BrunaChamon** [comment]
@dennisja Solution works for me! Thank you!

**Comment by juan-carlos-correa** [comment]
@alextrastero thanks, it was my mistake for my knowledge of js. The @dennisja solution is perfect ;D

**Comment by ThatBrianDude** [comment]
Wow. The docs could really use a section of "programmatically doing xyz" for almost every component.

**Comment by alextrastero** [comment]
PR's welcome :)

**Comment by dennisja** [comment]
@merrazquin I'm sure you can remove it by doing something like this 
```js
const toast = document.querySelector('#toast-container>.toast.panning');
if(toast){
   toast.remove()
}
```
