### ISSUE TITLE
Set Autocomplete ID from props

### ISSUE THREAD

**Issue by mlileikis** [react-materialize/react-materialize#431]
Hello, I would like to add ID property for input generated by Autocomplete component.
Right now it is hardcoded as autocomplete-input https://github.com/react-materialize/react-materialize/blob/master/src/Autocomplete.js#L103.
This causes wrong behavior when multiple Autocomplete components are created, e.g. clicking one field selects the other.
Could someone look into it? I tried locally fixing node_modules, it is an easy fix, but I would like to deploy to heroku, thanks :)

**Comment by alextrastero** [comment]
Hey @mlileikis, wanna give it a try and submit a PR? Would be glad to review it :) Have a look how it's done here: https://github.com/react-materialize/react-materialize/blob/aa9f65f096d71ebb66498b623bb338fda95fae2c/src/SideNav.js#L8 maybe.

**Comment by mlileikis** [comment]
Okay I'll try to contribute, but I'm not familiar with the process with git, I'm used to mercurial.

I'll have to fork this repo and clone it, make changes, then push and you will merge it, right?

**Comment by alextrastero** [comment]
Cool thanks!

**Comment by mlileikis** [comment]
PR created https://github.com/react-materialize/react-materialize/pull/432

**Comment by mlileikis** [comment]
Nice, we completed this issue then, I'll close it. Before I do, when will these changes be merged to master branch? :)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
