### ISSUE TITLE
parentComponent must be a valid React Component after upgrading to 1.1.0

### ISSUE THREAD

**Issue by EtiennePeeters** [react-materialize/react-materialize#433]
Coming from [Overlay.js](https://github.com/react-materialize/react-materialize/blob/e01c95b43be635447161514c06996dacab7b6204/src/Overlay.js#L39).

**Solution: do not upgrade to 1.1.0 when using React 15.**

It did not immediately occur to me that version 1.1.0 depends on React 16. And because my package.json states `"react-materialize": "^1.0.6"`, it automatically updates to new **minor** versions (which should not contain breaking changes).
This caused my project to break with this error. 

Shouldn't the major version be upped to reflect this breaking change? Or is there a way to not automatically update to versions which require a higher version of React?

**Comment by alextrastero** [comment]
You are absolutely correct. I checked the components but couldn't find anything broken, that's why I opted for a minor. I'll have a look at this ASAP

**Comment by alextrastero** [comment]
Is this a warning or an error? can you submit a code example here?

**Comment by EtiennePeeters** [comment]
Thanks! Fortunately I can upgrade to React 16, so that obviously solves the problem also. But others might not be so fortunate.

It is an error.

The error in overlay.js is triggered by just rendering a `Modal`. I do not use `Overlay` myself.
_MyModal.jsx:_
```
render(){
    return(
        <Modal header={'header'} trigger={<Button>trigger</Button>}>
            content
        </Modal>
    );
}

**Comment by Dyceman** [comment]
Has this issue been solved?

**Comment by alextrastero** [comment]
Hey @Dyceman, not yet, would you like to give it a try? :)

**Comment by Dyceman** [comment]
I upgraded to react16 and I've received a new error message involving the modal.

**Comment by benfluleck** [comment]
Cheers for this i used this fix on my vscode and it worked and removed the errors however when i pushed to production on Heroku i encountered the same errors. Any thoughts?

**Comment by alextrastero** [comment]
Hey @benfluleck, what errors specifically?
