### ISSUE TITLE
Material Icons not working with React components

### ISSUE THREAD

**Issue by Willibaur** [react-materialize/react-materialize#436]
I have a site using Middleman, Webpack and Materialize, we have a React component in one of the pages that works ok apart from the fact that Material Icons are not rendered on Internet Explorer and Firefox; all icons in the rest of the site work fine across all browsers.
Any help would be appreciated.

## Packages used
- materialize-css 0.100.2 => I tried 0.97, 0.98 with the same result
- webpack 3.10.0
- react 16.2.0 => I tried with 15.xx versions and got the same result
- react-materialize 1.1.1

In my `layout` I'm importing the icons according to the Docs

`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="preload" as="style" onload="this.rel='stylesheet'">`

what is being displayed at the moment is the icon name like `alarm_off` or `&#xE857;` as I've tried both input methods

**Comment by alextrastero** [comment]
Hey @Willibaur, this doesn't seem to be an issue with `react-materialize`, as we only provide the javascript :), did you manage to solve this?

**Comment by czarbina** [comment]
This seems to still be an issue, but only for my deployed app. Any resolutions?

**Comment by alextrastero** [comment]
Hey @czarbina, can you check if in the production code, the link still exists in `index.html`. Maybe it's some webpack misconfiguration
