### ISSUE TITLE
Uncaught TypeError: $(...).pickatime is not a function

### ISSUE THREAD

**Issue by guboi72** [react-materialize/react-materialize#438]
Hi, I use react and materialize and I can't make the timepicker work. I looked on your site https://react-materialize.github.io/#/forms and you seem to have the same error in console. Can you confirm that you have the same console error.

I use vanilla materialize by importing it from my index.html.

```<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>```
```<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>```

**Comment by Dyceman** [comment]
That happens when the dom element you are trying to access is out of scope. I currently having the same issue trying to close a modal.

**Comment by daxaxelrod** [comment]
Dom element being the time picker?
Im using
<Row>
          <Input name="on" type="time" onChange={(e, value) => {

          }} />
</Row>

**Comment by alextrastero** [comment]
Hi, pickatime doesn't work with certain version of materialize-css

**Comment by alextrastero** [comment]
required version is "materialize-css": "^0.100.2",

**Comment by daxaxelrod** [comment]
@alextrastero Thanks!

**Comment by jcxswc** [comment]
Same issue. Using "materialize-css": "^1.0.0-rc.2".

**Comment by alextrastero** [comment]
Please downgrade to materialize-css@0.100.2

**Comment by jcxswc** [comment]
No such luck. Remains to receive a `$(...).pickatime is not a function`.

_package.json_
`"materialize-css": "^0.100.2"`
...
`"react-materialize": "^2.4.2"`

_app head_
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>`

**Comment by alextrastero** [comment]
Are you using `create-react-app`?
Check out this repo example: https://github.com/alextrastero/react-materialize-cra-example
