### ISSUE TITLE
"Uncaught Error: parentComponent must be a valid React Component" when use Modal

### ISSUE THREAD

**Issue by jimmdd** [react-materialize/react-materialize#439]
I got the following erros when I tried to use Modal. It was running fine and suddenly not working. I checked my project set ups and everything else and I can't figure out why until I comment out the modal. It will give me this same error every time I try to use Modal even for the sample code from react-materialize example. 

I am running on `"react-materialize": "^1.0.14" `when the issue happens, I upgrade to 1.1.1 and the error is still there. Here is the error msg from the browser: 

```
propTypes.js:181 Uncaught Error: parentComponent must be a valid React Component
    at invariant (propTypes.js:181)
    at Object.unstable_renderSubtreeIntoContainer (bundle.js:91974)
    at OverlayTrigger._renderOverlay (bundle.js:33419)
    at OverlayTrigger.componentDidMount (bundle.js:33403)
    at bundle.js:68185
    at measureLifeCyclePerf (bundle.js:67996)
    at bundle.js:68184
    at CallbackQueue.notifyAll (bundle.js:30962)
    at ReactReconcileTransaction.close (bundle.js:70110)
    at ReactReconcileTransaction.closeAll (bundle.js:15576)
```

**Comment by alextrastero** [comment]
Hey @jimmdd, what was the issue? incase someone else runs into this problem :)

**Comment by jimmdd** [comment]
It's the same issue where here discussed in here: [](https://github.com/react-materialize/react-materialize/issues/433), I saw it after I post this. The solution is to using `“react”: “^16.2.0",“react-dom”: “^16.2.0",“react-materialize”: “^1.0.6",`as dependencies.

**Comment by alextrastero** [comment]
Thanks @jimmdd

**Comment by stephenfriedman** [comment]
@jimmdd Your link shows a reference to issue 433 but instead just references to this page. Here is the proper link for anyone bamboozled by this: [https://github.com/react-materialize/react-materialize/issues/433](https://github.com/react-materialize/react-materialize/issues/433)
