### ISSUE TITLE
Unexpected warning when using select component

### ISSUE THREAD

**Issue by scarletsky** [react-materialize/react-materialize#44]
Here is my code:

```jsx
<Row>
  <Input
    label="Font Size"
    s={12}
    type="select"
    defaultValue={String(this.state.fontSize)}
    onChange={this.handleSelectChange.bind(this, 'fontSize')}>
    {Array(15).fill().map((v, i) => {
      return (
        <option key={i} value={16+i}>
          {`${16+i}px`}
        </option>
      );
    })}
  </Input>
</Row>
```

But I get the following warning in console:

```
Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Input`.
```

I have no idea why this happen, but the `onClick` works as expect.

**Comment by isaiah** [comment]
My guess is that the selector re-render the options as input element and the value is set by 'value' instead of `defaultValue`.

**Comment by scarletsky** [comment]
@isaiah 
So in the `Select` component, we are going to use `value` instead of `defaultValue` ?

**Comment by isaiah** [comment]
@scarletsky I was guessing, ignore my previous comment please.

By checking the code, I found that for `select`, the `onChange` event is not added for react, instead it's hooked by jquery.

https://github.com/react-materialize/react-materialize/blob/master/src/Input.js#L37

**Comment by alextrastero** [comment]
Closing for now, please reopen if needed.
