### ISSUE TITLE
server for docs started with errors Module not found: Error: Can't resolve 'materialize-css/css/ghpages-materialize.css

### ISSUE THREAD

**Issue by Pechalka** [react-materialize/react-materialize#441]
It's because no materialize-css package.json and last version have other folder structure. I will fix it.

**Comment by Pechalka** [comment]
https://github.com/react-materialize/react-materialize/pull/442

**Comment by alextrastero** [comment]
Smashing! We are rewritting the docs in Gatsby so hopefully many other issues will get solved then :)

**Comment by alextrastero** [comment]
Thanks @Pechalka, please continue!! 💯  👍

**Comment by Dhrvv** [comment]
Module not found: Error: Can't resolve 'materialize-css/dis/css/materialize.min.css' in 'C:\Users\Dhruv Verma\supply-chain-management\src'
