### ISSUE TITLE
Buttons Not working on mobile

### ISSUE THREAD

**Issue by josephpung** [react-materialize/react-materialize#449]
As stated in title, buttons are not working when I run my website on mobile

**Comment by alextrastero** [comment]
Hey @josephpung, not working meaning they don't click? or they don't animate? This is a first :)

**Comment by josephpung** [comment]
@alextrastero i cant click on the buttons when i view it on mobile, works prefect on normal web tho.

this is the page im using, the button is on the main component after the location loads so if you wanna test it out you need to use chrome and allow location services 
[Page Link](https://voiceweather.herokuapp.com/)

**Comment by alextrastero** [comment]
I'm getting other errors like: 
`Oopsy daisy, this shouldn't happen ! not-allowed` and
`Verify the microphone and check for the table of errors in sdkcarlos.github.io/sites/artyom.html to solve your problem. If you want to give your user a message when an error appears add an artyom listener` when I click the button on mobile

**Comment by alextrastero** [comment]
I'm afraid we don't remove click listeners to buttons manually when on mobile view, it must be something else in your code

**Comment by josephpung** [comment]
i think i've figured the problem out, thank you!
