### ISSUE TITLE
SideNavItem react-router Integration

### ISSUE THREAD

**Issue by gn-ley** [react-materialize/react-materialize#450]
Similar as the solution for NavLink #188, there needs to be a solution for SideNavs as well.

An additional prop "to" seems the best way to go:
```<SideNavItem to="/route">```

**Comment by alextrastero** [comment]
Closing in favour of
```jsx
<SideNav>
  <li><NavLink to="/some/path">Name to show</NavLink></li>
</SideNav>
```
