### ISSUE TITLE
Custom input error messages breaks lines with some white spaces

### ISSUE THREAD

**Issue by pmartiner** [react-materialize/react-materialize#452]
Adding a custom error message into an Input field, without replacing each space for a `&nbsp;` breaks the lines within the error label.
Any ideas where the errors might be? 

Working code :
`<Input l={12} s={12} error='Invalid&nbsp;user&nbsp;or&nbsp;password' type='password' id='password' label='Password' onKeyPress={this.handleKeyPress.bind(this)} onChange={(e) => {this.handleInputChange(e, 'pw')}}/> `

![captura de pantalla de 2018-01-08 11-29-36](https://user-images.githubusercontent.com/25936810/34683412-96ea37a2-f467-11e7-8abc-0813152da66f.png)

Error label with line breaking: 
`<Input l={12} s={12} error='Invalid user or password' type='password' id='password' label='Password' onKeyPress={this.handleKeyPress.bind(this)} onChange={(e) => {this.handleInputChange(e, 'pw')}}/> `

![captura de pantalla de 2018-01-08 11-28-42](https://user-images.githubusercontent.com/25936810/34683411-96ca1fa8-f467-11e7-8c1c-2714bede4ae8.png)

**Comment by alextrastero** [comment]
True! seems like the input is missing `.validate` class which sets the width.

**Comment by pmartiner** [comment]
I don't think setting the `validate` prop to default would be the best solution, since it's an optional class in the "non-react"-materialize. Maybe making the prop `error` the new width setter would be nice. This would make sense as the problem is related to the custom error message; defaulting the validation in the Input component would affect users who aren't customizing their errors, yet I don't really know if fixing it that way is even possible.

**Comment by alextrastero** [comment]
I would rather not mess around with `css` changes, I think we can mark this issue as resolved stating that `validate` prop is what was missing, WDYT?

**Comment by pmartiner** [comment]
I agree. 
Yeah, the the issue is resolved. Thank you very much!
