### ISSUE TITLE
Issue in input type select

### ISSUE THREAD

**Issue by tapandave** [react-materialize/react-materialize#453]
Please help with the issue coming in my react redux app when i want to populate data using select input,

just copied and paste code from website
`<Input s={12} type='select' label="Select">`
        `<option value="null">Select</option>`
       `<option value="Select 1">Select 1</option>`
        `<option value="Select 2">Select 2</option>`
        `<option value="Select 3">Select 3</option>`
`</Input>`

and throwing an error 
TypeError: this.updater.enqueueCallback is not a function

using :  
"react": "^16.1.1",
 "react-dom": "^16.1.1",
"react-materialize": "^1.0.16",

please help...

**Comment by alextrastero** [comment]
You might need to reinitialise the select `$('select').material_select();` when the new data arrives

**Comment by alextrastero** [comment]
Also please make sure that you do have react16 as mentioned in this ticket: https://github.com/facebook/react/issues/10320

**Comment by tapandave** [comment]
reinitialise the select,but how to use '$' in react component lifecycle,can you show me an example

**Comment by alextrastero** [comment]
If you have a look at the implementation of `<Input />` [here](https://github.com/react-materialize/react-materialize/blob/master/src/Input.js#L24), you can see how we use `$`. Now, if you are using `react-create-app`, you might have an issue. For webpack check [this](https://webpack.js.org/plugins/provide-plugin/#usage-jquery) out

**Comment by abhinavRai23** [comment]
@tapandave initialize in componentDidMount.
`componentDidMount() {
        $('select').material_select();
}`

**Comment by ShubhamKushwah** [comment]
`componentDidMount() { $('select').material_select(); }` didn't work for me.

**Comment by ziyang0621** [comment]
Im using `react-create-app`, and `componentDidMount() { $('select').material_select(); }` doesnt work for me, anyone has idea? 

I use `import $ from 'jquery';` in my component.

**Comment by alextrastero** [comment]
Try having a look here @ziyang0621,
`https://github.com/alextrastero/react-materialize-cra-example`
