### ISSUE TITLE
Using materialize SASS components

### ISSUE THREAD

**Issue by mpetricek** [react-materialize/react-materialize#454]
Hi,

is there an elegant way how to use style components from materialize which are in "node_modules/etc." in my own styles in app. If I simply import them they will be rendered twice in final css.

Thank you in advance!

**Comment by alextrastero** [comment]
I guess you are using the compiled CSS from the CDN at the moment? If you choose to go with SASS you will need to remove all imports to the compiled CSS and handle the sass compilation on your own via Webpack or similar.

**Comment by mpetricek** [comment]
No I'm  not using compiled CSS. The Materialize SASS are compiled via Webpack.

My question is how to use for example "@extend .white-text" in my own stylesheets without duplicating SASS code. For now I imported three Materialize scss components via ~materialize-css/etc. but those components would render twice on the end.

**Comment by alextrastero** [comment]
I would need a better example if possible,  `@extend .white-text` will always result in duplication or maybe I still don't understand the issue :)

**Comment by mpetricek** [comment]
If I wan't to use @extend and use classes from materialize I need to import components like "_color.scss, _variables.scss" into my stylesheet. That leads to duplicate rendering of those components.

**Comment by alextrastero** [comment]
I see, I don't know how you can avoid that. If you want to extend a var declared in variables.scss, you will need to import the file, and if THAT file requires other files, you need to import them too.

This however is not an issue with react-materialize since we're just importing the compiled css from them.

**Comment by guillermo-varela** [comment]
Hi,

This helped me to change the colors without ending up with a duplicated CSS:

1. Add `node-sass` as a development dependency.

2. Create a file `index.scss` with the colors I needed and importing SASS files from materializecss:
```
@import 'materialize-css/sass/components/_color-variables';
$primary-color: color('blue', 'lighten-2') !default;
$secondary-color: color('yellow', 'base') !default;
@import 'materialize-css/sass/materialize';
````

3. In `index.js` import the JS from materialize, but NOT the CSS. Instead import my file `index.scss` (which contains the SASS files from materialize already).
```
import './index.scss';
import 'materialize-css/dist/js/materialize.min.js';
```

4. Run the app. Both development and production builds worked for me.

I hope this helps others :)
