### ISSUE TITLE
Closing a modal on an actions modal proptype

### ISSUE THREAD

**Issue by yash592** [react-materialize/react-materialize#458]
Is there any way to close a modal on clicking a submit button with an actions modal prototype?

Example code shown below:

`<Modal id = "Popout"
    	header= 'Tell your followers about your project.'
    	trigger={<Button id="PostBtn">Post</Button>}
      actions={
        <Button  name="btn" id="submitBtn" className="btn btn-default" onClick={this.handleFormSubmit} data-confirm="Are you sure you want to submit?" >Submit</Button>        
      }>`

**Comment by alextrastero** [comment]
You could add a `ref` and close inside `handleFormSubmit`, I think that would work

**Comment by alextrastero** [comment]
```
<Modal
	...
	ref='myModal'
	...
>
...
handleFormSubmit() {
	$(this.refs.myModal).close()
	...
}
```

**Comment by yash592** [comment]
Thank you @alextrastero 

I added a `modal = "close` attribute to the button and was able to close the modal and submit as well.

**Comment by alextrastero** [comment]
Ok, closing then :)
