### ISSUE TITLE
Toggling checkbok with an onClick event using boolean

### ISSUE THREAD

**Issue by clemudensi** [react-materialize/react-materialize#462]
Hi, I've been having trouble toggling the materialize checkbox with a separate button I created, I've been able to verify that my state works properly by passing in boolean values into the checked object parameter of checkbox input. I don't know if this is a bug or an error on my part, therefore I would appreciate any assistance to resolve this issue. Although the checkbox toggle works properly by itself when bound to other functions.

**Comment by alextrastero** [comment]
Yeah, it's because it's attached to jQuery events, have a look in the materializecss documentation, something related to reinitialising the checkbox

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
