### ISSUE TITLE
Button onClick not fired when 'fab' paramater used.

### ISSUE THREAD

**Issue by jacquesdev** [react-materialize/react-materialize#463]
I have a Button that looks like the one below.

```
     <Button
        floating large
        fab='vertical'
        waves='light'
        icon='add'
        onClick={function}
      />
```

It seems that onClick gets ignored when fab='vertical' (or 'horizontal') for that matter. When I removed that property entirely, the onClick fires as expected.

**Comment by jacquesdev** [comment]
It turns out this is by design (I did not realise), but it is not specified in the docs, so will add a PR to get that updated.

**Comment by alextrastero** [comment]
Thanks @jacquesdev
