### ISSUE TITLE
Support `onClick` for <NavItem/>

### ISSUE THREAD

**Issue by lloydwatkin** [react-materialize/react-materialize#465]
I'd like to be able to pass on `onClick` prop to `<NavItem/>` rather than a `href`.

**Comment by alextrastero** [comment]
All props are passed here https://github.com/react-materialize/react-materialize/blob/master/src/NavItem.js#L12, doesn't this work?

**Comment by lloydwatkin** [comment]
Unfortunately not, if I write:

```jsx
      <Navbar>
        <NavItemonClick={this.props.refreshAndBrowse}>
          <Icon left>view_list</Icon>
          <span>'BROWSE}</span>
        </NavItem>
      </Navbar>
```

This generates:

```html
<li class="no-padding">
  <a href=""><i class="material-icons left">view_list</i><span>Browse</span></a>
</li>
```

So when I click on the `<li/>` (to which the `onClick` prop is attached) the `<a/>` tag is getting activated (since it has a href) and hijacks the action.

**Comment by lloydwatkin** [comment]
...if `href` attribute is not added to the `<a/>` tag then the `onClick` fires as expected and everything is good :+1:

**Comment by lloydwatkin** [comment]
My short term solution is to use an `<li/>` in `<Navbar/>` rather than `<NavItem/>` but longer term (or before I get a chance to make a PR myself) it would be good to support the clicks only :)

**Comment by alextrastero** [comment]
Ah I see, ok so ideally if prop `onClick` exists we should remove the `href` from `a`

**Comment by lloydwatkin** [comment]
I'd say if `href` doesn't exist don't include it? That way its up to the
user?

**Comment by marvinkome** [comment]
I think the way you should do this is to add `e.preventDefault()` to the onClick handler this way when the `a` is clicked it doesn't do what the browser default does that is route to the `href` location.

**Comment by lloydwatkin** [comment]
That doesn't work. The link tag is a child element.

**Comment by alextrastero** [comment]
@lloydwatkin @marvinkome feel free to give it a go :)

**Comment by onluiz** [comment]
@alextrastero @lloydwatkin, this issue could be closed? :)

**Comment by alextrastero** [comment]
Yes! :)
