### ISSUE TITLE
Implementing Search Bar

### ISSUE THREAD

**Issue by Koolstr** [react-materialize/react-materialize#467]
Can we get the Materialize search bar included? I noticed it wasn't an option in [our NavBar documentation](https://react-materialize.github.io/#/navbar). And yet It's listed as possible with the original Materialize in [their NavBar documentation](http://materializecss.com/navbar.html), so what would it take to get it implemented here as well?

I tried implementing it raw from Materialize's docs, but it doesn't render correctly at all. It's possible I just did it wrong though.

**Comment by AlexandrDobrovolskiy** [comment]
same issue

**Comment by alextrastero** [comment]
We have a [searchForm](https://github.com/react-materialize/react-materialize/blob/188ee6c4521a1afc16548108cde2637d9bdc8ce6/src/SearchForm.js)

**Comment by Koolstr** [comment]
I would presume so, but then why is this not listed anywhere in the documentation?

**Comment by alextrastero** [comment]
Actually the implementation is quite basic, what are the requirements for the search bar? Would a normal input with a search icon work?

**Comment by Koolstr** [comment]
If that matches the one from the original Materialize docs, then I don't see why not.

Just because the implementation is basic, doesn't mean it shouldn't be documented. I had no way of knowing that this component existed (outside of digging through the source files).

**Comment by alextrastero** [comment]
Sorry, I meant that I don't recommend using the mentioned component as the implementation is basic/not complete, no callbacks are passed to the form, so not much use. That's probably why no one added it to the documentation.

Feel free to submit a PR with any changes you would apply to this component :)

**Comment by Koolstr** [comment]
Oh, ok. I'll be trying it out at some point. What aspects of the search bar do and don't work? Can you clearly list them for me?

**Comment by alextrastero** [comment]
Hey @Koolstr, I think some acceptance criteria could be:

- `onSubmit` prop for form
- `onChange` prop for input
- `icon` prop to show or not the search icon?

Not sure if any more are needed

**Comment by alextrastero** [comment]
Ping @Koolstr :)

**Comment by Koolstr** [comment]
Sorry, been busy prepping for technical whiteboard job interviews. I'll hopefully get around to this shortly.

**Comment by alextrastero** [comment]
Closing for now, will reopen if required
