### ISSUE TITLE
DatePicker reopens when changing tabs.

### ISSUE THREAD

**Issue by shrestha-bikash** [react-materialize/react-materialize#468]
Steps to reproduce this issue:

Click on the Date Picker input
Click on a date to choose one and click close or just click close
Click another tab
Return back to the previous tab
The Date Picker Modal opens without the user clicking on it

**Comment by alextrastero** [comment]
Hey @shrestha-bikash, the code would look like this?
```jsx
<Tabs>
  <Tab>content</Tab>
  <Tab>
    <Input type='date' />
  </Tab>
  <Tab>content</Tab>
</Tabs>
```

**Comment by Lucas-Braz-Cunha** [comment]
@alextrastero actually this happens if you just change tabs on the navigator (happened to me on Chromium).
```html
<Row>
  <Input type='date' />
</Row>
```

**Comment by shrestha-bikash** [comment]
@alextrastero I am not talking about <Tabs> I am talking about browser tab like @Lucas-Braz-Cunha said.

**Comment by alextrastero** [comment]
Ah! I see, would this be an issue with react-materialize or materialize-css then? We need to debug this, anyone want to give it a try?

**Comment by shrestha-bikash** [comment]
I found that react-materialize has used pickadate [library](https://github.com/amsul/pickadate.js) and this issue is related to this library. [Here](https://github.com/amsul/pickadate.js/issues/160) is the issue that has the solution which can be used to solve this issue.

**Comment by shrestha-bikash** [comment]
In Input.js file from src folder
here this code 
```
if (this.isDatePicker) {
    $(this.dateInput).pickadate(this.props.options);
    $(this.dateInput).on('change', this._onChange);
}
```
can be changed as
```
if (this.isDatePicker) {
    $(this.dateInput).pickadate({...this.props.options, onClose: function() {
       if(this.props.options.onClose) {
          this.props.options.onClose();
        }
        $(document.activeElement).blur()
      }
    });
    $(this.dateInput).on('change', this._onChange);
}
```

This may work I have done something like this to make it work in materialize-css.

**Comment by alextrastero** [comment]
`react-materialize` is using whatever `materialize-css@0.98.2` was using.

It seems now they might have their [own implementation](https://github.com/Dogfalo/materialize/blob/7420a390d179900a399cd55cdd7d4f0fb8fce81a/js/datepicker.js)

**Comment by alextrastero** [comment]
Great @shrestha-bikash! Wanna submit a PR?

**Comment by shrestha-bikash** [comment]
Okay

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
