### ISSUE TITLE
Custom Modal Fix Header And Footer

### ISSUE THREAD

**Issue by daiduongbian44** [react-materialize/react-materialize#47]
To adapt to some pages, now i need the Modal Component with fixed header and footer but the modal has adaptive height. Besides that, the Modal also has more flexible, i mean we can open and close modal programatically. Hope team helps me. Thanks.
Best and regard:
ManhNQ

**Comment by alextrastero** [comment]
Hi @daiduongbian44! I'm not sure if I understand the first part of your comment `Besides that, the Modal also has more flexible`. All you want is the modal to be triggered from another component? ie opened closed

**Comment by alextrastero** [comment]
Closing as no more info, please reopen if needed.
