### ISSUE TITLE
view_headline showing up on Nav when window is resized

### ISSUE THREAD

**Issue by urahonky** [react-materialize/react-materialize#48]
Hello!

First of all: Thank you very much for making this project. It's working really well so far, but I ran into a small issue that I could help fix or suggest a fix for you.

I'm rendering a very simple Nav that just has the name of the application (so far) on it, and when I resize the window the words "view_headline" show up on the Nav bar and I can't find a way to remove them. It looks like it's related to the nav-mobile property. Would it be possible for us to send in whether or not the nav-mobile displays? Below is a snippet of the code and a screencap of what it looks like.

![image](https://cloud.githubusercontent.com/assets/6754000/13584685/b5bf14a2-e485-11e5-97bf-b00d9176b1b8.png)

```
render: function(){
        return (
            <Navbar className="nav" brand="PROJECT TV"/>
        );
    }
```

**Comment by isaiah** [comment]
Hi @urahonky Thanks for reporting this, try include the material web fonts:

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

Let me know if it works :)

**Comment by urahonky** [comment]
That worked! Would it be possible for us to have the option to hide it? Right now I don't have anything on the Navbar other than the project title (throwing together a prototype for my company) and would rather not have it show up if possible.

No rush, though, because the hamburger icon is much better than view_headline :) Thanks again!

**Comment by isaiah** [comment]
Glad to help.
