### ISSUE TITLE
Input select dropdown issue

### ISSUE THREAD

**Issue by timmeh-m** [react-materialize/react-materialize#483]
I'm having some trouble with the select input. I have copy and pasted the select input example into my project and whilst it almost works, when I select an option in the dropdown the dropdown goes away, but the options are still selectable (as if the dropdown didn't actually go away but instead had it's alpha changed to 0). Has anyone experienced this issue?

**Comment by alextrastero** [comment]
Is this still happening @timmeh-m ?

**Comment by timmeh-m** [comment]
Unfortunately so, 2.0.7

**Comment by alextrastero** [comment]
Can't reproduce @timmeh-m, could you specify exactly steps to reproduce?

**Comment by timmeh-m** [comment]
It's really odd, I've used just the example code (copy and pasted) from the docs and I've captured a video so you can see what happens. https://youtu.be/T9zQhotTkfw

**Comment by timmeh-m** [comment]
Well then, I've discovered that the example code doesn't have this problem in all of my classes, just one in particular. Further found my predecessor had css code for the div different to the other classes. Removal of the pointless css code has resolved this issue. Thanks for your time, annoyed it was something like this but hey, it works now.

**Comment by alextrastero** [comment]
This is strange! thanks for following up on it :)
