### ISSUE TITLE
Version 2.0.6 not working

### ISSUE THREAD

**Issue by cernadasjuan** [react-materialize/react-materialize#484]
### Description

When I do npm i react-materialize, the version 2.0.6 doent't have the source code in lib folder, so when i run npm start the app crashes.

**Comment by alextrastero** [comment]
Absolutely true, this is due to https://github.com/react-materialize/react-materialize/commit/e181e73e9406416a5efb12d805f8f12f1d644720#diff-354f30a63fb0907d4ad57269548329e3

I messed up the travis config. 2.0.7 should fix this :)
