### ISSUE TITLE
Materialize css version

### ISSUE THREAD

**Issue by cernadasjuan** [react-materialize/react-materialize#489]
Hi, I saw in the installation instructions that the materialize css version is 0.98.0, but there are new versions of the library. Is mandatory to use the 0.98.0 version, or I can change it?

Thanks!

**Comment by alextrastero** [comment]
Hey @cernadasjuan, the issue is that they made breaking changes in the js part. So by updating it will break. If you want, update the version and see if anything breaks, please fill an issue then :)
