### ISSUE TITLE
Controlled modal component

### ISSUE THREAD

**Issue by BryceMehring** [react-materialize/react-materialize#493]
### Description

Allow the modal component to be controlled via props without the need for a button. It would function similar to how material-ui opens/closes the modal via the `open` prop. http://www.material-ui.com/#/components/dialog

**Comment by alextrastero** [comment]
@BryceMehring `2.1.0` ;)

**Comment by severeon** [comment]
Shouldn't this logic be in the render function aswell?  Currently it will only open the modal via the prop if it was instantiated with the property set.
