### ISSUE TITLE
Tab active not working

### ISSUE THREAD

**Issue by timmeh-m** [react-materialize/react-materialize#498]
I have a header with links that direct to different pages using react-router. One of the pages has tabs on it, and when the page loads from being selected in the header, the component for the first tab (which I've set as active) is loaded, but the tab itself is not active. The problem here is that if I click on another tab (tab 2 for example), tab 2 becomes active, shows the content for that BUT also continues to show the content for tab 1. If I reload the page, the tabs work fine, but by navigating to the page via the header, I have this issue consistently.

<img width="928" alt="screen shot 2018-03-14 at 10 01 21 am" src="https://user-images.githubusercontent.com/28582683/37379504-b35cd748-276e-11e8-9617-3b97a4861e48.png">
<img width="927" alt="screen shot 2018-03-14 at 10 01 30 am" src="https://user-images.githubusercontent.com/28582683/37379507-b3b1d284-276e-11e8-86e0-94d3769b82a6.png">

**Comment by alextrastero** [comment]
@timmeh-m have a look at the linked PR

**Comment by timmeh-m** [comment]
Hmmm, well I'm not entirely sure how to use that branch in my project (I put the link to the branch in my package.json but it doesn't download the src file, just some readme's and other docs), so I ended up just manually putting your code in my local copy of react-materialize 2.1.0. It didn't seem to fix the problem, although that could just be down to me.

Here's how I'm setting up the tabs, where I want only the first tab active by default.

`<Tabs>
  {this.autoNotificationRules.map((value, index) => {
    return (
      <Tab key={index} title={``Rule ${index+1}``} active={index === 0}>
        <NotificationRule rule={value} index={index}/>
      </Tab>
     )
  })}
</Tabs>`

In my package.json, I tried

`"react-materialize": "https://github.com/react-materialize/react-materialize.git#tabs-reinit"`

but got nothing but doc files.

**Comment by alextrastero** [comment]
@timmeh-m try `2.1.2` :)

**Comment by timmeh-m** [comment]
In Safari no change, but in Chrome it looks to be much better, not 100% but works most of the time. That's fine, we'll just recommend the use of Chrome. Thanks for your help!

**Comment by alextrastero** [comment]
In this case the browser shouldn't make any difference really, weird

**Comment by osztenkurden** [comment]
I still have this issue, on version 2.4.2
