### ISSUE TITLE
Add `Sidenav` fixed prop

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#499]
### Sidenav fixed prop

Currently, most of our issues our related to sidenav, since this is such an important component, we need to update the docs, have more examples, and add more props such as `fixed`.

**Comment by alextrastero** [comment]
What's the diff between Sidenav and Navbar, can they be the same element? what can they share?

**Comment by onluiz** [comment]
> What's the diff between Sidenav and Navbar, can they be the same element?

I don't think so. Although I don't see much of cases of Sidenav been used alone, making they distinct components could make it easier to maintain and customize, no?

About more examples and props, we could use the same as in materializecss to start. http://materializecss.com/sidenav.html

What you think @alextrastero ?

**Comment by alextrastero** [comment]
I see, have a look at what lyssareba is doing in #520 maybe this issue will be fixed by that PR?

**Comment by alextrastero** [comment]
But yes, adding more examples is always good :)

**Comment by onluiz** [comment]
It sure will be fixed by that PR (#520) =)
