### ISSUE TITLE
Webpack ES6

### ISSUE THREAD

**Issue by joshhornby** [react-materialize/react-materialize#5]
Has anyone managed to get this working in an ES6 environment? 

For example 

```
import { Button } from 'react-materialize-real';
```

Produces the following error 

```
ERROR in ../~/react-materialize-real/src/Button.js
Module parse failed: /Users/foo/node_modules/react-materialize-real/src/Button.js Line 17: Unexpected token (
You may need an appropriate loader to handle this file type.
|     disabled: React.PropTypes.bool
|   },
|   render() {
|     var C = this.props.node || 'button';
|     var classes = {
 @ ../~/react-materialize-real/src/index.js 2:10-29
```

**Comment by kriscarle** [comment]
I hit this issue and ended up just switching it back to ES5 render: function(){} syntax. For me it seems to have something to do with babel not liking the mix of React.createClass and the ES6 class syntax. All of the react examples I can find either do it one way or the other: http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

**Comment by isaiah** [comment]
Someone pushed the `react-materialize-real` to npm for me, but I have no control over it, instead I've created the `react-materializecss` package on npm, @joshhornby   can you try if that one is working now?

@kriscarle ideally the npm package should be ignored by babel, as it should have already been transpiled to ES5.

**Comment by rasmushaglund** [comment]
I have the same problem. Would it be a good idea to convert the project to react friendly ES6?

**Comment by isaiah** [comment]
Please reopen if still experience the issue.
