### ISSUE TITLE
Footer contains hard-coded 'Connect' h5 tag

### ISSUE THREAD

**Issue by shanemcgraw** [react-materialize/react-materialize#50]
When a Footer component is loaded without any styling, it will always display 'Connect', without any way of deleting other than modifying the entire module directly. It appears to come from line 75 in the Footer.js file: 
`_react2.default.createElement(
                'h5',
                { className: 'white-text' },
                'Connect'
              ),
              this.props.links`

It looks like this is coming from the website footer directly over at [https://react-materialize.github.io/](url)

Furthermore, the footer always displays a two-pane style by default (i.e. one footer of slightly lighter color above another, slightly darker, footer. Is this by design? I was thinking it could be due to the h5 tag included as well...

**Comment by alextrastero** [comment]
Hey @shanemcgraw, correct, this was hard-coded, the two-pane style is inherited from materializecss therefore it is by design.

**Comment by shanemcgraw** [comment]
I gotcha. Many thanks!
