### ISSUE TITLE
Disable past dates in DatePicker

### ISSUE THREAD

**Issue by PREMPRAKASHSINGH** [react-materialize/react-materialize#507]
### Description

I am not able to disable past dates in case where i don't want to allow user's to select past dates.

### Steps to Reproduce
Following is the code sample:
```
<Row>
  <Input name='on'  type='date' onChange={function(e, value) {}} />
</Row>
```

**Expected behavior:** [What you expect to happen]
There should be some parameters like minDate that will disable the past dates from minDate.

**Actual behavior:** [What actually happens]
At the moment it does not disables the past dates and user's can select past dates.
### Versions

**react-materialize:** 1.0.8
**materialize-css:** 0.100.1
**react:** 0.14.7

**Comment by alextrastero** [comment]
Hi, first thing I recommend is to update `react-materialize` and all it's dependencies :)

**Comment by alextrastero** [comment]
react-materialize: 1.0.8 (current 2.1.2)
materialize-css: 0.100.1 (0.100.2)
react: 0.14.7 (16.2.0) also update react-dom

**Comment by alextrastero** [comment]
materialize-css in this version is using pickadate. You can pass options to the input for the datepicker if i'm not mistaken:
http://amsul.ca/pickadate.js/date/#limits

Let me know if it doesn't work with a code sample :)

**Comment by PREMPRAKASHSINGH** [comment]
Hey @alextrastero  thanks it worked 👍
