### ISSUE TITLE
I can't see my inputs into a Card.

### ISSUE THREAD

**Issue by thecassion** [react-materialize/react-materialize#508]
### Input can't be a content into a card

I am trying to use a card as a form. When I put my input in a `children` in my card , It does not work and I can't be able to see my inputs

my code 
List of inputs
` const inputlist = [
    {label:"First name", type:"text"},
    {label:"First name", type:"text"},
    {label:"First name", type:"text"},
    {label:"First name", type:"text"},
    {label:"First name", type:"text"}];
    const Inputs = inputlist.map((myinput)=>{
      return <Input label={myinput.label} type={myinput.type} s={12}/>
    });`
The card
` <div className="container">
          <br /><br /><br />
          <Row>
            <div className="col s12 m6 offset-m3">
            <Card header={<div className="card-action teal ligthen-1 white-text">
                  <h6> Welcome to my website</h6>
                </div>} title="Signup" children={Inputs} actions ={<button> Signup</button>}/>
              </div>
          </Row>
        </div>`
### Versions

**react-materialize:** 2.1.0
**materialize-css:** 0.98.0
**react:** 3.7.2

**Comment by alextrastero** [comment]
Absolutely right! This is a bug. seems like actions panel is taking overlapping all the section /weird

**Comment by LukasUnbesiegt** [comment]
yes it is  overlapping .

**Comment by onluiz** [comment]
Hi guys.

After an analise, I was capable to identify that the problem occurs when the css class .col, in Input component, is set to be true.

In other words, if input has css class .col the above problem happens :P

I don't know how would be the impact of removing this class from Input component (I mean, it is there for some reason), so I would like to ask if you guys could give me some tip to solve the problem, please.

**Comment by alextrastero** [comment]
Good catch @onluiz!

@thecassion since all `Inputs` have grid classes make sure to wrap them all in a `<Row>`:

```jsx
<Row>
{inputList.map((props) => <Input ...props />)}
</Row>
```

**Comment by alextrastero** [comment]
Closing since the issue of Inputs having grid classes is discussed [here](https://github.com/react-materialize/react-materialize/issues/160)
