### ISSUE TITLE
Navbar className only applies class to NavItem but no to Navbar

### ISSUE THREAD

**Issue by marcogonzalo** [react-materialize/react-materialize#51]
`<Navbar brand='Logo' className='light-blue lighten-2' right></Navbar>`

Generates a red Navbar with NavItem in 'light-blue lighten-2', but Navbar doesn't change its background color.

**Comment by alextrastero** [comment]
This was fixed with #42. Have got the latest?

**Comment by marcogonzalo** [comment]
Which should be the latest version number? I installed it from npm.

**Comment by alextrastero** [comment]
@marcogonzalo please try now, npm package updated :)

**Comment by alextrastero** [comment]
please reopen if still not working

**Comment by marcvs83** [comment]
Still having this issue. Just did a fresh npm install.
