### ISSUE TITLE
Tabs swipeable option

### ISSUE THREAD

**Issue by VanyllaGorylla** [react-materialize/react-materialize#511]
### Description

Hello,
For Tabs component,  when using "swipeable" option in tabOptions code returns an error.

### Steps to Reproduce

 <Tabs tabOptions={{ swipeable: true}}>
            <Tab title="t1">
              Tab 1             
            </Tab>
            <Tab title="t2">
             Tab 2
            </Tab>           
</Tabs>

**Expected behavior:** [What you expect to happen]

Page should be displayed properly and user should be able to switch between pages with swipe animation.

**Actual behavior:** [What actually happens]

Page crashes with following error:
react-dom.development.js:15060 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
in line: 
removeChild: function (parentInstance, child) {
      parentInstance.removeChild(child);
    },

### Versions

**react-materialize:** 2.1.2
**materialize-css:** 0.100.2
**react:** 1.6.2

**Comment by alextrastero** [comment]
Hey @VanyllaGorylla, can I have a some sample code? for me this works:
```jsx
    <Tabs className='tab-demo z-depth-1' tabOptions={{swipeable: true}}>
      <Tab style={{background: 'red'}} title='Test 1'>Test 1</Tab>
      <Tab style={{background: 'blue'}} title='Test 2'>Test 2</Tab>
      <Tab style={{background: 'yellow'}} title='Test 3'>Test 3</Tab>
      <Tab style={{background: 'green'}} title='Test 4'>Test 4</Tab>
    </Tabs>
```

Also what exact version of react are you using? required is: react: 16.x

**Comment by VanyllaGorylla** [comment]
Hello,

Thank you for ur answer.  For this example I've used the newest version of react create app, materialize-css and react-materialize.

App.hoc.js
```jsx
import React, { Component } from "react";

export default function(Component) {
  return class Wrapper extends Component {
    constructor(props) {
      super(props);
      this.state = {
        label: "hello"
      };
    }

    componentDidMount() {
      console.log("cmp did mount");
// in real app I do ajax call here and set new state with fetched data.
      setTimeout(() => {
        this.setState({ label: "New label" });
      }, 3000);
    }

    render() {
      return <Component label={this.state.label} />;
    }
  };
}

```

App.js
```jsx
import React, { Component } from "react";
import { Tabs, Tab } from "react-materialize";
import logo from "./logo.svg";
import "./App.css";

import wrapper from "./App.hoc";

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>

        <p>label = {this.props.label}</p>

        <div>
          <Tabs className="tab-demo z-index-1" tabOptions={{ swipeable: true }}>
            <Tab title="Test 1">Test 1</Tab>
            <Tab title="Test 2">Test 2</Tab>
            <Tab title="Test 3">Test 3</Tab>
            <Tab title="Test 4">Test 4</Tab>
          </Tabs>
        </div>
      </div>
    );
  }
}

export default wrapper(App);

```

index.js
```jsx
import React from "react";
import ReactDOM from "react-dom";

import "../node_modules/materialize-css/dist/css/materialize.css";
import "../node_modules/materialize-css/dist/js/materialize";
import "./index.css";

import App from "./App";

import registerServiceWorker from "./registerServiceWorker";

ReactDOM.render(<App />, document.getElementById("root"));
registerServiceWorker();
```

After removing **tabOptions={{ swipeable: true }}** prop, it works like it should.

Thanks for helping out!

**Comment by alextrastero** [comment]
Ok, for now I would remove the `tabOptions` until this is fixed, are you still getting that error?

**Comment by VanyllaGorylla** [comment]
Hello,

Hello, I wrote that without above mentioned option there is no error :) 

Thanks:)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
