### ISSUE TITLE
Timepicker broken

### ISSUE THREAD

**Issue by xGouley** [react-materialize/react-materialize#513]
Timepicker not working (see on your doc/demo)

**Comment by alextrastero** [comment]
What version of `materialize.css` are you using?

**Comment by usrivastava91** [comment]
It's not working for both, 0.100.2 and 1.0.0-beta. Along with the timepicker, the datepicker is also a little different than the materialize.css one. 
I've raised a PR to fix it. Please have a look https://github.com/react-materialize/react-materialize/pull/515

![timepicker](https://user-images.githubusercontent.com/15278455/38022399-01a2cd98-329d-11e8-864e-44ed56888f77.png)
![datepicker](https://user-images.githubusercontent.com/15278455/38022408-08cc6930-329d-11e8-8762-a3e4124c0af7.png)

**Comment by alextrastero** [comment]
Fixed in #515
