### ISSUE TITLE
Having difficulty creating a controlled component with <Input type="checkbox"/>

### ISSUE THREAD

**Issue by cjorda15** [react-materialize/react-materialize#525]
### Description

---Having difficulty creating a controlled component with <Input type="checkbox"/>  ---

Other input types are able to be set as controlled component when provided the prop of value though. 

Also unable to do have a controlled component with <Input type="checkbox"/> with the prop of defaultValue

### Steps to Reproduce

1. Render a  <Input value={this.state.checked} type="checkbox"/>  within a react Component

2. Force a setState change to toggle boolean value on the parent components of the <Input type="checkbox/>

3.) Repeat but with defaultValue = {this.state.checked}

```
Code that would not update after redux store simulated a form reset, which handled all other input 
type but the checkbox.


checked={isChecked}
          defaultValue={isChecked}
          type="checkbox"
          label={option}
          size={this.props.size || 12}
          key={index}
          onChange={e => {
            this.props.handleInput(
              this.props.property,
              this.props.type,
              option
            );
          }}

```

EXPECTED: controlled component with <Input type="checkbox"/> 

ACTUAL: Not controlled. 

    "react-materialize": "2.1.2",
**materialize-css:** 0.98.0
**react:**16.2.0

**Comment by alextrastero** [comment]
Gonna have a look at this

**Comment by Rdore88** [comment]
I am having the same problem so I was wondering if there has been any update to this?

**Comment by alextrastero** [comment]
Still no updates on this, AFAIK we need to reinit the checkbox on some lifecycle method

**Comment by JacksonBates** [comment]
I think I'm hitting this issue as well.

I have an element that can be toggled on/off via the checkbox. This is recorded in state as well. This works fine.

However, there are occasions when the element is toggled via a different source, and while the state changes appropriately, and even the `checked='true|false'` changes in the underlying markup viewed in the dev tools, the actual checkbox on screen makes no change.

Is this the same issue, and does anyone know of a workaround?

**Comment by dtruong11** [comment]
I am having the same problem.

**Comment by Marzon** [comment]
I´ve checked and the problem is with Input component.. It is receiving a new props checked = true but don´t update the internal state just like it does at onChange. Then, on the render, the this.state.checked stills false. 

Where is the best place to update the state with a: this.setState({checked: this.props.checked}) ?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
