### ISSUE TITLE
Upgrading to use materialize-css: 1.0.0-beta

### ISSUE THREAD

**Issue by ellistev** [react-materialize/react-materialize#532]
Is there any thought to update the codebase to support the 1.0.0-beta version of materialise?

update: nevermind.  I see why now. expect some pull requests in the future :)

**Comment by SOSANA** [comment]
where can we find info on the migration update to latest materialize v1.*?

**Comment by alextrastero** [comment]
So far we only support the version stated on the documentation. soon though :)

**Comment by SOSANA** [comment]
Thanks @alextrastero , any chance you could give an update on readme so others don't ask same questions? Also possibly adding even a rough ETA ex 1 to 3 months or PR's welcome etc to help bring the project up to speed for new version? stoked about this project! Cheers

**Comment by n8udd** [comment]
Any plans to update to v1.0.0 as this is now out of beta?

**Comment by alextrastero** [comment]
We are very close, only a few issues left which we would really apreciate some help with https://github.com/react-materialize/react-materialize/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A3.0.0

**Comment by alextrastero** [comment]
Done 👍
