### ISSUE TITLE
How to change input date language

### ISSUE THREAD

**Issue by Lucas-Braz-Cunha** [react-materialize/react-materialize#539]
Is it possible to change the language of input  type = 'date'?
If it is, how can I do so?

### Versions

**react-materialize:** 1.1.1
**react:** 15.6.1

**Comment by alextrastero** [comment]
Hey @Lucas-Braz-Cunha 
YOu can pass options has props
https://github.com/react-materialize/react-materialize/blob/master/src/Input.js#L28

The options for `pickadate` are here: http://amsul.ca/pickadate.js/api/
