### ISSUE TITLE
Breadcrumb not usable

### ISSUE THREAD

**Issue by davidaq** [react-materialize/react-materialize#54]
In the docs, the Breadcrumb component is used with `MenuItem`, but `MenuItem` is not exported in `index.js`.

I tried exporting the component myself but I get `TypeError: Cannot read property 'props' of null` when ever there's children inside`<Breadcrumb>`.

**Comment by isaiah** [comment]
Hi @davidaq, can you try import `MenuItem` from `react-materialize/lib/MenuItem`  and see of the problem still exist?
