### ISSUE TITLE
Change carousel page onClick

### ISSUE THREAD

**Issue by PopTudor** [react-materialize/react-materialize#542]
Hello,
I'm trying to go to next item using the Carousel component when some action happens without clicking an indicator or swiping. Can I accomplish this? it would be ok to programatically click the next indicator to simulate the user.

Thank you!

**Comment by alextrastero** [comment]
Hey @PopTudor, I'm not really sure, I know that Carousel accepts options, have you seen what type of options you can pass?

**Comment by PopTudor** [comment]
@alextrastero Yeah, I checked but doesn't seem to have it. I android we have something like carousel.setIndex(0) which I think is natural for these multiple pages UI

**Comment by alextrastero** [comment]
Checking the materializecss docs:
```js
// Next slide
$('.carousel').carousel('next');
$('.carousel').carousel('next', 3); // Move next n times.

// Previous slide
$('.carousel').carousel('prev');
$('.carousel').carousel('prev', 4); // Move prev n times.

// Set to nth slide
$('.carousel').carousel('set', 4);

// Destroy carousel
$('.carousel').carousel('destroy');
```

You would need to add a `carouselId` [prop](https://github.com/react-materialize/react-materialize/blob/master/src/Carousel.js#L91)

**Comment by alextrastero** [comment]
Closing, let me know if this doesn't work @PopTudor :)

**Comment by PopTudor** [comment]
@alextrastero thank you, works great!
