### ISSUE TITLE
dropdown width checkbox close on change

### ISSUE THREAD

**Issue by zif002** [react-materialize/react-materialize#548]
Hi, I'm using dropdown with the input checkbox 
But if you click on the checkbox then the dropdown is hidden I tried e.stopPropagation(); on dropdown   but then do not  onChange on the checkbox. Is this possible to bypass who? Thanks

**Comment by alextrastero** [comment]
Hey @zif002, can you paste an example so we can debug?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
