### ISSUE TITLE
SideNav component missing

### ISSUE THREAD

**Issue by richmeij** [react-materialize/react-materialize#55]
Hi guys,

Are there any plans on the SideNav component yet?

**Comment by isaiah** [comment]
Hi @richmeij , I'll take a look, last time I checked it's not so straight forward to implement.

**Comment by richmeij** [comment]
Thanks. If it's to much of a hassle right now, I'd be happy take a swing at it. Just wanted to verify if there was anything in the works already.

**Comment by isaiah** [comment]
That would be great, there is a `SubNav` component, but it didn't work properly at the moment.

**Comment by smeijer** [comment]
To bad this one is still missing. Is there any progress on this?

**Comment by richmeij** [comment]
Oh dear, I totally forgot about this issue. Is it still something that needs to be addressed? @isaiah

**Comment by alextrastero** [comment]
Hi @richmeij, that would be great :D

**Comment by richmeij** [comment]
Allright! I'll get on it! :D

**Comment by alduethadyn** [comment]
How's it going @richmeij? Need any assistance? :)

**Comment by richmeij** [comment]
Hey @alduethadyn, I just started working on it this week. I will post any questions I have in this thread.

**Comment by richmeij** [comment]
Hi guys, 
I made a PR (#202) for this to see if I'm moving in the right direction. Any input is appreciated!

**Comment by richmeij** [comment]
Closing this since the PR (#202) has been merged! :tada:
cc @alduethadyn
