### ISSUE TITLE
Will there be support for FileInput?

### ISSUE THREAD

**Issue by ThatBrianDude** [react-materialize/react-materialize#550]

**Comment by onluiz** [comment]
That would be interesting :)

**Comment by alextrastero** [comment]
anyone want to give it a go?

**Comment by niross** [comment]
I had a crack at it. Let me know your thoughts

**Comment by onluiz** [comment]
@ThatBrianDude , @alextrastero @niross 
https://materializecss.com/text-inputs.html in File Input section has a simple example of a File Input.

This is the one we could use here, right?
