### ISSUE TITLE
react-materialize without using the index.html

### ISSUE THREAD

**Issue by OriAmir** [react-materialize/react-materialize#551]
hi
I want to use the library without put all the scripts on the index.html file

I try to install query and matrialize-css library via npm and then to just import them on my index.js file but it's just not working..

there is another way to use the library without put all the references on index.html file?

TNX

**Comment by alextrastero** [comment]
What's the error exactly, this should work.
The scripts in the index.html are to import materializecss (js and css), jquery and the fonts.

**Comment by subratadhal** [comment]
I have react redux setup and have no html file.

**Comment by alextrastero** [comment]
can you see an error on the console?

**Comment by OriAmir** [comment]
@alextrastero  @subratadhal 

Can you explain exactly how you initialize the library ? or you just install is vis npm and use?

I don't have any errors in console , I just now see any css effects on my UI .Then I try to add it to my html and just then I see the css effects .

**Comment by OriAmir** [comment]
@alextrastero  OK I understand you , so I have to add anyway the 'materializecss' to my library to use 'react-materialize'  ?

Yes, I use `create-react-app`  what my options to add materializecss that work?
1. add in html 
2. Try to add to my index.js file this rows (After install the librarys via npm):
import $ from 'jquery';
import 'materialize-css';
import 'materialize-css/dist/css/materialize.min.css';

tnx for your help

**Comment by OriAmir** [comment]
@alextrastero @subratadhal 
Hi , I try everything possible but still not work for me without import the files in index.html 

1. I try to install jqeury,matrilize-css and react-materialize and then import on index.js:
import $ from 'jquery';
import 'materialize-css';
import 'materialize-css/dist/css/materialize.min.css';


2. I try install and import 'jquery' in web pack and then import the css and js in index.js:
   new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.$': 'jquery',
      'window.jQuery': 'jquery',
  })

3. I try to give it directly from node modules in index.js:
import 'materialize-css/dist/js/materialize.min.js'
import 'materialize-css/dist/css/materialize.min.css'\


Nothing work, what i am doing wrong ): ?

**Comment by meteormanaged** [comment]
Looking at something similar myself here.

I'm attempting to use the package with Gatsby, which dynamically generates the index.html with each change/build, so adding links and scripts to the index.html is not an option.  

I was able to get things imported using react-helmet, but that's got me putting script tags in the head, and it's not letting me determine my ordering for css (thus, materialize is overriding my local custom css).  

Gonna keep digging but glad to take any ideas...

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
