### ISSUE TITLE
Carousel doesn't work.

### ISSUE THREAD

**Issue by DmitryNyshchyi** [react-materialize/react-materialize#555]
Hi.
I have problem with carousel.
This carousel was worked, but yesterday break.
I see you do new commit, please, help me.

IDE compile without mistakes, but browser writes:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
 
**react-materialize:** 2.2.1
**react:** 16.0.2

Thanks.

**Comment by alextrastero** [comment]
Hi @DmitryNyshchyi, can you paste here the code you initialise the carousel with?

**Comment by alextrastero** [comment]
Also, what version of `materializecss` are you using?

**Comment by DmitryNyshchyi** [comment]
initialized:
<Carousel images={[
                    'https://lorempixel.com/250/250/nature/1',
                    'https://lorempixel.com/250/250/nature/2',
                    'https://lorempixel.com/250/250/nature/3',
                    'https://lorempixel.com/250/250/nature/4',
                    'https://lorempixel.com/250/250/nature/5'
                ]} />

also
<Carousel options={{shift: 110}}>
                    <CardFirstLoan/>

                    <CardLoan sum={5000}
                              rating="5,0"
                              bonus={5}
                    />

                    <CardLoan sum={7500}
                              rating="5,9"
                              bonus={10}
                    />

                    <CardLoan sum={10000}
                              rating="9,9"
                              bonus={15}
                    />
                </Carousel>

This all code was worked, but now no. 
I tested and to do mistakes -  "<Carousel />"

materialize:0.98.0

**Comment by alextrastero** [comment]
Seems like `lorempixel` is down, try with this service: `https://picsum.photos/250/250`
