### ISSUE TITLE
Collapsible menus in Sidebar

### ISSUE THREAD

**Issue by phillipnunes** [react-materialize/react-materialize#559]
Hi.

Are there variations from _Sidenav_, like in [documentation](https://materializecss.com/sidenav.html)? I am interested in collapsible menus.

I noticed the component _Collapsible_ but I would like to know if there is something already developed in the _Sidenav_ component itself.

Thanks.

**Comment by phillipnunes** [comment]
And i tried this:
```
  render () {
    return (
      <SideNav fixed={this.state.isFixed}>
        <SideNavItem userView
          user={{
            background: Background,
            image: Avatar,
            name: 'some_name',
            email: 'some_email'
          }}
        />
        <Collapsible>
          <CollapsibleItem header='Name Header' >
            <SideNavItem waves href='#!third'>New</SideNavItem>
            <SideNavItem waves href='#!third'>List</SideNavItem>
          </CollapsibleItem>
          <CollapsibleItem header='Another thing' >
            <SideNavItem waves href='#!third'>Third Link With Waves</SideNavItem>
          </CollapsibleItem>
        </Collapsible>
      </SideNav>
    )
  }
```

And get this warning in console:
`Warning: validateDOMNesting(...): <li> cannot appear as a descendant of <li>. See li > ... > li.`

If there is not a better way to do this, how to solve this problem? I think the reason is the combination of component _CollapsibleItem_ with _SideNavItem_

[ ]'s

**Comment by alextrastero** [comment]
Hey @phillipnunes, why not replace `SideNavItem` with another element?

**Comment by phillipnunes** [comment]
Hi @alextrastero.

Yes, it is a good ideia. I thought there was already some other way of combining the components to avoid this warning.

For now, I'll do as you suggested.

Thanks,
Phillip
