### ISSUE TITLE
Remove JQuery dependencies 

### ISSUE THREAD

**Issue by marvinkome** [react-materialize/react-materialize#560]
## Feature request 

I love materialize css but the fact that in react I'll have to use it with jquery isn't really cool. I'll be happy to join in so they can be a rewrite for the js aspect to be completely independent of jquery. Then we only import materialize.css.

**Comment by alextrastero** [comment]
Agree. `materialize@1.0.0-rc.1` doesn't require jQuery, ideally we would need to upgrade and fix the breaking components

**Comment by marvinkome** [comment]
I'd love to help with this, how can I get started

**Comment by marvinkome** [comment]
@alextrastero I'm currently working on removing JQuery as a dependency. I'm currently trying to understand how you mocked jquery to do the same for window.M, can you give a little insight here. Thanks

**Comment by alextrastero** [comment]
Hey @marvinkome, there's some stackoverflow posts about mocking globals with Jest, something like:
```js
const M = window.M;
const method1Mock = jest.fn();
const method2Mock = jest.fn();

describe('something', () => {
  beforeEach(() => {
    window.M = {
      method1: method1Mock,
      method2: method2Mock
    };
  });

  afterEach(() => {
    window.M = M;
  });
```

**Comment by alextrastero** [comment]
I've created a `3.0.0@beta.0` branch, if you have time please test and report any bugs :)

**Comment by marvinkome** [comment]
Awesome, I will.

**Comment by alextrastero** [comment]
Done 👍
