### ISSUE TITLE
onClick on carousel not working if scrolling left

### ISSUE THREAD

**Issue by CLopes1** [react-materialize/react-materialize#561]
### Description

I have images in a carousel with `onClick` handlers but they only fire if I scroll to the right.

### Steps to Reproduce

```
const cats = [
    {
        image: 'http://r.ddmcdn.com/w_830/s_f/o_1/cx_0/cy_66/cw_288/ch_162/APL/uploads/2014/10/cat_5-1.jpg',
        id: 1
    },
    {
        image: 'https://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg',
        id: 2
    },
    {
        image: 'https://d17fnq9dkz9hgj.cloudfront.net/uploads/2012/11/91615172-find-a-lump-on-cats-skin-632x475.jpg',
        id: 3
    }
];



<Carousel
    options={{
        dist: -60,
        shift: 60,
        indicators: true
    }}
>
    {cats.map((cat) => {
        return (
            <img
                alt="cat"
                key={cat.id}
                onClick={() => { console.log(cat.id) }}
                src={cat.image}
            />
        );
    })}
</Carousel>
```

**Expected behavior:** [What you expect to happen]
I expected the onClick to fire when I scroll to the left and click on the cat. It does, however fire when I scroll to the right.

**Actual behavior:** [What actually happens]
The onClick event doesn't fire.

### Versions

**react-materialize:** 2.3.1
**materialize-css:** 0.98.2
**react:** 16.0.0

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
