### ISSUE TITLE
Using Tab with react-router (Link)

### ISSUE THREAD

**Issue by OriAmir** [react-materialize/react-materialize#562]
There is some option to use Link (from react-router) in tabs?( like in the navbar)

I want that every click on one of tabs will redirect with the link.
something like that:
`<Tabs className='tab-demo z-depth-1'>
            <Link to={`admin/`}><Tab title="admin"/></Link>
            <Tab title="Test 2" active>Test 2</Tab>
        </Tabs>
`

or maybe tab will get property of 'to'? 

thanks!

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
