### ISSUE TITLE
Preloader color error

### ISSUE THREAD

**Issue by Xstoudi** [react-materialize/react-materialize#563]
### Description

[Description of the issue]

### Steps to Reproduce

1. Go on the Preloader page of React-Materialize website or add a Preloader that doesn't flash on your project

**Expected behavior:** Example page load correctly

**Actual behavior:** Crash because `color` is not defined [Preloader.js#L20](https://github.com/react-materialize/react-materialize/blob/3e9f7c3fae0e734b6b87fd9696614be0c51fd6dc/src/Preloader.js#L20)

### Versions

**react-materialize:** 2.3.1
**materialize-css:**  0.100.2
**react:** 16.4.1

**Comment by dmitry-yudakov** [comment]
https://github.com/react-materialize/react-materialize/pull/564 should fix it

**Comment by ditaW** [comment]
affected versions:
2.3.1
2.3.0
last working version:
2.2.1

**Comment by alextrastero** [comment]
Version 2.3.2 should fix this, thanks all for your help :)
