### ISSUE TITLE
Fixed sidenav issue

### ISSUE THREAD

**Issue by Xstoudi** [react-materialize/react-materialize#567]
### Description

Can't create a fixed sidenav.

### Steps to Reproduce

Try to instanciate a fixed sidenav.

**Expected behavior:** The sidenav appears

**Actual behavior:** `React.cloneElement(...): The argument must be a React element, but you passed undefined.`

### Versions

**react-materialize:** 2.3.2
**materialize-css:** 0.100.2
**react:** 16.4.1

**Comment by alextrastero** [comment]
solved in `2.3.3` thanks for catching this!
