### ISSUE TITLE
Preloader documentation bug

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [react-materialize/react-materialize#569]
### Description

when you go to the doc of preloader component you got an empty page

### Steps to Reproduce

1. Go to the docs https://react-materialize.github.io/#/
2. Click on the Components nav
3. Click on the Preloader item

**Expected behavior:** See the documentation

**Actual behavior:** empty page

**Comment by alextrastero** [comment]
Thanks for spotting this, fixed now
https://react-materialize.github.io/#/preloader
