### ISSUE TITLE
Input "type = switch" does not handle onChange

### ISSUE THREAD

**Issue by linuxenko** [react-materialize/react-materialize#57]
Input element with type `switch` does not attach `onChange` event.

**Comment by alextrastero** [comment]
Hey @linuxenko, what is an input type `switch` ? 😄

**Comment by linuxenko** [comment]
[![](https://sc-cdn.scaleengine.net/i/f114c72c251aa78025ded4af38d0f563.png)](https://react-materialize.github.io/forms.html)

**Comment by alextrastero** [comment]
Good catch
https://github.com/react-materialize/react-materialize/pull/58

**Comment by linuxenko** [comment]
Thanks
