### ISSUE TITLE
3.0.0 Card.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#584]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by alextrastero** [comment]
I'll jump on this

**Comment by CloudPower97** [comment]
@alextrastero Whoops, I'm almost ready with a PR for this... I'm sorry for the confusion, it's my fault.
What should we do now? :grimacing:

**Comment by alextrastero** [comment]
Ah no problem, I didn't manage to start, been very busy :) you grab it

**Comment by alextrastero** [comment]
ping @CloudPower97 lemme know if i can help :)

**Comment by CloudPower97** [comment]
Hey, @alextrastero I already have a branch on my forked repo, going to create a PR in a few days I hope.

**Comment by alextrastero** [comment]
Card component doesn't seem to have changes, please reopen if it does :)
