### ISSUE TITLE
3.0.0 CardTitle.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#586]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by mccraveiro** [comment]
There was no changes to cards. Reference: https://github.com/Dogfalo/materialize/blob/v1-dev/v1-changelog.md

**Comment by mccraveiro** [comment]
It seems to be working just fine on #733. Should we close this issue?
