### ISSUE TITLE
3.0.0 Footer.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#594]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by dmitry-yudakov** [comment]
I think I could help with few more - like this one?

**Comment by dmitry-yudakov** [comment]
This component is also fine as it is.

Unrelated to 3.0.0 there's small issue with copyright symbol in the docs which I could fix with PR for master. 

And perhaps a link for [materialize-css footer page](https://materializecss.com/footer.html) could be useful - for general advice about how to structure the main page and a sticky footer?

**Comment by alextrastero** [comment]
Hey @dmitry-yudakov, how about adding the missing info to our docs? https://github.com/react-materialize/react-materialize/blob/master/docs/src/pages/FooterPage.js

**Comment by dmitry-yudakov** [comment]
I have added the info about how to structure the main page and a sticky footer from Materialize and fixed broken copyright symbol.

I created pull request #640 - it's for master branch since the change is unrelated to 3.0.0

**Comment by CloudPower97** [comment]
Hey @alextrastero, I think there is nothing to do here. Do you agree?
