### ISSUE TITLE
3.0.0 Input.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#596]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by alextrastero** [comment]
I'm grabbing this one

**Comment by alextrastero** [comment]
Creating:

- [ ] TextInput.js
- [ ] Select.js
- [ ] Checkboxes.js
- [ ] Autocomplete.js (refactor)

**Comment by CloudPower97** [comment]
Should we move _TimePicker_ and _DatePicker_ in their own component?

**Comment by CloudPower97** [comment]
Hey, @alextrastero what about the [`range` input](https://materializecss.com/range.html)?

**Comment by alextrastero** [comment]
Good catch @CloudPower97, that also needs implementing

**Comment by alextrastero** [comment]
Done :)
