### ISSUE TITLE
3.0.0 Modal.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#599]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by mendaomn** [comment]
According to [the migration guide](https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md#modal)

> Modal
Change attribute data-activates to data-target
Removed ready and complete callback, use onOpenEnd and onOpenEnd callback instead

I've gone ahead and changed the propTypes accordingly. I'm not sure whether this name change should be added to our tests

All tests seem to be passing, is there another suggested way to "Check that the component works" ?

**Comment by alextrastero** [comment]
Hey @mendaomn, that means manual QA, just fire it up locally and see if it works, is there a PR for this?

**Comment by mendaomn** [comment]
I apologize for the very BASIC question, but what do you mean by "fire it up and see if it works"? The only way I found was running tests :)

**Comment by alextrastero** [comment]
No problem!
If you clone this repo/branch: https://github.com/react-materialize/webpack-boilplate/tree/beta-debug on a folder next to your react-materialize repo and npm install; npm start you will be able to test your changes :)
