### ISSUE TITLE
input "type = checkbox" refs problem

### ISSUE THREAD

**Issue by linuxenko** [react-materialize/react-materialize#60]
[![](https://sc-cdn.scaleengine.net/i/ed8f407e8545e94ab61a248a663aaaca.png)](https://sc-cdn.scaleengine.net/i/ed8f407e8545e94ab61a248a663aaaca.png)

I'm not sure i know what does it means, it appears from following code :

```js
          <Row>
            <Input name="ch" type='checkbox'  label="test" />
          </Row>
```

**Comment by linuxenko** [comment]
Please check  #59

**Comment by alextrastero** [comment]
@linuxenko I guess this can be closed now right?

**Comment by linuxenko** [comment]
@alextrastero yes, it fixed
