### ISSUE TITLE
3.0.0 Preloader.js - ProgressBar.js & Spinner.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#603]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by dmitry-yudakov** [comment]
I'll check this one

**Comment by dmitry-yudakov** [comment]
Btw

> Keep jQuery initialisation of component if exists

Why keep it? To make the transition easier?

**Comment by alextrastero** [comment]
That was my initial thought yes, but to be honest it's a mayor breaking change so let's go ahead and remove it :)

p.s. could this be also done in your previous PR?

**Comment by alextrastero** [comment]
So we can mark this as done?

**Comment by dmitry-yudakov** [comment]
Yes, I think so

**Comment by CloudPower97** [comment]
> That was my initial thought yes, but to be honest it's a mayor breaking change so let's go ahead and remove it :)
> 
> p.s. could this be also done in your previous PR?

So, can we drop jQuery? I've would like to contribute and this is not clear to me as of now.

**Comment by alextrastero** [comment]
Hey @CloudPower97, in the materialize-css docs it shows you how to initialise the component using a `M` global object instead of `jQuery`

**Comment by alextrastero** [comment]
Any updates here?

**Comment by dmitry-yudakov** [comment]
I think this issue can be closed - Preloader.js, ProgressBar.js and Spinner.js are ok.

I first created jQuery offtopic here, sorry about that. These components don't use jQuery and require no additional changes.

**Comment by alextrastero** [comment]
Ok closing :)
