### ISSUE TITLE
3.0.0 Table.js

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#608]
### Upgrade to latest materialize-css@1.0.0-rc.2

AC
- Branch off 3.0.0-beta.0
- Check that the component works
- Update with new available modifiers and options
- Update propTypes and description
- Update examples page
- Create PR into branch 3.0.0-beta.0

**Comment by alextrastero** [comment]
Hey @dmitry-yudakov, that would be great, as per mentioning I'm not sure :/

**Comment by alextrastero** [comment]
👋 @dmitry-yudakov

**Comment by dmitry-yudakov** [comment]
@alextrastero Sorry for the delay, please check the pull request.

**Comment by dmitry-yudakov** [comment]
@alextrastero Sorry for the delay, please check the pull request.
