### ISSUE TITLE
Input label does't change active state on value-change

### ISSUE THREAD

**Issue by ditaW** [react-materialize/react-materialize#612]
### Description

While changing the value-property of an <Input>-Component the active-state of the label-active-state doesn't change, so it does not fade away.

### Steps to Reproduce

1. Create an &lt;Input value=this.state.xyz label="mylabel"&gt;
2. call setState{xyz:"Test"}

**Expected behavior:** 
the label "mylabel" should fade to the top

**Actual behavior:** 
the value and the label overlap

** Possible conclusion **
Input.js:
this.state.value is set in the constructor but not in "componentWillReceiveProps"
i.e. Input.js line 92:
+  if (nextProps.value && nextProps.value !== this.state.value) this.setState({value:nextProps.value})

### Versions

**react-materialize:** 2.3.3
**materialize-css:** 1.0.0-rc2
**react:** 16.4.1

**Comment by alextrastero** [comment]
Hi, currently we only support `materialize-css@0.100.2`, please downgrade and test again :)

On a separate note: We’re currently updating react-materialize to support the latest materialize-css version and hopefully remove the jQuery dependency, we would really appreciate if you want to give it a try in your project. Branch `3.0.0-beta.0`, issues labeled [3.0.0](https://github.com/react-materialize/react-materialize/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A3.0.0) please ;)

**Comment by alextrastero** [comment]
And please reopen if this is still happening :)

**Comment by ditaW** [comment]
> And please reopen if this is still happening :)
I don't think i have the rights to reopen an issue :)

**Comment by alextrastero** [comment]
👍

**Comment by alextrastero** [comment]
It sure does @geoff-wasilwa, please submit one :)

**Comment by alextrastero** [comment]
AFAIK this is solved

**Comment by ivofrancisco** [comment]
From what I've figured out it happens only when there is input field with type Password. And this is the best solution I came across:
autoComplete="new-password"

**Comment by alextrastero** [comment]
This is fixed in `react-materialize@3.x`

**Comment by ivofrancisco** [comment]
Ok
Thank you very much.
Best regards
Ivo

Alexander Odell <notifications@github.com> escreveu no dia sexta,
29/03/2019 à(s) 13:48:
