### ISSUE TITLE
Card Reveal - onRevealOpen/Close event 

### ISSUE THREAD

**Issue by vickyvxr** [react-materialize/react-materialize#618]
### Description
Good afternoon,
I'm testing the Card Reveal component and I would like to know when the reveal is opened or closed.
I can't see any event to be passed by prop to the Card component.
Is there any way to do this? 
Thanks in advance.

### Versions

**react-materialize:**2.3.3.
**react:** 16.4.0

**Comment by alextrastero** [comment]
Hi, there's no way of passing that 'option' to `Card`, if it's not implemented in http://archives.materializecss.com/0.100.2/cards.html it can't be added here. :)
