### ISSUE TITLE
Collapsible accordion all expanded initially

### ISSUE THREAD

**Issue by jesseflorig** [react-materialize/react-materialize#62]
<Collapsible accordion> initially renders with all list items expanded. Once an item is clicked, the list behaves as expected.

**Comment by alextrastero** [comment]
Hi @jesseflorig, i've tried to reproduce this but no luck, it seems to work fine. Do you get any error message? Can you show us how you implement the component?

**Comment by alextrastero** [comment]
No answer, closing.
