### ISSUE TITLE
(urgent help) unable of get use function of materilaze.js which is connected from html via jquery inside reactjs

### ISSUE THREAD

**Issue by get4prince** [react-materialize/react-materialize#621]
third party js file of materilizejs is cannot possible to access from reactjs itself
Steps to Reproduce

1.  `<Modal`
    id='foo'
    header='Modal Header'>
    Lorem ipsum dolor sit amet
  `</Modal>`

2.`import $ from 'jquery'`

3. `handleSubmit(event){
      event.preventDefault();
      $('foo').modal('open');
    }`

**Expected behavior: modal should be open
**Actual behavior:.modal() is not found

### Versions
i am using create-react-app

**Comment by alextrastero** [comment]
Hey @get4prince have a look at this sample REPO
https://github.com/alextrastero/react-materialize-cra-example

**Comment by get4prince** [comment]
solved actually i was trying to add js file into html file ...
