### ISSUE TITLE
Fixed Action Button - Vertical

### ISSUE THREAD

**Issue by jamesmart77** [react-materialize/react-materialize#622]
### Description

There is a slight typo in the code example of the vertical fixed action button. The Button component has `faicon` as the parameter but it should be `icon`.

See error on page: https://react-materialize.github.io/#/buttons
Error located in file: https://github.com/react-materialize/react-materialize/blob/master/examples/FixedActionButton.js

**Comment by alextrastero** [comment]
Super @jamesmart77 wanna give it a go?

**Comment by jamesmart77** [comment]
absolutely! Can you add me as a collaborator?

**Comment by alextrastero** [comment]
Hey @jamesmart77, you can already collaborate :) just submit a PR

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
