### ISSUE TITLE
Datepicker defaultValue not displaying

### ISSUE THREAD

**Issue by bluejillo** [react-materialize/react-materialize#629]
I cannot get defaultValue for the datepicker to display. If I put a print statement into the datepicker's event handler, it prints out the default value.

Here is the datepicker:
`<Input type="date" id={episode.id+"_date"} className="required_input dpick" name="episode_date" defaultValue={episode.episodeDate} onChange={this.handleEpisodeDateChange}/>`

Here is its event handler:
`handleEpisodeDateChange(e){
		console.log('date fired');
		console.log('new value',e.target.value);
		console.log('defaultValue',e.target.defaultValue);
	}`
Here is the console log when the event handler is triggered:
date fired
new value 17 August, 2018
defaultValue Jan-15-1986

If I use the regular materialize css I can get the default value to show up. The reason I am using this one is because no matter what I did, I could not get the event handler to fire.

Am I just doing something wrong here?

EDIT: I have also tried using the value attribute with no affect.

**Comment by alextrastero** [comment]
Yeah, it's not very easy to set an initial date, but it's doable;
```jsx
const options = {
  onStart: function() {
    this.set('select', new Date('Mon, 20 Apr 2015 00:00:00 EDT'))
  }
}

<Input type='date' options={options} ... />
```
