### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by Etregoning** [react-materialize/react-materialize#635]
### Description

I can't seem to use any of the components from this package. I get the same error every time.

### Steps to Reproduce

1. Edited Home.js in components directory
2. Made slider subcomponent
3. ran code

**Home.js code:**
```
// @flow
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import routes from '../constants/routes.json';
import styles from './Home.css';
import HomeSlider  from './subcomponents/home/HomeSlider'

type Props = {};

export default class Home extends Component<Props> {
  props: Props;

  render() {
    return <HomeSlider />
  }
}

```

**HomeSlider.js code:**
```
import React from 'react'
import { Slider, Slide } from 'react-materialize'

export default () => (
    <Slider>
        <Slide
            src="http://lorempixel.com/580/250/nature/1"
            title="This is our big Tagline!">
            Here's our small slogan.
        </Slide>
        <Slide
            src="http://lorempixel.com/580/250/nature/2"
            title="Left aligned Caption"
            placement="left">
            Here's our small slogan.
        </Slide>
        <Slide
            src="http://lorempixel.com/580/250/nature/3"
            title="Right aligned Caption"
            placement="right">
            Here's our small slogan.
        </Slide>
    </Slider>
)
```

**Expected behavior:**
Slider will show up in my app

**Actual behavior:**
Uncaught ReferenceError As Stated in title.

### Versions

**react-materialize:** 2.4.2
**materialize-css:** 0.100.2
**react:** 16.4.1

**Comment by alextrastero** [comment]
Hey @Etregoning, did you manage to solve this?

If you are using create-react-app, please have a look at https://github.com/alextrastero/react-materialize-cra-example for an example.

The issue probably is that you might be requiring jquery after materialize-css js.
