### ISSUE TITLE
Radio buttons not working as expected on second selection.

### ISSUE THREAD

**Issue by Squinner21** [react-materialize/react-materialize#645]
### Description

The radio buttons do not seem to function correctly during the second selection of a radio button. 

### Steps to Reproduce

1. Navigate to radio button example react materialize website: https://react-materialize.github.io/#/forms
2. Select the 'Red' radio button
3. Select the 'Yellow' radio button

**Expected behavior:** 
Red button should be unselected and yellow button should be selected.

**Actual behavior:** 
Red button stay selected.

**Comment by mizinsky** [comment]
+1

**Comment by ljachymczyk** [comment]
+1

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
