### ISSUE TITLE
Unable to have controlled input (Input contains an input of type text with both value and defaultValue props)

### ISSUE THREAD

**Issue by SharePointPro** [react-materialize/react-materialize#652]
### Description

If you create a controlled component with value on a textfield, you get the react error message:

Input contains an input of type text with both value and defaultValue props

To Reproduce:

1. Create `<Input type="text" value={this.state.aValue} onChange={this.onChange} />`
2. Load page, open console

**Expected behavior:** `<inputs />` with value should not have a defaultValue

**Actual behavior:** `<inputs />` are rendered with both a defaultValue and a Value

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
