### ISSUE TITLE
How to add onClick event to Slide element?

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [react-materialize/react-materialize#653]
There is no onClick prop on Slide element.
Was trying to add absolute position div on top of every slide, but it causes bugs.
![image](https://user-images.githubusercontent.com/23122290/46258290-82b5e300-c4d0-11e8-9993-7a9357c2dff2.png)
need to add `onClick={this.onSelectPicture(index)}`

**Comment by AlexandrDobrovolskiy** [comment]
Solved using <li> instead of Slider
![image](https://user-images.githubusercontent.com/23122290/46259480-b8fc5e00-c4e2-11e8-962a-79d7481ca1f0.png)

**Comment by alextrastero** [comment]
All props are passed to the `Slide` component, adding an `onClick` should work :)
https://github.com/react-materialize/react-materialize/blob/master/src/Slide.js#L33
