### ISSUE TITLE
Icon className not effect inside input

### ISSUE THREAD

**Issue by OriAmir** [react-materialize/react-materialize#657]
hi I want to customize icon behind the input field , but it's not add any class to the Icon when it's inside the Input : 

```
  <Input s={6} label="First Name" validate>
        <Icon className={styles.test}>account_circle</Icon>
   </Input>
```

When it's alone without the input it's works well:
`        <Icon className={styles.test}>account_circle</Icon>
`
what could be the problem?

tnx!

**Comment by alextrastero** [comment]
Hey @OriAmir, `Input` accepts an `icon` prop which can be set to `account_circle`, this will add `prefix` class to the icon, but you can't pass **additional** classes this way.

As per your code sample, `Input` doesn't accept children.

I would write it like this:
```jsx
<Icon className={`${styles.test} prefix`}>account_circle</Icon>
<Input s={6} label="First Name" validate />
```

**Comment by alextrastero** [comment]
I'm afraid currently there's no way to add external classes to the `Input`'s icon

**Comment by OriAmir** [comment]
@alextrastero tnx for your help  . when I write that in your way it's not in the same line , i mean icon in separte line and input in separte line.

**Comment by alextrastero** [comment]
Yes, currently it's not possible to add a classname to the Input icon, I solution would be to pass an icon node as a prop instead of a string to `<Input />`, want to give it a go?

**Comment by OriAmir** [comment]
@alextrastero  can you give me example of what you mean please ? tnx

**Comment by alextrastero** [comment]
Right now Input accepts an icon prop, this should be a string. We could add a node `const icon = <Icon className="xxx" />` and pass it as a prop to Input.

Then we would need an if/else to check the type of icon prop and render accordingly.
