### ISSUE TITLE
Unable to Customize my Buttons

### ISSUE THREAD

**Issue by Dolcekar** [react-materialize/react-materialize#663]
### Description

For some reason I cannot write content inside my 'wave' buttons. One is supposed to be 'sign up', the other 'sign in'. To add space in between them, I used Row and Col this way: 
 ```
<Row>
        <Col s={6} className='grid'>
        <a class="waves-effect waves-light btn-large" href="#">Sign in </a>
        </Col>
      
        <Col s={6} className='grid'>
          <a class="waves-effect waves-light btn-large" href="#">Sign Up</a>
        </Col>
      </Row>
```
When I run my code, I get to show one full label and half the other
![error-buttons-materialize](https://user-images.githubusercontent.com/36909773/46585551-5f46e700-ca40-11e8-902b-2665b2926519.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [or Code Sample...]

**Expected behavior:** [What you expect to happen]

Display both labels correctly

**Actual behavior:** [What actually happens]
Labels are not showing correctly, by labels I mean text content of buttons
### Versions

**react-materialize:** 0.98.0
**materialize-css:** 0.98.0
**react:** ^16.0.0

**Comment by alextrastero** [comment]
I tried adding your sample code [here](http://react-materialize.github.io/) and it works fine, have you checked what the `css` is doing? Maybe there's something else influencing

**Comment by Dolcekar** [comment]
@alextrastero I should have mentioned that this is contained within a Parallax. My code looks like this 
```
``export default () => (
<div>
  <Parallax imageSrc='/img/findHelp.jpg'/>
  <div className="section  orange lighten-2 ">
    <div className=" row container ">
      <h2 className="header text-center">Join the World and Change It</h2>
      <p className="grey-text text-darken-3 lighten-3">We all need help, everyday, everywhere. 
      Join the Samaritans network, a place where people help one another.</p>
      <Row>
        <Col s={6} className='grid'>
        <a class="amber darken-4 waves-effect waves-light btn-large" href="#">Sign Up </a>
        </Col>
      
        <Col s={6} className='grid'>
          <a class=" amber darken-4 waves-effect waves-light btn-large" href="#">LogIn </a>
        </Col>
      </Row>
      </div>
    </div>

  

  <Parallax imageSrc="/img/getHelp.jpg"/>

  <div className="footerContainer text-center orange lighten-2">
        <footer> Copyright &copy; {new Date().getFullYear()} The Samaritan</footer>

    </div>
</div>
)``
```

**Comment by alextrastero** [comment]
I see, what's the rendered css of this button ?

**Comment by Dolcekar** [comment]
Coming straight from here https://materializecss.com/waves.html#! I did not add anything from my end. Maybe materializecss components are not entirely compatible with react-materialize?

**Comment by alextrastero** [comment]
Thanks, I mean I need a screenshot of the rendered css, to see why it's cutting, maybe there's a maxwidth somewhere?

**Comment by Dolcekar** [comment]
Does this picture help? What I noticed is, it only displays both buttons text when I named them both 'Sign Up'.... it's the weirdest thing. I don't think it has to do with the css itself. It's something about the way the code is written. If it helps, I'll be happy to run a demo of my code using Screencastify to make it fast and easy.

![template-buttons-error](https://user-images.githubusercontent.com/36909773/46606864-db870c00-cacc-11e8-864f-54040bc5e16d.png)

**Comment by alextrastero** [comment]
Can you right click on the button with the issue and click on inspect, then paste here a screenshot of the `computed` css, like so:
![screen shot 2018-10-08 at 2 37 15 pm](https://user-images.githubusercontent.com/4152819/46609257-b19f0b00-cb07-11e8-9167-3fb7cc04f00c.png)

**Comment by lastgiven** [comment]
Should your class on the anchor not be className?

What happens when you change 
`class=" amber darken-4 waves-effect waves-light btn-large"`
to
`className=" amber darken-4 waves-effect waves-light btn-large"`

**Comment by Dolcekar** [comment]
@lastgiven , thank you, I am glad you caught that, but sadly didn't fix it!
@alextrastero Here is the screenshot. I hope this gives a better insight. You may not have wanted to see the entire details list but just in case!
![dev-tools-button-specs](https://user-images.githubusercontent.com/36909773/46625393-d1333500-cb01-11e8-9bb4-91ac639ba024.png)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
