### ISSUE TITLE
Tabs - PR proposal: Which Tab am I currently on? 

### ISSUE THREAD

**Issue by mendaomn** [react-materialize/react-materialize#665]
Hi,

I've used react-materialize Tabs before and I've always found myself in need of reacting to a tab change.
However the onSelect method just gives me back an idx (which seems to be different everytime??) and I'm not able to recognize which Tab I'm currently on.

I'd love it to submit a PR to simply change the argument passed to the onChange callback, somewhere around here: [Tabs.js#L21](https://github.com/react-materialize/react-materialize/blob/master/src/Tabs.js#L21)

I'm thinking something along the lines of:

```js
const target = {
  idx, // I'm not sure what purpose this serves, but it's the id currently passed through
  title // The title of the active tab
}
onChange( target, e)
```

What do you think?

Should I go on and PR?

**Comment by alextrastero** [comment]
Hey @mendaomn, we are rewritting these components to adapt to the materialize-css@1.0.0, there's a milestone set and lots of issues tagged with 3.0.0-beta, you want to have a look? We could add this feature there. This was the PR that was already done, but you can add new features to it:
https://github.com/react-materialize/react-materialize/issues/607

**Comment by mendaomn** [comment]
Sure would love to help out with the 3.0.0-beta, even though I'm not sure I understand what the single issues describe to do :) Can you help me out with that?

**Comment by alextrastero** [comment]
Well that issue is already closed, the idea is to update each component to the new materialize-css interface, remove jquery init methods and add new options.
More info: https://github.com/react-materialize/react-materialize/wiki/Updating-to-new-materialize-css-version

**Comment by BilalHalayqa** [comment]
Hi, seems this is still pending ? How can I get the selected tab?
