### ISSUE TITLE
Dropping Icon component in favor of Material Design Icons for React

### ISSUE THREAD

**Issue by CloudPower97** [react-materialize/react-materialize#674]
Hello,
I would like to know if we could drop the actual implementation of `Icon` component to instead use _[Material Design Icons for React](https://github.com/levrik/mdi-react)_.

It has ALL of the original Material icons made by __Google__ (which you can find [here](https://material.io/tools/icons/?style=baseline)) plus some (a lot, actually) of community made one.

I'm asking this because I recently worked on a project which uses `react-materialize` and  a lot of icons.

At first everything was fine, but soon I've realized I was in need of more icons than the one provided by Google (and consequently `react-materialize` implementation of `Icon`).

Then I discovered this library and it plays very well with `react-materialize` I can say.

But It's strange to have two `Icons` component from two different packages which fulfill the same exact task.

What do you think? 

This might be a really good enhancement for `react-materialize`!

**Comment by CloudPower97** [comment]
No, they do not have these extra icons.  That's the problem. 
If I wanted to use more icon I would have to import both the Google Material Icons stylesheet and this package to use every icon I need...

But this package has everything that `materialize-css` uses plus, as said before, a lot more of community made icons which follows the _Google Material Design_ guidelines.

Moreover they are already packaged as single components and they renders as SVG.

**Comment by alextrastero** [comment]
Ok, going to have a look :)

**Comment by CloudPower97** [comment]
Thanks, I think you will like this idea as  much as I do

**Comment by CloudPower97** [comment]
Hey @alextrastero did you have some time to get into this? I'm still pretty much convinced it's a nice move :smile:

**Comment by alextrastero** [comment]
Do you have a sample PR I could look at for the implementation?

**Comment by alextrastero** [comment]
Closing for now, let me know if we need to reopen this

**Comment by CloudPower97** [comment]
Hey, @alextrastero, I think we can make any `icon` `prop` a `node` and not using `Icon` component ourselves in other components of `react-materialize`.
If the user wants, he can use the component shipped with `react-materialize`, otherwise he is able to use anythings he wants, like [`Material Design Icons for React`](https://github.com/levrik/mdi-react).

This is the same approach used in #793 .

Let me know if this is ok for you, I'd like to open a **P.R** for this, if you agree. :smile:
