### ISSUE TITLE
Cant figure out how to initialize dropdown for navbar on mobile screen

### ISSUE THREAD

**Issue by vincefio** [react-materialize/react-materialize#681]
### Description
On smaller than medium screen size my navbar list items do not turn into a dropdown menu.  I'm not sure how to initialize this process as i normally do with materialize.  If there is a method to fix this problem please let me know.

Thanks!

In materialize documentation it says:

Initialization
After including the sidenav-trigger line into your navbar, all you have to do now initialize the plugin. This example below assumes you have not modified the classes in the above example. In the case that you have, just change the selector in the line below to match it.

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.sidenav');
    var instances = M.Sidenav.init(elems, options);
  });

  // Or with jQuery

  $(document).ready(function(){
    $('.sidenav').sidenav();
  });

### Versions
"^2.4.6"

**react-materialize:** x.x.x
**materialize-css:** x.x.x
**react:** x.x.x

**Comment by alextrastero** [comment]
Hey @vincefio, does this work on the browser? how about when you use mobile size on browser?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!

**Comment by mritunjaymusale** [comment]
Yes, it's not working on 3.8.3
