### ISSUE TITLE
"required" Input not being validated

### ISSUE THREAD

**Issue by tonio-ramirez** [react-materialize/react-materialize#685]
### Description

`Input` fields validate `minLength`, `maxLength`, and `pattern` properly, but do not mark the field as `invalid` if it is empty and `required`.

### Steps to Reproduce

1. `<Input required validate/>`
2. Enter text
3. Delete text, leaving input empty

**Expected behavior:**
Input field is marked invalid (red, with `invalid` class)

**Actual behavior:**
Input field is marked clean (gray, without `invalid` or `valid` class)

### Versions

**react-materialize:** 2.4.7
**materialize-css:** 0.98.0
**react:** 16.5.2

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
