### ISSUE TITLE
Input Error Message are hidden?

### ISSUE THREAD

**Issue by jhe01** [react-materialize/react-materialize#687]
Input error message are not displayed until you click on the input tag. and the error message do the transition like the actual label of the input.

upon checking on html code, the error message was inside the label of the input itself (label:after).

Expected behavior: it should be displayed under the input tag.

Actual behavior: 
![image](https://user-images.githubusercontent.com/35474475/47564341-405cb600-d957-11e8-9b1c-5c2bcd0a0af8.png)

### Versions

react-materialize:^2.4.6
materialize-css: 0.100.2
react: 16.5.2

Thanks in Advance for the Help!

**Comment by jhe01** [comment]
@haddyo 

> Did you tried using the prop 'error'?
 yeah, i have error prop on my input.

> if am wrong, can you be little elaborate on what you want to fix?
![image](https://user-images.githubusercontent.com/35474475/47631074-4503b300-db7f-11e8-8c86-0bd4008f0e47.png)

above image (from materializecss website), there was a highlighted helper text. that text was not being displayed on my input.

**Comment by haddyo** [comment]
![image](https://user-images.githubusercontent.com/24606061/47633169-f18b6800-db72-11e8-9181-701f32863e23.png)


Try the above Properties 'error' & 'success' along in your Input Component

**Comment by jhe01** [comment]
@haddyo 

first thing, here is my code

![image](https://user-images.githubusercontent.com/35474475/47633483-0c68d700-db89-11e8-9ba7-9324ad7dee24.png)

second thing, this is the preview before clicking the input.

![image](https://user-images.githubusercontent.com/35474475/47633526-39b58500-db89-11e8-8ab7-93dde7088e58.png)

upon checking on html, the input has invalid class but the label does not have an "::after" tags in it. that is why i don't have way to check if it is hidden or not. though the label has data-error attribute.

![image](https://user-images.githubusercontent.com/35474475/47633675-c5c7ac80-db89-11e8-9ca0-ab5c0ca17fb7.png)

third, this is preview of the input after i click on it. the helper text do the transition same thing the label does that goes from down to up and then displays the helper text.

![image](https://user-images.githubusercontent.com/35474475/47633577-6073bb80-db89-11e8-90c1-c0a003b46ce8.png)

**Comment by alextrastero** [comment]
Closing, let me know if this is not clear yet
