### ISSUE TITLE
Text input state not changed to active with zero as default value

### ISSUE THREAD

**Issue by geoff-wasilwa** [react-materialize/react-materialize#688]
### Description

Creating a text input with a default value of zero displays an overlapped value and label. This is because the `active` class is only set for truthy values.

### Steps to Reproduce

`<Input label="Anchor Last" value={0} />`

**Expected behavior:**
<img width="337" alt="screenshot 2018-10-31 at 23 08 01" src="https://user-images.githubusercontent.com/6013054/47815609-daf73380-dd61-11e8-9152-e8443b2dd450.png">

**Actual behavior:**
<img width="337" alt="screenshot 2018-10-31 at 23 05 57" src="https://user-images.githubusercontent.com/6013054/47815576-c4e97300-dd61-11e8-9ed6-133b5aaa532d.png">

### Versions

**react-materialize:** 2.4.5
**materialize-css:** 0.100.2
**react:** 16.5.1

**Comment by alextrastero** [comment]
You might also be getting a `PropTypes` warning. `value` should be either an array or a string. Can you convert to string before assigning to `value`?
