### ISSUE TITLE
SideNav Trigger on another Component not working properly

### ISSUE THREAD

**Issue by jhe01** [react-materialize/react-materialize#691]
### Description
Hello, 

I have 2 components, a Header and Aside component. My Sidebar are on the Aside component but the trigger was on the Header component.

The problem is, I can't trigger my SideNav to open using my trigger on Header component. But if i put a trigger props on SideNav, and click the trigger on Header component it is opening though i can't close it and Whenever i click the created trigger via trigger props, it works well.

### Versions

react-materialize: ^2.4.7
materialize-css: 0.100.2
react: ^16.5.2

Thanks in advance!

**Comment by jhe01** [comment]
@alextrastero 

Sorry for late reply alextrastero,

here is my Header Component

![image](https://user-images.githubusercontent.com/35474475/48926584-6d769700-ef0a-11e8-8f73-a4b4a8124327.png)

and  here is my Aside Component

![image](https://user-images.githubusercontent.com/35474475/48926676-06a5ad80-ef0b-11e8-94f7-80e07bc58338.png)


As you can see i have my trigger on header.

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
