### ISSUE TITLE
Remove tooltip when navigating to another page

### ISSUE THREAD

**Issue by geoff-wasilwa** [react-materialize/react-materialize#692]
### Description

Clicking a Button with a tooltip that navigates to another page displays the tool on the next page.

**Expected behavior:** The tooltip should be removed

**Actual behavior:** Tooltip is still rendered on new page

### Versions

**react-materialize:** 2.4.5
**materialize-css:** 0.100.2
**react:** 16.5.1

**Comment by geoff-wasilwa** [comment]
@alextrastero what about calling `close` or `destroy` when the tool-tipped button is unmounted?

**Comment by alextrastero** [comment]
Absolutely, would you like to give it a go?

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
