### ISSUE TITLE
Wrong versioning on Changelog

### ISSUE THREAD

**Issue by Willibaur** [react-materialize/react-materialize#693]
### Description

Hi all, I think there is an error within the [Changelog](https://github.com/react-materialize/react-materialize/blob/master/CHANGELOG.md) weather we jump from `2.4.5` to `2.5.6` instead of `2.4.6`.

I'm happy to upload a PR with the change if I'm correct.

![image](https://user-images.githubusercontent.com/12820932/48713039-44eb5600-ec07-11e8-95f8-9f1aa41803fb.png)

**Comment by alextrastero** [comment]
Absolutely right, I was waiting for the next version to fix it, will do now
