### ISSUE TITLE
Nothing works with rect-router

### ISSUE THREAD

**Issue by nazarposhta** [react-materialize/react-materialize#70]
Do you know that nothing works when someone want to use react-router and tries to navigate on the site by 
`<Link to="/some-link"></Link>`
Plugins (Tabs) or something was not initialized 
We are making the single page application - actually. But it's not possible with that package.

**Comment by nazarposhta** [comment]
I resolved that with 
``componentDidMount(){
        $('ul.tabs').tabs();
    },
``

**Comment by rulatir** [comment]
Please fix this. The workaround suggested by the OP is not feasible in a nontrivial app. Also other components are failing too (Dropdown!)

**Comment by alextrastero** [comment]
Hey @nazarposhta please reopen this issue if it remains, thanks!
