### ISSUE TITLE
Adding the possibility to autoplay and stop/start the Carousel

### ISSUE THREAD

**Issue by CloudPower97** [react-materialize/react-materialize#703]
Hey there,
what about adding the possibility to autoplat and start/stop the carousel on hover?

It's as simple as adding a `setInterval` for the autoplay, `mouseenter` and `mouseleave` listener on `componentDidMount` for the `hovering` case and clean everything up on `componentWillUnmount`.

Of course start/stop is only one of the possibility you can achieve adding these kind of event listener.

This is just one of the use case I needed to cover when working with the slider.

I already have implemented this in a project of mine, just wanted to know if you would like me to open a PR for that.

Let me know :smile:

**Comment by alextrastero** [comment]
Thanks @CloudPower97 for the suggestion, although we want to keep this library just as a wrapper for `materializecss`, adding extra features is not the task of this library. Could that be a feature suggestion for them?
