### ISSUE TITLE
CardPanel always gets teal class

### ISSUE THREAD

**Issue by rulatir** [react-materialize/react-materialize#71]
CardPanel always gets `teal` class. The result is that the teal color cannot be overriden by any other color class that is defined earlier in materialize.css, e.g. it can be overriden by `deep-orange` but cannot be overriden by `red`.

Since both selectors match with the same specificity and both rulesets come from the same source, actual ordering of rules in the stylesheet comes into play and the last one wins.

You should actually parse the `className` prop and only add `teal` if no other color class is found.

**Comment by alextrastero** [comment]
Hey @rulatir, thanks for all this input 👍 
Could you show us some sample code, i'm trying to reproduce as such:
```JS
      <CardPanel className={'red'}>
        <p>Hey there</p>
      </CardPanel>
```
And it seems to work fine.

**Comment by rulatir** [comment]
What does your code render as in your app?

In my app it renders as `<div class="card-panel teal red"><span class="white-text"><p>Hey there</p></span></div>` and the div.card-panel is teal.

**Comment by rulatir** [comment]
Hmm, I had something weird installed as 'react-materialize' - it reported itself as 0.14.3 but the code was different, and the CardPanel component actually contained this code:

```
  const classes = {
    'card-panel': true,
    'teal': true
  };
```

I removed and reinstalled and it's OK now.
