### ISSUE TITLE
3.0.0 Storybook stories

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#718]
### Create stories for components for documentation

- [x] BadgesPage
- [x] BreadcrumbsPage
- [x] ButtonsPage
- [x] CardsPage
- [x] CarouselPage
- [x] ChipsPage
- [x] CollapsiblesPage
- [x] CollectionsPage
- [x] DropdownPage
- [x] FooterPage
- [x] FormsPage
- [ ] GettingStartedPage (aka introduction)
- [x] GridPage
- [x] IconsPage
- [ ] MediaPage
- [x] ModalsPage
- [ ] NavbarPage
- [ ] PageFooter
- [x] PaginationPage
- [ ] ParallaxPage
- [ ] PreloaderPage
- [x] Range
- [ ] SideNavPage
- [x] TablesPage
- [x] TabsPage
- [x] ToastPage

**Comment by mccraveiro** [comment]
Will the `/examples` directory be removed after all stories are written?

**Comment by alextrastero** [comment]
I think so yes

**Comment by onluiz** [comment]
Implemeting * ModalsPage stories :)

**Comment by onluiz** [comment]
The GettingStartedPage will have same content as https://react-materialize.github.io/#/ currently has?

**Comment by alextrastero** [comment]
Hey @onluiz I already started working on a welcome page that should include the documentation to get started :) sry

**Comment by onluiz** [comment]
That's fine :) I will work on * MediaPage then

**Comment by onluiz** [comment]
@alextrastero, opened a pr for Media page!
Is it ok if I start * NavbarPage?

:)

**Comment by alextrastero** [comment]
Sure! @onluiz

**Comment by onluiz** [comment]
Opened a pr for Navbar! 
@alextrastero, is it ok if I start * PageFooter?

**Comment by onluiz** [comment]
Implementing ParallaxPage :)

**Comment by iSarCasm** [comment]
@alextrastero do you need help with any?

**Comment by alextrastero** [comment]
Sorry for the delay, i've been really busy with personal stuff, @onluiz how are we doing? I'll pick up the `getting started page` ASAP cheers

**Comment by onluiz** [comment]
Hi @alextrastero, I am having some problems with SideNav stories, but besides this one I think we're doing fine :)

**Comment by onluiz** [comment]
@alextrastero, added Tabs stories :smile:

**Comment by alextrastero** [comment]
I think we are done here @onluiz, I published 3.0.0. Thanks to you and all other contributors 👍 

Next steps are:
- reduce bundle (ability to import only 1 component)
- complete all stories
