### ISSUE TITLE
3.0.0 Autocomplete with Icon

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#726]
Autocomplete needs a story with Icon, also can we remove `iconClassnames` prop and only pass `material-icons prefix`?

**Comment by mccraveiro** [comment]
As it is, It seems that the icon is breaking the layout. I will investigate further.

<img width="570" alt="screen shot 2018-12-16 at 11 37 17 pm" src="https://user-images.githubusercontent.com/782333/50061994-90a00980-018b-11e9-9063-2cb80f321d53.png">

**Comment by mccraveiro** [comment]
Oh! I had forgotten to pass the class name 😂

**Comment by alextrastero** [comment]
thx
