### ISSUE TITLE
False positive test at Button.spec.js

### ISSUE THREAD

**Issue by onluiz** [react-materialize/react-materialize#738]
### Description
Playing with Button component, a found out that there is 2 tests (fab hover and fab click) that are always positive. At first that would be fine :P but even when I force test conditions to fail, it does't, causing a false positive.

### Steps to Reproduce

1. Run tests
2. Verify that https://github.com/react-materialize/react-materialize/blob/master/test/Button.spec.js#L44 and https://github.com/react-materialize/react-materialize/blob/master/test/Button.spec.js#L50 will always pass

**Expected behavior:** [What you expect to happen]
- Test should fail when the given condition is no more respected

**Actual behavior:** [What actually happens]
- Even if tests condition is not respected, tests will pass, causing the impression that the component is final when there is a chance that it is broken

### Versions

**react-materialize:** v2.4.6 and 1.0.0-beta.0

**Comment by alextrastero** [comment]
Is there something I can assist with here?

**Comment by alextrastero** [comment]
Aha, the issue is that the assertion in the test is not happening, you need to add `toHaveLength(1)` for example

**Comment by onluiz** [comment]
I tried that, but then test always fail, and the component is working fine.
It seems that the way we are simulating `hover` and `click` might not be the best for this situation.

```
wrapper = shallow(<Button fab="vertical">Stuff</Button>);
wrapper.simulate('hover');
expect(wrapper.find('.fixed-action-btn active')).toHaveLength(1);
```

The assert can't find `fixed-action-btn active` after `wrapper.simulate('hover');`.

I will be searching more about this to see if I can come up with some ideia and open a PR :)

**Comment by alextrastero** [comment]
True, the hover simulation might not be working

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
