### ISSUE TITLE
parallax component use zoomed in picture? 

### ISSUE THREAD

**Issue by dellwatson** [react-materialize/react-materialize#743]
**Expected behavior:** 
expecting the parallax component could be modify, because right now the image always zoomed in which not the one i wanted to.

or could be modify together with className="responsive-img"

**Comment by alextrastero** [comment]
Hey @dellwatson, can you give us some more input? What feature from materialize-css would you expect this parallax component to have? thx :)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
