### ISSUE TITLE
Alternative Approach

### ISSUE THREAD

**Issue by mattlockyer** [react-materialize/react-materialize#744]
### Description

I've come up with an alternative to your library, which I think is pretty great btw. Thanks for all the hard work.

Since there are several issues with being in sync with the materializecss releases and component issues, happens to the best of us, I decided to use materialize directly but instead import custom components on top of a core bundle.

I wrote about this approach here, hope someone finds it useful.

https://medium.com/@mattdlockyer/youre-using-materialize-css-wrong-470b593e78e9

**Comment by alextrastero** [comment]
Hey @mattlockyer, nice article and a valid approach. Question though, since you imported `materialize.min.js` in your `index.html`, would that not mean that you it can't be optimized with webpack?

**Comment by mattlockyer** [comment]
Good question. I actually created a custom build of `materialize.min.js` that includes only the core files to get each individually imported component running. So the file I've included is much smaller than the original `dist/materialize.min.js`. Hope this helps.

**Comment by alextrastero** [comment]
Ah I see, how do you keep in sync with materialize-css if so?

**Comment by mattlockyer** [comment]
So materialize-css is pulled in live from my bundler. Need more components, just uncomment the materialize.scss imports and they will be loaded by the bundler.

If materialize releases a new JS version, you will have to recompile the minified js, but it's only one command line.

There's a link to the custom grunt file in the post as well!
