### ISSUE TITLE
Parallax Image too Large

### ISSUE THREAD

**Issue by DaleP1988** [react-materialize/react-materialize#754]
### Parallax Image too Large

Trying to use a free Pexels image on my site. When used with React-Parallax, the image turns out to be large and distorted. For most of the images I tried, the result didn't even compare to the original image. How can I scale the image to both accommodate the parallax and display completely?

### Sample Code

import React, { Component } from "react";
import { Col, Row, Container } from "../components/Grid";
import { Parallax } from "react-materialize";
// import { ParallaxBanner } from "react-scroll-parallax";
import background from "../images/cooltile.jpg";
import vr from "../images/computerFace.jpg";
// import tile from "../images/pinktile.jpg";
import Nav from "../components/Nav";
import { Link } from "react-router-dom";
import "../components/Enter/Enter.css";

class Enter extends Component {
  render() {
    return (
      <div>
        <Parallax imageSrc={background} style={{}} />

        <div className="section white">
          <div className="row container">
            <h2 className="header">Parallax</h2>
            <p className="grey-text text-darken-3 lighten-3">
              Web Designer and Developer
            </p>
            <Link to="/about">
              {" "}
              <a className="waves-effect waves-light btn-small">
                Enter Site
              </a>{" "}
            </Link>
          </div>
        </div>

        <Parallax imageSrc={vr} id="vr" />
      </div>
    );
  }
}

export default Enter;

**Expected behavior:** [What you expect to happen]

I would like to see both images scaled down by about 50% (as they appear on the Pexels site)

**Actual behavior:** [What actually happens]

All that I see are blown up tiles (in the first image) and teeth (in the bottom image).

### Versions

**react-materialize:** 2.4.8
**materialize-css:**
**react:** 16.0.0

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
