### ISSUE TITLE
Input not rendering

### ISSUE THREAD

**Issue by sepanaho** [react-materialize/react-materialize#756]
### Description

I can't get check-boxes and radio-sets to render.

I am new to this so please excuse me if I am missing something obvious.

### Steps to Reproduce

```
<Row>
    <Input s={12} label='Text' />
    <Input s={12} type='file' label='File' />
    <Input s={12} type='checkbox' name='filter' value='camping' label='Camping' defaultValue='checked' />
    <Input s={12} name='group1' type='radio' value='red' label='Red' />
    <Input s={12} name='group1' type='radio' value='yellow' label='Yellow' />
    <Input s={12} name='group1' type='radio' value='green' label='Green' className='with-gap' />
    <Input s={12} name='group1' type='radio' value='brown' label='Brown' />
    <Input s={12} name='on' type='switch' value='on' />
</Row>
```

**Expected behavior:** 
I would have expected check-boxes and radio-sets to render in the same fashion as text and file inputs.

**Actual behavior:** 
The check-box and radio-set does not render. Please see attached screenshot.
![renderfail](https://user-images.githubusercontent.com/9158531/52367839-da351280-2ab1-11e9-8237-498cde7beeff.PNG)
 

### Versions

**react-materialize:** 2.6.0
**materialize-css:** 1.0.0
**react:** 16.7.0

**Comment by alextrastero** [comment]
At this moment we don't support the latest version of materialize-css, we have a milestone react-materialize@3.0.0-beta which is nearly ready. Please feel free to help out https://github.com/react-materialize/react-materialize/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22
