### ISSUE TITLE
Collection does not put my data attribute into UL

### ISSUE THREAD

**Issue by miku86** [react-materialize/react-materialize#757]
Hey folks,
thanks for reading :)

### Description

`<Collection />` does not use my custom data attribute.

### Steps to Reproduce

1. Create a Collection: 
```
<Collection data-testid="my-custom-list">
    <CollectionItem>My Item</CollectionItem>
</Collection>
```

2. Look at the HTML code in Dev Tools:
```
<ul class="collection">
    <li class="collection-item">My Item</li>
</ul>
```

**Expected behavior:**
I expect, that `data-testid="my-custom-list"` is also in the HTML code.
For other elements like `<Button />` and `<Input />` it works.

**Actual behavior:**
The data-attribute `data-testid="my-custom-list"`is not in the HTML code.

### Versions

**react-materialize:** 2.6.0
**materialize-css:** 0.100.2
**react:** 16.8.1

**Comment by onluiz** [comment]
@alextrastero, can I fix this one? =)

**Comment by alextrastero** [comment]
Sure! We're also really close to finishing `3.0.0` all we need are some extra storybook stories if you're interested :)

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
