### ISSUE TITLE
TextInput onChange callback issue

### ISSUE THREAD

**Issue by mrerichoffman** [react-materialize/react-materialize#758]
### Description

The TextInput component does not pass through the onChange callback. This is on the 3.0 beta branch.

### Steps to Reproduce

`<TextInput type='email' id='email' label='Email' value={this.state.email} onChange={this.handleChange} />`

handleChange callback function does not pass through to the input html element - looks like a simple fix is needed to update the function binding from this to props inside TextInput.

**Expected behavior:** Callback to get executed.

**Actual behavior:** No callback

### Versions

**react-materialize:** 3.0.0
**materialize-css:** 1.0.0
**react:** 16.4.1

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
