### ISSUE TITLE
TimePicker does not work in 3.0

### ISSUE THREAD

**Issue by mrerichoffman** [react-materialize/react-materialize#759]
### Description

TimePicker does not import on the 3.0 beta branch.

### Steps to Reproduce

`import { TimePicker } from 'react-materialize';`

Looks like index.js is missing `import TimePicker from './TimePicker';`

This component is also affected by the onChange callback issue in TextInput. Side note, it would be nice to get the time picker instance from outside this component to access all of the time instance variables like amOrPm, hours, and minutes - so we don't have to parse the time value.

**Expected behavior:** Import to resolve

**Actual behavior:** Import does not resolve

### Versions

**react-materialize:** 3.0.0
**materialize-css:** 1.0.0
**react:** 16.4.1

**Comment by alextrastero** [comment]
Thanks for catching this! simple fix will solve ASAP

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
