### ISSUE TITLE
Chips with "close" prop is broken in 3.0.0

### ISSUE THREAD

**Issue by iSarCasm** [react-materialize/react-materialize#769]
### Description

Chips with "close" prop missing actual "close" class.

### Steps to Reproduce

1. Create a Chip with close prop
2. Code example from story:
```jsx
stories.add('with close', () => (
  <Chip close>Jane Doe</Chip>
));
```

**Expected behavior:** Proper styles for close icon
![image](https://user-images.githubusercontent.com/1886857/54082818-c59fa080-4323-11e9-9d9b-57c5bdc0525e.png)
![image](https://user-images.githubusercontent.com/1886857/54082822-d05a3580-4323-11e9-9007-36df3a2d07c3.png)

**Actual behavior:** Wrong style because of missing "close" class on <i>
![image](https://user-images.githubusercontent.com/1886857/54082781-7e191480-4323-11e9-9103-a90e65bc78a6.png)
![image](https://user-images.githubusercontent.com/1886857/54082811-b7518480-4323-11e9-9b36-3dde5a4011c1.png)

### Versions

**react-materialize:** 3.0.0-beta.0
**materialize-css:** 1.0.0
**react:** 16.8

**Comment by alextrastero** [comment]
Fixed
