### ISSUE TITLE
message.trim is not a function

### ISSUE THREAD

**Issue by prdx** [react-materialize/react-materialize#77]
Hi,

I am trying to run your `docs` by running these commands:

```
npm run build
npm run start
```

However I got error `message.trim is not a function` TypeError in `dev.js` while running `npm run start`. Is 
there a way to fix that?

Thanks!

**Comment by alextrastero** [comment]
Hey @prdx, the documentation is in the react-materialize/react-materialize repo. You need to go to the docs folder, npm install and npm start. Assets are served from 8080 and you can see the docs at localhost:4000

**Comment by prdx** [comment]
Hi @alextrastero, I did that, but I am still getting the error. Here is the stacktrace:

```
/mnt/data/Projects/react-materialize/docs/dev.js:13
  var formattedMessage = message.trim().split('\n').reduce(function (acc, line) {
                                 ^

TypeError: message.trim is not a function
    at output (dev.js:13:34)
    at Socket.<anonymous> (dev.js:24:29)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
```

**Comment by isaiah** [comment]
@prdx Maybe your `nodejs` version is too low.

**Comment by isaiah** [comment]
@prdx lol, I also have the same problem, checking.
