### ISSUE TITLE
NavItem should have a prop to specify which element we want render other than the <a> tag

### ISSUE THREAD

**Issue by ropali** [react-materialize/react-materialize#778]
### Description

NavItem should have a prop to specify which element we want render other than the anchor tag so that it can be used with reeact-router Link tag

**Expected behavior:** Able to change the underlying anchor tag to any other tag

**Actual behavior:** Always renders the anchor tag

### Versions

**react-materialize:** 2.6.0
**materialize-css:**0.98.0
**react:** 16.8.4

**Comment by alextrastero** [comment]
Why not use like so?

```jsx
<Navbar>
  <Link to="foo">Getting started</Link>
</Navbar>
```

**Comment by ropali** [comment]
Yeah, I tried that already but it breaks the UI. See the attached screenshot.
![Short Link](https://user-images.githubusercontent.com/31515245/54881651-0943ef80-4e78-11e9-8458-f88adbc5af7e.png)

**Comment by onluiz** [comment]
@alextrastero, need some help on this one?

**Comment by alextrastero** [comment]
@ropali depending on how big your project is, could you try using `react-materialize@3.x` and seeing if this is still an issue?

**Comment by alextrastero** [comment]
Even if you try to fix this @onluiz, @ropali would need to test the mayor update first :)

**Comment by ropali** [comment]
> @ropali depending on how big your project is, could you try using `react-materialize@3.x` and seeing if this is still an issue?

I am just doing a toy project, not a big deal. I will try  `react-materialize@3.x` .

**Comment by onluiz** [comment]
Ok :)

**Comment by alextrastero** [comment]
Any luck @ropali? I'm going to close, please reopen if this issue remains, thx
