### ISSUE TITLE
Can't Make TextInput Controlled

### ISSUE THREAD

**Issue by MSharifi78** [react-materialize/react-materialize#792]
### Description

I passed *value* prop to **TextInput** in order to reset it's value.
but the *value* prop gets passed as *defaultValue* to **input** tag

### Steps to Reproduce

1. render a **TextInput**
2. pass *value* prop to **TextInput** and set it's value to a state
3. change state's value

**Expected behavior:** *TextInput* value should change

**Actual behavior:** *TextInput* value doesn't change

### Versions

**react-materialize:** 3.0.3
**materialize-css:** ^1.0.0
**react:** 16.8.4

**Comment by alextrastero** [comment]
Hey @MSharifi78, this works for me:

```jsx
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '123'
    }
  }

  render() {
    return (
      <div className="App">
        <TextInput value={this.state.value}/>
      </div>
    );
  }
}
```

```html
<div class="App">
  <div class="input-field col">
    <input class="" type="text" id="0" value="123">
  </div>
</div>
```

**Comment by MSharifi78** [comment]
According to this [line](https://github.com/react-materialize/react-materialize/blob/master/src/TextInput.js#L79), no value prop has passed to the inner input tag.

take a look at this example:
https://codesandbox.io/s/xj74z0x51q

**Comment by alextrastero** [comment]
What are you trying to achieve? As far as I know a controlled input is one which can receive a value via props. In your example, I can type something in the input field and it's getting populated via state.
![Screen Shot 2019-03-29 at 2 38 43 PM](https://user-images.githubusercontent.com/4152819/55236527-6e109880-5230-11e9-9b3a-93d8d733a51f.png)

**Comment by alextrastero** [comment]
I've figured out your issue, i'm looking into it @MSharifi78

**Comment by MSharifi78** [comment]
Thank you,
I open a PR if you want take a look at it😉

**Comment by CloudPower97** [comment]
@alextrastero I'm having the same issue. 
I can confirm that @MSharifi78 P.R fixes this.
His build is failing just because of `prettier`.
ATM I had to copy&paste his changes into my codebase in order to make things works right.

**Comment by masonjwhite** [comment]
Hey @alextrastero! Any update on merging of @MSharifi78's most recent pull request? This is a major breaking change in one of the corporate applications I support. Thanks so much!

**Comment by alextrastero** [comment]
`3.2.0` :)

**Comment by masonjwhite** [comment]
Thanks Alex! Appreciate the quick response!
