### ISSUE TITLE
Add action on icon in TextInput

### ISSUE THREAD

**Issue by LucaProgrammer** [react-materialize/react-materialize#793]
Good morning,
first of all i want to congratulate with you for you're gr reat work.

### Description

I have a question about icon in TextInput component.
I want to add an action on that icon, but ther'isn't a prop that allows it to me. 

How can i do?

#### Thanks for helping out!

**Comment by alextrastero** [comment]
Hey @LucaProgrammer, could you please add an example of what you are trying to achieve?

A `TextInput` can contain an icon, like materializecss https://materializecss.com/text-inputs.html

**Comment by LucaProgrammer** [comment]
@alextrastero Yhea,
I want to add a "close" icon, and when I click it, the input should be emptied.

**Comment by alextrastero** [comment]
Proposed solution would be for `icon` prop to also allow a node, then you could attach the click handler to this node.

**Comment by CloudPower97** [comment]
@alextrastero The proposed solution would also allow us to use _Material Design Icons_ or any other custom Icon, as discussed in #674
