### ISSUE TITLE
Old Documentation

### ISSUE THREAD

**Issue by jamesmart77** [react-materialize/react-materialize#796]
### Is v2.6.0 Gone?

Our team really enjoys using this library. We are in the middle of building an application on v2.6.0 but can't find any of the old version documentation. Is only v3.0.0 documentation available now?

If so, is there any way to make the old documentation available again? To not have that all of a sudden is going to cause a lot of rework for your users :(

Thanks for all your work!

**Comment by onluiz** [comment]
As a temporary solution I deployed old docs here: https://onluiz.github.io/react-materialize-docs/index.html#/

**Comment by alextrastero** [comment]
Thanks @onluiz!

@jamesmart77 `materialize-css` still has access to the old docs and this library is just a wrapper, so all the info you need is either in the `propTypes` of each component or in the `materialize-css` docs. Sorry for any inconvenience we might of caused :)
