### ISSUE TITLE
Collapsible's accordion and popout does not work

### ISSUE THREAD

**Issue by evgenosiptsov** [react-materialize/react-materialize#80]
HI!

`<Collapsible popout={true} accordion={true} onSelect={this.props.onSelect}>
            {this.props.sections.map(function(section) {
                return (
                    <CollapsibleItem header={this.props.renderHeader(section)}>
                        {this.props.renderContent(section)}
                    </CollapsibleItem>)
            }.bind(this))}          
            </Collapsible>`   
- With popout=true active li does not have 'active' className
- With accordion=true selected items doest not explained

Check please collapsible component, there is enought of bugs.

**Comment by EGedeon** [comment]
https://github.com/react-materialize/react-materialize/pull/81

**Comment by yanickrochon** [comment]
This component is broken, this is why it is not working. For example, the materialize example shows that the following HTML markup

```html
<ul class="collapsible popout" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
    <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
  </li>
</ul>
```

Should render as

![selection_101](https://cloud.githubusercontent.com/assets/78461/19970042/2954626c-a1b1-11e6-84fe-816d681f4db7.png)

with this DOM structure

![selection_104](https://cloud.githubusercontent.com/assets/78461/19970125/77a8299e-a1b1-11e6-913f-9da6698e5eec.png)

However, the JSX markup

```jsx
<Collapsible popout>
  <CollapsibleItem header='First' icon='filter_drama'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Second' icon='place'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
  <CollapsibleItem header='Third' icon='whatshot'>
    Lorem ipsum dolor sit amet.
  </CollapsibleItem>
</Collapsible>
```

despite rendering the same visual, has this DOM structure

![selection_102](https://cloud.githubusercontent.com/assets/78461/19970060/37951c18-a1b1-11e6-886e-cca9618e1451.png)

Thus breaks the component's animation on reveal.

**Comment by yanickrochon** [comment]
See PR #165

**Comment by reesmanp** [comment]
This issue still exists. I am on version 0.17.6 and clicking on my collapsible item does nothing. 

Why does each collapsible item have their own state? The state should be managed by the parent, be it collapsible or something else. If I remove the state from collapsible item and change it purely to props, then everything works just as expected.

**Comment by reesmanp** [comment]
This might be fixed via #189

**Comment by alextrastero** [comment]
not fixed yet :)

**Comment by tamitutor** [comment]
yep, still broken

**Comment by cullanrocks** [comment]
Im having the same issue. It works if I refresh the page, but not on initial render.

**Comment by alextrastero** [comment]
Ok, going to have a look at this

**Comment by mattBlackDesign** [comment]
@alextrastero how is the progress on #286? 

I have just created PR #321 which addresses @yanickrochon comment about HTML rendering matching Materialize docs. It does not address collapsible item states.
