### ISSUE TITLE
Problem using react-materialize with typescript

### ISSUE THREAD

**Issue by Rober19** [react-materialize/react-materialize#801]
### Description

Problem using react-materialize with typescript

### Steps to Reproduce

it's produced when I import it.
![image](https://user-images.githubusercontent.com/28882108/55391994-098b5d00-5500-11e9-88ba-b97c4691142a.png)

**Expected behavior:** Let me import

**Actual behavior:** Error in Image

### Versions

**react-materialize:** 3.0.3
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by alextrastero** [comment]
Is this a bug for this project? Seems not, can you give us more info?

**Comment by Rober19** [comment]
Don't worry, I solved using `  const { Modal } = require('react-materialize');`
**This is only feedback**

**Comment by alextrastero** [comment]
Ah cool, thanks
