### ISSUE TITLE
Select does not put my data attribute into UL

### ISSUE THREAD

**Issue by uiktiomasfeliz** [react-materialize/react-materialize#811]
### Description

The Select component does not work correctly with dynamic data.

![image](https://user-images.githubusercontent.com/5663564/55538689-4e112700-56bf-11e9-82e0-06fed856612c.png)

### Versions

**react-materialize:** 3.0.3
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by alextrastero** [comment]
Thanks for this, can you paste a code sample for me to test?

**Comment by uiktiomasfeliz** [comment]
> Thanks for this, can you paste a code sample for me to test?


Here is an example similar to what I have in the project: [https://repl.it/repls/CostlyDishonestLanguage](https://repl.it/repls/CostlyDishonestLanguage)

**Comment by CloudPower97** [comment]
@uiktiomasfeliz This should be fixed with `3.1.0`

**Comment by alextrastero** [comment]
Closing, please let us know if it's not fixed :)

**Comment by uiktiomasfeliz** [comment]
Hello, sorry for the delay, I updated to the latest version and the bug has not been solved, I leave the link of the demo: [https://repl.it/repls/PossibleRadiantTrace](https://repl.it/repls/PossibleRadiantTrace)

**Comment by CloudPower97** [comment]
@uiktiomasfeliz You are right, #822 has not been merged as of now.
I'll work on it ASAP, hopefully it will be merged in the next release.
Thanks for the feedback. :blush:
