### ISSUE TITLE
dismissible flag for Modals doesn't seem to work

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#819]
From gitter chat

**Comment by CloudPower97** [comment]
@alextrastero can't reproduce the bug
[![Edit zq85km4zw3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zq85km4zw3?fontsize=14)

**Comment by alextrastero** [comment]
True, this works fine, thanks for checking :)
