### ISSUE TITLE
Select / Deselect Checkboxes Not Updating In React

### ISSUE THREAD

**Issue by jamesmart77** [react-materialize/react-materialize#823]
### Select / Deselect Checkboxes Not Updating In React

We have a React component that lists checkboxes with user names. At the top of the list is a Select and Deselect All button. We have validated that our Redux store is updating and returning the appropriate props to the component so it should re-render the checkbox list either selected or deselected accordingly. The issue though is that each checkbox does not update, but remains its initial value.

### Steps to Reproduce

1. Create a React Application using Create-React-App
2. Map through an array of users and rendering the React-Materialize Checkbox component with the 'checked' parameter dynamic based on the users.isChecked value

**Expected behavior:** All checkboxes should be selected or deselected upon the click action of the corresponding button.

**Actual behavior:** Each checkbox does not update, but remains its initial value.

### Versions

**react-materialize:** 3.0.5
**materialize-css:** 1.0.0
**react:** 16.8.2

### Screenshot
![image](https://user-images.githubusercontent.com/29242164/56145780-ebe3dc00-5f72-11e9-8c3a-2fe8391423a2.png)

**Comment by CloudPower97** [comment]
@jamesmart77 This should be fixed in version `3.1.0`

**Comment by jamesmart77** [comment]
@CloudPower97 
Excited to try out this fix, but looks like there's an import directory reference error in src/Navbar.js

Please change line 5 in src/Navbar.js to `import TextInput from './TextInput';` I tried to submit a pull request but received a 403 on the branch push.

The problem seems to be that in the npm package the lib/Navbar.js file is pointing to a non-existent src directory. 

Line 16 in lib/Navbar.js of the npm v3.1.0 is where the problem is...
`var _TextInput = _interopRequireDefault(require("../src/TextInput"));`

**Comment by CloudPower97** [comment]
@jamesmart77 Yep. Noticed this error earlier today; I already have a branch ready for that.
Thank you for reporting this.

Anyway, to avoid `403` have a look [here](https://github.com/react-materialize/react-materialize/blob/master/.github/CONTRIBUTING.md)
