### ISSUE TITLE
i am facing issue in spfx webpart with react-bootstrap

### ISSUE THREAD

**Issue by TusharFork** [react-materialize/react-materialize#826]
### Description

[Description of the issue]

### Steps to Reproduce

1. Create spfx webpart
2. npm install react-bootstrap
3. gulp serve

### Versions
This is my package.json file
{
  "name": "employee-exit-process",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/rush-stack-compiler-3.0": "^0.6.7",
    "@microsoft/sp-core-library": "1.8.0",
    "@microsoft/sp-lodash-subset": "1.8.0",
    "@microsoft/sp-office-ui-fabric-core": "1.8.0",
    "@microsoft/sp-property-pane": "1.8.0",
    "@microsoft/sp-webpart-base": "1.8.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "bootstrap": "^4.3.1",
    "react": "16.7.0",
    "react-bootstrap": "^1.0.0-beta.8",
    "react-dom": "16.7.0",
    "typescript": "^3.1.6"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.0",
    "@microsoft/sp-tslint-rules": "1.8.0",
    "@microsoft/sp-module-interfaces": "1.8.0",
    "@microsoft/sp-webpart-workbench": "1.8.0",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

![2019-04-16_11-11-12](https://user-images.githubusercontent.com/44160541/56185325-ce7a4500-603a-11e9-852b-949720748ab1.png)

**Comment by CloudPower97** [comment]
Hey, @TusharFork , I do not see how we can help you here.
It seems you are not even using `react-materialize`.

**Comment by alextrastero** [comment]
Closing for now, reopen if this issue is related to this project :)
