### ISSUE TITLE
Modal with custom buttons in footer?

### ISSUE THREAD

**Issue by rulatir** [react-materialize/react-materialize#83]
How can I specify custom buttons with callbacks (e.g. "Yes, delete", "NO, KEEP IT!!!") in the modal footer?

**Comment by isaiah** [comment]
This feature is in `master` branch, but not yet released. Please see https://github.com/react-materialize/react-materialize/pull/79

**Comment by yanickrochon** [comment]
This is in the master branch, now. One must specify these using the `actions` props.

**Comment by Neotriz** [comment]
Can someone post an example of a modal component with customizable footer?

**Comment by yanickrochon** [comment]
```jsx
<Modal
  header={ i18n.__('layout.dialog.modal.delete.header') }
  ttrigger={
    <Button className="left red darken-2" waves='light'><i className="material-icons left">delete</i><span className="hide-on-small-only"><T>delete</T></span></Button>
  }
  actions={
    <div>
      <Button modal="close" waves="light" className="red darken-2" onClick={ this.deleteAction.bind(this) }><Icon left>delete</Icon><T>delete</T></Button>
      <Button flat modal="close" waves="light"><T>dismiss</T></Button>
    </div>
  }
>
  <p><T model={ this.props.modelName || 'model' }>layout.dialog.modal.delete.message</T></p>
</Modal>
```

As you can see, you can put whatever you want in the `actions` prop, just wrap your components/elements inside a root node, for example, in the case above, a `div`.

**Comment by Neotriz** [comment]
Thanks a bunch! How were you able to figure out, if you don't mind answering?

**Comment by yanickrochon** [comment]
I read the [source](https://github.com/react-materialize/react-materialize/blob/master/src/Modal.js#L77) :wink:
