### ISSUE TITLE
Select not updating dynamically

### ISSUE THREAD

**Issue by sboopal** [react-materialize/react-materialize#833]
### Description

Second select is not updating based on the first select. Using react-materialize component

### Steps to Reproduce

i have two selects in my form and when i change values in the first select it should automatically populate the inputs for my second select. I was able to achieve this but the problem is that my UI is not showing the new inputs for second select. When i inspect i see the select options to be the newly updated inputs but the UI is not displaying the same. 

Below is the code
/* eslint-disable*/
import React, { Component } from 'react';
import 'materialize-css/dist/js/materialize.min.js'
import 'materialize-css/dist/css/materialize.min.css'
import M from "materialize-css";

const vendorNodes = [
    {
        id:1,  
        name: 'Bay', 
        nodeNames: ['TDMAR', 'HBCGCD','HSBCRD']
    },
    {
        id:2,
        name: 'Saks', 
        nodeNames: ['CAPEMV', 'CSMLNK','FEPTKM','HSBCRD','PTAHUE','SMTCLX','TOKENEX','VTPDCR']
    },
    {
        id:3,
        name: 'LT', 
        nodeNames: ['PTACRD', 'LNTGCD','HSBCRD','FEPTKM','SMTCLX','TOKENEX','VTPDCR','INCISO']
    }
]

class BannerReport extends Component {

    state = {
        selectedBanner : 'Saks',
        selectedStoreType:'',
        selectedVendor:'',
        selectedTranStatus:'',
        startDate:'',
        endDate:''
    }

    componentDidMount() {
        console.log(M);
        M.AutoInit();
    }

    handleChangeBanner = (e) => {
        this.setState({ selectedBanner : e.target.value })
    }

      render(){
    
        const getVendor = () => {
            const nodes = vendorNodes.filter((vendorNode) => vendorNode.name === this.state.selectedBanner)[0];
            return(
                <select onChange={this.handleChangeVendor}>
                    {nodes.nodeNames.map(m => <option>{m}</option>)}
                </select>
            )
        }

        return(
            <div className="container">
                <div className="row">
                    <form className="col s12">
                        <div className="row">
                            <h6 className="col s12 m2">Banner</h6>
                            <div className="input-field col s12 m3">
                                <select 
                                    name="bannerDropDown"
                                    onChange={this.handleChangeBanner} >
                                        {vendorNodes.map((vendorNode) => <option key={vendorNode.id} value={vendorNode.name}>{vendorNode.name}</option> )}
                                </select>
                                <label>Banner</label>
                            </div>
                            <h6 className="col s12 m2 offset-m1">Store Type</h6>
                            <div className="input-field col s12 m3">
                                <select>
                                    <option value="" disabled selected>Select</option>
                                    <option value="Online">Saks.Com</option>
                                    <option value="Physical">Physical Store</option>
                                </select>
                                <label>Type</label>
                            </div>
                        </div>
                        <div className="row">
                            <h6 className="col s12 m2">Vendor</h6>
                            <div className="input-field col s12 m3">
                                {getVendor()}
                                <label>Vendor</label>
                            </div>
                            <h6 className="col s12 m2 offset-m1">Tran Status</h6>
                            <div className="input-field col s12 m3">
                                <select>
                                    <option value="" disabled selected>Select</option>
                                    <option value="Approved">Approved</option>
                                    <option value="Declined">Declined</option>
                                    <option value="Timeout">Timeout</option>
                                    <option value="Onhold">Onhold</option>
                                </select>
                                <label>Status</label>
                            </div>
                        </div>
                        <div className="row">
                            <h6 className="col s12 m2">Start Date</h6>
                            <div className="input-field col s6 m3">
                                <input type="text" className="datepicker" />
                            </div>
                            <div className="input-field col s6 m3">
                                <input type="text" className="timepicker" />
                            </div>
                        </div>
                        <div className="row">
                            <h6 className="col s12 m2">End Date</h6>
                            <div className="input-field col s6 m3">
                                <input type="text" className="datepicker" />
                            </div>
                            <div className="input-field col s6 m3">
                                <input type="text" className="timepicker" />
                            </div>
                        </div>
                        <button className="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i className="material-icons right">send</i>
                        </button>
                    </form>
                </div>
            </div>
        );
    }
}

export default BannerReport;

#### Thanks for helping out!

![Capture](https://user-images.githubusercontent.com/34709987/56313554-76197500-6118-11e9-8c32-171eb9203b54.PNG)

**Comment by CloudPower97** [comment]
Hey @sboopal , there was already #811 .
It's been fixed with #822 and released in version `3.1.0`
Anyway, DO NOT update just yet, as we have a problem that will be fixed soon with #832

**Comment by sboopal** [comment]
ok thanks for the update. Is my code looks good or any changes needed?

**Comment by alextrastero** [comment]
Closing for now, let me know if this is still an issue :)

**Comment by sboopal** [comment]
is the fix for this has been added?

**Comment by CloudPower97** [comment]
@sboopal It does indeed works from version 3.2.0 onwards.
I've created a simple sandbox so you can check it out yourself:
[![Edit 90j3mv74w](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/90j3mv74w?fontsize=14)

**Comment by sboopal** [comment]
@CloudPower97 it is not working with my project. when I select one of the dropdowns I need the other drop down to update based on the first one. as i have mentioned in the issue second drop down is updating but the UI is not showing the actual value rather it is showing the old values. but if we select the dropdown value will update to the correct one but the dropdown will still reflect old values

**Comment by CloudPower97** [comment]
@sboopal You are not even using `react-materialize`. Please check my example and the [docs](http://react-materialize.github.io/react-materialize/).
