### ISSUE TITLE
Not checking for existence of `M` correctly

### ISSUE THREAD

**Issue by JGrishey** [react-materialize/react-materialize#836]
https://github.com/react-materialize/react-materialize/blob/33aec145e6ad6578d927cab48a4e3240b995d7a2/src/Button.js#L16

This code should be:

```
if (typeof M === 'undefined') return;
```

Ran into this while using Jest to test React components.

**Comment by alextrastero** [comment]
True!

**Comment by alextrastero** [comment]
Maybe a good opportunity to check that all components that require `M` have the same syntax.

**Comment by bbeesley** [comment]
Created a PR to add the undefined check on all components that were missing it.
