### ISSUE TITLE
Relative import path breaking upon transpiling

### ISSUE THREAD

**Issue by JGrishey** [react-materialize/react-materialize#837]
https://github.com/react-materialize/react-materialize/blob/33aec145e6ad6578d927cab48a4e3240b995d7a2/src/Navbar.js#L5

This should be:

```
import TextInput from './TextInput';
```

Causing issues when using through NPM, because the components get recompiled into the `react-materialize/lib` directory and there is no `src` directory.

Thanks!

**Comment by CloudPower97** [comment]
There already is #832

**Comment by alextrastero** [comment]
Sorry for the trouble, this is now fixed
