### ISSUE TITLE
Row in Footer automatically adjusts itself to l={6}

### ISSUE THREAD

**Issue by SybGlm** [react-materialize/react-materialize#84]
I'm a total newbie to react-materialize... Right now I'm stuck at trying to adjust my Footer by defining its size. It should be like: 
```
<Row>
      <Col l={6} m={6} s={12}>
           <h5 className="white-text">Footer Title</h5>
           <p className="white-text">Footer Content - much bla bla bla</p>
       </Col>
       <Col l={6} m={6} s={12}>
           <Card className="light-green accent-2 hoverable"
                textClassName="black-text"
                title="Card-Title"
                actions={
                  [<Button waves="light" className="light-green accent-4 white-text">
                    <Icon left>cloud</Icon>This is a Button</Button>]
                  }>
             Some Card content
            </Card>
      </Col>
</Row>
```

but in Chrome it automatically wraps the Row in another Row-Element that has a width=l6. 

Additionally, can someone teach me how to do some offset with react-materialize? On the homepage it says it's a String as it is in the original Materialize. But it's not working. 
I tried something like this (but I have absolutely no idea how to do it...) 

```
<Col offset="l1" l={6} m={6} s={12}>
...
</Col>
```

**Comment by isaiah** [comment]
The `Footer` is quite rigid regarding styling, I think you are better off, just by using the grid components `Row` and `Col`.

The `offset` should work, but I'll have a try by myself.

**Comment by SybGlm** [comment]
Thanks for helping :) 

Regarding the Footer: 
I tried to use the grid components Row and Col inside it by using the following code inside my footer.jsx-File ... 

```
  <Footer className="light-green accent-4"
        copyrights="&copy; 2016 Copyright Text"
        moreLinks={
          <a className="white-text text-lighten-4 right" href="#!">
            <span className="white-text"><i className="material-icons right">add</i>
              Add</span></a>
        }
        >
        <Row>
          <Col l={6} m={6} s={12}>
            <h5 className="white-text">FooterTitle1</h5>
            <p className="white-text">Some text: blabla</p>
          </Col>
          <Col l={6} m={6} s={12}>
              <h5 className="white-text">FooterTitle 2</h5>
              <p className="white-text">Footer Text 2: blabla</p>
          </Col>
        </Row>
      </Footer>
```

... but as mentioned, it seems like the row adjusts itself to l=6 on big screens instead of l=12 (on middle screens everything works perfectly fine and the outer Row is m=12 wide). Is there some sort of customization that I'm missing? 

Here is a screenshot of what I mean when I say it automatically wraps itself in another Row, that has l=6: 
![footer](https://cloud.githubusercontent.com/assets/14124780/16420218/d6850fb0-3d50-11e6-97fa-5eda348779fa.png)

**Comment by isaiah** [comment]
@SybGlm As I said, just replace the `Footer` component with a normal `footer` element.

**Comment by alextrastero** [comment]
Closing unless it's still an issue
