### ISSUE TITLE
ReferenceError: M is not defined

### ISSUE THREAD

**Issue by Dadarkp3** [react-materialize/react-materialize#841]
### Description
Having some problems with the react-materialize while creating the project with create-react-app, follow the documentation, but nothing works. 

### Steps to Reproduce

1. Create a project with create-react-app with typescript
2. Normal react-materialize install
3. Add the CSS and js from materialize-css in the index.html located in the public file
4. Fix the issue of the types adding a declaration with "d.ts" for the react-materialize
5. Add any type of component, with the, corrects imports

**Expected behavior:** Normal component showing in the app
**Actual behavior:** 
Errors on the console:  Uncaught SyntaxError: Unexpected token < with the materialize.js 
and Carousel.js:53 Uncaught ReferenceError: M is not defined with the components used

### Versions

    "materialize-css": "^1.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-materialize": "^3.1.1",
    "react-scripts-ts": "3.1.0"

**Comment by CloudPower97** [comment]
It means that `materialize-css` was not imported correctly.
This relates to #836.  @alextrastero At this point, we should check all components that require `M`.

**Comment by alextrastero** [comment]
This is related to how you import materialize-css.js asset, let us know if you can't solve this

**Comment by anshulkatta** [comment]
> ### Description
> Having some problems with the react-materialize while creating the project with create-react-app, follow the documentation, but nothing works.
> 
> ### Steps to Reproduce
> 1. Create a project with create-react-app with typescript
> 2. Normal react-materialize install
> 3. Add the CSS and js from materialize-css in the index.html located in the public file
> 4. Fix the issue of the types adding a declaration with "d.ts" for the react-materialize
> 5. Add any type of component, with the, corrects imports
> 
> **Expected behavior:** Normal component showing in the app
> **Actual behavior:**
> Errors on the console: Uncaught SyntaxError: Unexpected token < with the materialize.js
> and Carousel.js:53 Uncaught ReferenceError: M is not defined with the components used
> 
> ### Versions
> ```
> "materialize-css": "^1.0.0",
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "react-materialize": "^3.1.1",
> "react-scripts-ts": "3.1.0"
> ```
> 
> #### Thanks for helping out!
follow this

http://fullstackhybrid.com/using-materializecss-with-reactjs/

**Comment by alextrastero** [comment]
> This is NOT a tutorial on the package called react-materialize.

**Comment by alextrastero** [comment]
I guess your issue is that `materialize` js is not being bundled.

`M` is added to the global window scope by materializejs, meaning they probably do something like `window.M = ...` so you can't do `import M from ...`. Just `import 'materialize-css';`

**Comment by hopper01** [comment]
i am using Cdn files in nextjs and getting this error in my useEffect hook. At first it shows this error and when i reload it the page just runs fine. Can you guys help me?
