### ISSUE TITLE
Could not find a declaration file for module 'react-materialize'

### ISSUE THREAD

**Issue by garwedgess** [react-materialize/react-materialize#842]
### Description
I'm updating react-materialize from an older version. But I'm having issues explained below. Note that I am not using TypeScript.

IDE reports: 
> Could not find a declaration file for module 'react-materialize'.

When running the app the browser reports:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `App`.

Which I'm guessing is because react-materialize module is not found?

### Steps to Reproduce

1. run create-react-app
2. npm install materialize-react
3. add materialize-css dependnecies to public/index.html (see below for contents)

**Expected behavior:** To be able to use react-materialize in my project
**Actual behavior:** Unable to use react-materialize due to the above.

### Versions

**react-materialize:** 3.1.1
**materialize-css:** 1.0.0
**react:** 16.8.6

Thanks for the help.

```<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="theme-color" content="#0b5584" />
  <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet" type="text/css" media="screen"/>
  <title>USE Ltd</title>
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>```

**Comment by CloudPower97** [comment]
Please, ensure that you are using `react-materialize` and not `materialize-react`.
Can you share a snippet of your `React` code? Which component are you trying to use?

**Comment by garwedgess** [comment]
Sorry, it was actually a mistake on my side. I was using a component which doesn't exist from v2.x -> v3.x. Thanks for the input.
