### ISSUE TITLE
Chip onClick Removed

### ISSUE THREAD

**Issue by jamesmart77** [react-materialize/react-materialize#845]
### React Materialize v3.0.0 Chip onClick No Longer Exists

The newest release of this library no longer supports the onClick parameter for the Chip component. This change in support is a bit surprising given the restrictions this imposes upon users. Is there any possibility of getting this function supported again?

### Versions

**react-materialize:** 3.1.1
**materialize-css:** 1.0.0
**react:** 16

**Comment by CloudPower97** [comment]
@jamesmart77 Which version are you coming from?

**Comment by masonjwhite** [comment]
Hey @CloudPower97 we're coming from 2.6. (I work with @jamesmart77.

**Comment by CloudPower97** [comment]
@masonjwhite @jamesmart77 This issue should be fixed with #848 :smile:

**Comment by masonjwhite** [comment]
Thanks @CloudPower97! Appreciate the quick response.
