### ISSUE TITLE
Select - no way to access new value in onChange w/o using a ref

### ISSUE THREAD

**Issue by rulatir** [react-materialize/react-materialize#85]
When a new selection is made in `<Input type="select"/>`, the onChange callback receives an event object that contains a target object that still contains the old value.

The new value is accessible only through the `Input` instance, but there is no apparent way to obtain it from the event object.

This necessitates using a `ref`, and `ref`s are for all intents and purposes deprecated, what with React documentation effectively saying that 99.99999999999999999999% of the time you feel you want to use them you are doing something wrong.

Please make it somehow possible to access the new value without using refs.

**Comment by rulatir** [comment]
BUMP

**Comment by chasen** [comment]
+1

**Comment by isaiah** [comment]
@alextrastero any update?

**Comment by alextrastero** [comment]
Forgive me but I still don't understand where the issue is:
```JS
_onChange (e) {
    const { onChange } = this.props;
    var types = {
      'checkbox': e.target.checked,
      'select-multiple': this.getMultipleValues(e.target),
      'default': e.target.value
    };
    const value = types[e.target.type] || types['default'];
    if (onChange) { onChange(e); }

    this.setState({ value });
  }
```

`value` comes from the target of the input

**Comment by rulatir** [comment]
Did you mean "target of the event"?

**Comment by alextrastero** [comment]
Ups, yes, that's what I meant

**Comment by alextrastero** [comment]
Please reopen this if not fixed :)
