### ISSUE TITLE
Checkbox checked state is not drawn on load

### ISSUE THREAD

**Issue by AelinGalathynius** [react-materialize/react-materialize#854]
### Description

I got some checkboxes on my page which display an activated state for accounts. 
The activated state is stored in a database, so on load we already know what checkbox state every checkbox has, but they all appear empty

### Steps to Reproduce

1. Initialize checkbox with "checked={true}"
2. load page

`<Checkbox
						name={"active"}
						label={""}
						aria-label={i18next.t('active')}
						filledIn
						checked={true}
						value={"active"}
						onChange={(evt) => {
							this.changeAccountActive();
						}}
						disabled={false}
						id={"_active_"}
					/>`

**Expected behavior:** When checkbox state is checked, the checkbox should appear checked on load.

**Actual behavior:** State is checked but the actual checkbox is not.

### Versions

**react-materialize:** ^3.2.0
**materialize-css:** ^1.0.0
**react:** ^16.8.6

**Comment by jamesmart77** [comment]
Looks like this was broken again because this was a problem a couple weeks ago...

https://github.com/react-materialize/react-materialize/issues/823

**Comment by CloudPower97** [comment]
Hey @jamesmart77, I've already made #855.
This _should_ never be broken again from now on, as I've added a new `spec` to check if the `Checkbox` is checked when the respective `prop` is used.
I think that it has been broken by #809.

Sorry for the trouble :grin:

**Comment by jamesmart77** [comment]
Thanks @CloudPower97! Is there a spec to check this for all appropriate components? We may be seeing similar behavior with radio buttons as well

 ![bitmoji](https://render.bitstrips.com/v2/cpanel/bcf24f22-8d36-43ef-af97-098d9a4c1423-1130e0d1-7aee-4853-bc4f-193d9ff81820-v1.png?transparent=1&palette=1&width=246)

**Comment by CloudPower97** [comment]
Hey @jamesmart77, just checked `RadioGroup` component, it seems everything is working.
Anyway, if you still have problem you can open a new issue
