### ISSUE TITLE
Lib version doesnt match with src

### ISSUE THREAD

**Issue by sminutoli** [react-materialize/react-materialize#86]
I´ve done `npm i react-materialize` and it looks like my `node_modules/react-materialize/lib/Dropdown.js` doesn't match with the `src/Dropdown.js` stated here on `master` (i´m still getting the old version, without initilization onComponentDidMount)...

The version seems to be right according to my `package.json`:

`"react-materialize": "^0.14.4"`

Am I doing something wrong or its a bug?

**Comment by isaiah** [comment]
The `npm` package is a bit old, I should have updated the current trunk version, sorry.

**Comment by sminutoli** [comment]
Please let me know if you're planning to update it soon

**Comment by sminutoli** [comment]
Any news about this one? Are you planning to still giving support on NPM or it's a discontinued package?

**Comment by isaiah** [comment]
@sminutoli 0.14.6 with the latest changes released on npm.
