### ISSUE TITLE
stops scrolling after close modal

### ISSUE THREAD

**Issue by babscomoglio** [react-materialize/react-materialize#862]
### Description

[Description of the issue]

### Steps to Reproduce

1. access: http://react-materialize.github.io/react-materialize/?path=/story/javascript-modal--default
2. Click on 'Modal'
3. Do not close the modal
4. Select from the side nav:React Materialize > Welcome

**Expected behavior:** 
You will expect to be able to scroll inside the <body class="sb-show-main">

**Actual behavior:**
Scroll is not happening

### Versions

**react-materialize:** 3.2.2
**materialize-css:** 1.0.0
**react:** 16.8.6

Thanks.

**Comment by alextrastero** [comment]
Good catch, I think this is just the way storybook navigates to other components. I don't think it's an actual component bug though

**Comment by babscomoglio** [comment]
Hi, thanks for your reply. 
I added the component to on of my project and the bug its there too :/

**Comment by alextrastero** [comment]
👍 will look into this

**Comment by alextrastero** [comment]
Can't reproduce, does your project use react-router for navigation?

**Comment by babscomoglio** [comment]
I am using react-router-dom

In my project I reproduce the error this way:

1) from the home page I click a button to take me to page 1
2) In page 1, I open a modal but I do NOT close it
3) I go back to the home page, using the back browser button. 
4) I again click the button to take me to page 1
5) I open the modal, then I close it. 
6) Page 1 won't scroll anymore.

Inspecting the code, it doesn't clean the 'overflow: hidden' from the body anymore.

**Comment by babscomoglio** [comment]
Hi @alextrastero 
I created a repo to replicate the issue.

https://github.com/babscomoglio/react-materialize-modal-issues

Hope it helps. 

To reproduce the error:

### Option 1
1) from http://localhost:3000/ click on 'go to page One'
2) in http://localhost:3000/pageone, see that content scrolls. Open modal, do not close
3) Press button 'back to Home'
4) from http://localhost:3000/ click on 'go to page One'
5) Open again the modal
6) close modal

Content won't scroll anymore


### Option 2
1) from http://localhost:3000/ click on 'go to page One'
2) in http://localhost:3000/pageone, see that content scrolls. Open modal, do not close
3) Use back button from browser
4) from http://localhost:3000/ click on 'go to page One'
5) Open again the modal
6) close modal

Content won't scroll anymore

please let me know if you can reproduce the error now. 

Thanks.

**Comment by CloudPower97** [comment]
Trying to reproduce the bug, I might have found another one. When I open a modal and then I use the back button of the browser, the modal doesn't close.

**Comment by alextrastero** [comment]
Would be interesting to see if this is our bug or a general materialize.css bug

**Comment by CloudPower97** [comment]
@alextrastero I think I was able to fix both issues, will open a __P.R__ soon.

**Comment by alextrastero** [comment]
Let us know if it's still happening @babscomoglio :)
