### ISSUE TITLE
Dropping Icon component

### ISSUE THREAD

**Issue by CloudPower97** [react-materialize/react-materialize#866]
Hey, @alextrastero, I think we can make any icon `prop` a `node` and dont use `Icon` component ourselves in other components of `react-materialize`.
If the user wants, he can use the component shipped with `react-materialize`, otherwise he is able to use anythings he wants, like _Material Design Icons for React_.

This is the same approach used in #793 .

Let me know if this is ok for you, I'd like to open a P.R for this, if you agree. :smile:

**Comment by alextrastero** [comment]
Nice, we could also limit it a bit, of course it's good that components can handle multiple situations and edge cases but I would vote to only allow `icon` prop to be a `node`.

**Comment by CloudPower97** [comment]
Yep, It definitely need to be a `node` and nothing else.
Alright then, I'll be working on this ASAP :man_technologist:

**Comment by alextrastero** [comment]
👍
