### ISSUE TITLE
defaultDate doesn't work properly

### ISSUE THREAD

**Issue by Tames12** [react-materialize/react-materialize#870]
Hi, When I define the defaultDate prop to the component using a state.date doesn't look to work correctly.

 I got the next: 

`<DatePicker options={{
defaultDate: new Date(this.state.myDate),
setDefaultDate: true,
format: 'MM-DD-YYYY'
}} />`

but when the picker is opened my date is not defined.

Unlike if I define the next: 

`<DatePicker options={{
defaultDate: new Date('2018-10-20'),
setDefaultDate: true,
format: 'MM-DD-YYYY'
}} />`

It works.

**Expected behavior:** I should be able to see my state.myDate as the default in the picker.

**Actual behavior:** The actual date ( at the moment of open the picker) is the default
### Versions

**react-materialize:** 3.3.0
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by CloudPower97** [comment]
I've create a sample sandbox to test the behavior and it seems to work:

[![Edit wonderful-mendel-hkzl4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-mendel-hkzl4?fontsize=14)

What does not work is doing something like this (taking into account the previous sandbox code)

```javascript
componentDidMount() {
     this.setState({
          myDate: "2019-10-20"
     });
}

```

**Comment by Tames12** [comment]
which browser are you using ? 
![image](https://user-images.githubusercontent.com/32028322/57889756-dae8ed80-77f2-11e9-94ae-398ccea9d55d.png)

open your example I just see the format, even when I change the date the only thing I see is the format literally.

**Comment by Tames12** [comment]
I see your example but the only thing I see is the format value, even if I change the date just the format (literally) is visible.

![image](https://user-images.githubusercontent.com/32028322/57889998-96118680-77f3-11e9-8b8b-733749d7db28.png)

**Comment by alextrastero** [comment]
I'm also seeing just the format

**Comment by CloudPower97** [comment]
@Tames12 Sorry, I thought you was referring to the date selected once the picker is open, which works correctly.
The behavior is the expected one, it seems that this is how `materialize-css` works.

**Comment by victorw999** [comment]
**format should be lowercase**  
format: "mm-dd-yyyy"
[Date format options](https://materializecss.com/pickers.html)


https://codesandbox.io/s/winter-silence-97yg9

**Comment by alextrastero** [comment]
Thanks @victorw999, good catch, closing this then
