### ISSUE TITLE
Side nav not being triggered.

### ISSUE THREAD

**Issue by luminkhant** [react-materialize/react-materialize#873]
I am using side nav as below and side nav is not being triggered.

`<SideNav
                            trigger={<Button/>} 
                            options={{closeOnClick: true}}>
                            <SideNavItem userView user={{
                                background: 'https://placeimg.com/640/480/tech',
                                image: 'static/media/react-materialize-logo.824c6ea3.svg',
                                name: 'John Doe'
                            }} />
                            <SideNavItem href="#!icon" icon="cloud">
                                First Link With Icon
                            </SideNavItem>
                            <SideNavItem href="#!second">
                                Second Link
                            </SideNavItem>
                            <SideNavItem divider />
                            <SideNavItem subheader>
                                Subheader
                            </SideNavItem>
                            <SideNavItem waves href="#!third">
                                Third Link With Waves
                            </SideNavItem>
                        </SideNav>`

**react-materialize:** 3.3.1
**materialize-css:** x.x.x
**react:** 16.8.6

**Comment by alextrastero** [comment]
Can you use any other materialize JS components? Are there any errors in the console?

**Comment by luminkhant** [comment]
There is no error in console. And I am thinking about to use other react components. @alextrastero

**Comment by alextrastero** [comment]
![works](https://user-images.githubusercontent.com/4152819/58722472-c94d3b80-83d7-11e9-9e0b-259a277f1556.gif)

 Works for me @luminkhant, you must have another issue

**Comment by luminkhant** [comment]
Yes, it is perfectly working on my computer web. But when i use it with my phone (iphone 7 & Mi A2), the side bar is not being triggered. Could you please test it with mobile phone ? @alextrastero

**Comment by alextrastero** [comment]
Works fine on my phone too, can you submit a repo where I can test?
