### ISSUE TITLE
Button show icon edit

### ISSUE THREAD

**Issue by jmario1236** [react-materialize/react-materialize#905]
### Description

Hi, I have a problem with button component, the icon button set default icon edit on linux mint machine

### Steps to Reproduce

1. Go to [index react materialize](http://react-materialize.github.io/react-materialize/?path=/story/react-materialize--welcome)
2. 
![](https://i.imgur.com/N9npNos.png)
![](https://i.imgur.com/F8EUsqr.png)
![](https://i.imgur.com/CQFuE6i.png)
![](https://i.imgur.com/8gtiDZC.png)

**Expected behavior:** No show icon edit

**Actual behavior:** show icon edit

PD: on windows work fine

**Comment by alextrastero** [comment]
@jmario1236 why is this closed? Thanks for catching this, it's an actual error that's just been introduced https://github.com/react-materialize/react-materialize/pull/890

**Comment by CloudPower97** [comment]
@alextrastero Sorry for that, I missed that as well :frowning:

**Comment by alextrastero** [comment]
No problem, can happen :)
