### ISSUE TITLE
Select element with icon throwing error

### ISSUE THREAD

**Issue by srthapa927** [react-materialize/react-materialize#908]
![Screenshot (5)](https://user-images.githubusercontent.com/26339586/64762885-ad247300-d55e-11e9-9ae2-3be63cf80b46.png)
### Description

While using Select element with icon it throws `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`
### Steps to Reproduce

http://react-materialize.github.io/react-materialize/?path=/story/components-select--with-icon

**Expected behavior:** It should show icon like other elements.
**Actual behavior:** Throws error

### Versions

**react-materialize:** 3.3.3
**materialize-css:**  1.0.0
**react:** 16.8.6

**Comment by srthapa927** [comment]
Using `<Select icon="how_to_reg" ><options>opt1</option></Select>` throws error.

Using  `<Select icon={<i className="material-icons">how_to_reg</i>}><options>opt1</option></Select>` renders string `how_to_reg`.

Using  `<Select icon={<Icon>how_to_reg</Icon>}><options>opt1</option></Select>` works fine.

**Comment by CloudPower97** [comment]
@srthapa927 Thanks for finding this out. Actually the problem is in the `story` itself, which I'm going to update.
Thanks for the feedback.
