### ISSUE TITLE
Slect with multiple option not working

### ISSUE THREAD

**Issue by xael-fry** [react-materialize/react-materialize#911]
### Description

Slect with multiple option not working
http://react-materialize.github.io/react-materialize/?path=/story/components-select--multiple

### Steps to Reproduce

1. Go to http://react-materialize.github.io/react-materialize/?path=/story/components-select--multiple
2. try to select options 1

**Expected behavior:** options 1 is selected

**Actual behavior:** nothing is selected

**Comment by alextrastero** [comment]
Thank you! Great catch.

**Comment by alextrastero** [comment]
Hi @xael-fry, can you confirm this is still happening?

**Comment by alextrastero** [comment]
please reopen if yes :)
