### ISSUE TITLE
DatePicker ClearBtn doesn't call onChange()

### ISSUE THREAD

**Issue by AelinGalathynius** [react-materialize/react-materialize#921]
### Description

When you initialise a DatePicker with "showClearBtn: true", the onChange will not be called if said button is pressed.

### Steps to Reproduce

1. Initialize DatePicker with "showClearBtn: true"
2. open DatePicker and select any date
3. open DatePicker again and use "clear"(clearBtn)
4. no onChange will be called

### Code
`<DatePicker
								id="date1"
								name="date1"
								icon={'today'}
								label={i18next.t("from")}
								key={'date1_' + this.props.lang}
								options={DateTimeUtils.datePickerOptions()}
								onChange={function (value) {
									this.changeFilter('filterFrom', value);
								}.bind(this)}
							/>`
DatePickerOptions
`static datePickerOptions = function () {
		return {
			format: i18next.t('dateFormat').toLowerCase(),
			i18n: { ...
				'cancel': i18next.t("cancel"),
				'clear': i18next.t("clear")
			},
			defaultDate: new Date(),
			setDefaultDate: true,
			showClearBtn: true,
			firstDay: 1,
			autoClose: true,
			container: 'body'
		}
	};`

**Expected behavior:**

I did expect that the clear will also call onChange, because it closes the window and the DatePicker has no State of it's own.

**Actual behavior:**

onChange is not called, which makes it hard to react to that click.

### Versions

**react-materialize:** "^3.4.1"
**materialize-css:** "^1.0.0"
**react:** "^16.10.2"

**Comment by matthewsbrandan** [comment]
Use the onClose function to check if the datePicker is empty when it is closed, if it is empty, and it is different from the previously stored value, it has been cleared.

**Comment by matthewsbrandan** [comment]
```
   onClose: (e) => {
        if(!e && this.filterFrom) this.changeFilter('filterFrom', null)
   },
```

**Comment by alextrastero** [comment]
Yes, this is the default behaviour for materializecss i'm afraid, nothing I can add here
