### ISSUE TITLE
Icon and font-size

### ISSUE THREAD

**Issue by lynicidn** [react-materialize/react-materialize#922]
### Description
> 
> Docs: https://materializecss.com/icons.html
> To control the size of the icon, change the font-size: 30px

### Steps to Reproduce
try it:
```html
<Icon style={{fontSize: "30px"}}>lock</Icon>
```
**Expected behavior:** icon with 30px of font size

**Actual behavior:** font size 24px from `material-icon` class of css

### Versions

materialize-css@ (empty)
react-materialize@3.4.1 
react@16.11.0

**Comment by lynicidn** [comment]
i think problem here:
https://github.com/react-materialize/react-materialize/blob/master/src/Icon.js#L18

we should transfer `style` for `i` component

**Comment by alextrastero** [comment]
@lynicidn good catch, we should maybe be passing `...rest` props:
`<i className={cx(classes, this.props.className)} {...rest} />`

Is this something you would like to give a go?

**Comment by lynicidn** [comment]
@alextrastero sorry, i can't.
1. bad know english
2. beginer in react/jsx 
3. don't understand about `rest` - it transformed props? as example: `fontSize` to `font-size` ?

i find temporary solve via className - copy css class `large` to `giant` and set Font Size for this class

**Comment by aelfric** [comment]
Is there still interest in fixing this?  I could submit a PR to add the spread props like you suggested.

**Comment by alextrastero** [comment]
Yes please!
