### ISSUE TITLE
Select not working in iOS

### ISSUE THREAD

**Issue by tomatenschaf** [react-materialize/react-materialize#924]
### Description

Environment: iPhone SE with iOS 13.1.3

Select don't chooses the option I Tab on, but the option of the next line. Tab on last Option don't fires an onChange event. Sometimes also no option is chosen, although there is a next option.

I found this bug in my project and retested/confirmed it on react-materialize.github.io

Sometimes iOS-Safari Bugs are reproducible on OSX-Safari, but I can't reproduce it on my (older) Mac OSX-Safari Version 12.1.2 (12607.3.10)

### Steps to Reproduce

1. Got to http://react-materialize.github.io/react-materialize/?path=/story/components-select--default
2. Tab on Option 3
3. Option 3 is highlighted- > select closes
4. Nothing/"Choose your option" is set
5. Tab on Option 1
6. Option 1 is highlighted -> select closes
7. Option 2 is selected
8. Tab on Option 2
9. Option 2 is highlighted -> select closes
10. sometimes: Option 3 is selected or: Nothing/"Choose your option" is selected

**Expected behavior:** 

Choose the option I clicked

**Actual behavior:** 

It chooses the option above the one I clicked

### Versions 

My private setup where I found the bug: 
**react-materialize:** 3.2.2
**materialize-css:** 1.0.0
**react:** 16.8.6

**Comment by alextrastero** [comment]
Thanks for the info :) closing for now
