### ISSUE TITLE
TextInput type file doesn't work

### ISSUE THREAD

**Issue by MohammadFatoni** [react-materialize/react-materialize#925]
### Description

I wanna use input type file in my project but when i try the code, it doesnt render the materialize component.

The code that i try to make input type file
```
<TextInput type="file" />
<input type="file" />
```

### Versions

**react-materialize:** 3.4.1
**materialize-css:** 1.0.0
**react:** 16.12.0

**Comment by alextrastero** [comment]
Hey @MohammadFatoni, i'm afraid File input is not implemented yet, for now you can use this code:

```jsx
  <div className="file-field input-field">
    <div className="btn">
      <span>File</span>
      <input type="file" />
    </div>
    <div className="file-path-wrapper">
      <input className="file-path validate" type="text" />
    </div>
  </div>
```

**Comment by alextrastero** [comment]
I took the opportunity to create this type of **TextInput** :)

**Comment by alextrastero** [comment]
`react-materialize@3.5.0`
