### ISSUE TITLE
Pagination - disabled arrows still have effect and point browser to #!

### ISSUE THREAD

**Issue by paulosuzart** [react-materialize/react-materialize#94]
Hi,

tried to use Pagination but when clicking back arrow even in the page one, the component gets activated and `activePage` becoms 0 and so forth. Same to forward arrow in the last page. 

Another strange thing is that  upon clicking `PaginationButton` it always point browser history to `#!`.

Cheers

**Comment by alextrastero** [comment]
Fix here: https://github.com/react-materialize/react-materialize/pull/95
I've also changed PagintaionButton href, now links to #

**Comment by alextrastero** [comment]
this was fixed in 0.14.8
Closing
