### ISSUE TITLE
idx property in Tab not working as expected

### ISSUE THREAD

**Issue by aurinxki** [react-materialize/react-materialize#952]
### Description
Upon construction of Tab, a numeric id is auto assigned instead of using idx property.

**Expected behavior:** 
`<Tabs>
    <Tab idx="example">
</Tabs>`

should result in a `div` element with `id="tab_example"`, according to **[Tab.js](https://github.com/react-materialize/react-materialize/blob/master/src/Tab.js)**:
`return _react.default.createElement(_Col.default, {
    id: "tab_".concat(idx)
    ...
}, children);`

**Actual behavior:** 
Instead, a `div` element is rendered with `id="tab_20"`

### Versions

**react-materialize:** 3.4.1
**materialize-css:** 1.0.0
**react:** 16.10.2

**Comment by babscomoglio** [comment]
was this resolved?

**Comment by alextrastero** [comment]
Hi @babscomoglio please paste your sample code. Basically `Tabs` needs to define the id of `Tab` in order to work. What's your issue?

**Comment by jonlima2018** [comment]
when defining idx in tabs the id and href are not changed, it is always defined with tabs-110

Expected:
`<Tabs>
     <Tab idx="example">
     <Tab idx="example2">
</Tabs>`

Actual:
Instead, a div element is rendered with 
`<div href="#tabs_110"> example 1</div>
<div href="#tabs_111"> example 2</div>

<div id="tabs_110"> content example 1</div>
<div id="tabs_111"> content example 2</div>`

**Comment by jonlima2018** [comment]
Hi @alextrastero, i'm added a pull request for fix bug.

**Comment by alexrizan** [comment]
Problem is still here (3.9.8)
And, please, look at this thing "react-materialize/src/idgen.js" :)

**Comment by alextrastero** [comment]
Should be fixed in 3.9.9 sorry for the delay!
