### ISSUE TITLE
Col does not support id attribute?

### ISSUE THREAD

**Issue by zhengpd** [react-materialize/react-materialize#96]
I look through the `Col.js` and found nothing about `id` html attribute. Am I missing something?

**Comment by alextrastero** [comment]
Hey @zhengpd what do you mean exactly? that you want to pass id? what's the purpose? 😊

**Comment by zhengpd** [comment]
@alextrastero Sorry I didn't make it clear. I have some code like `<Col id="my_id">something</Col>`. It used to work with react-materialize 0.14.4, but not working with latest version and the `id` is missing from rendered DOM. It seems that `{...props}` was removed from the return block in latest `Col`'s render method.

**Comment by alextrastero** [comment]
Absolutely right @zhengpd, #114 should fix it :)

**Comment by zhengpd** [comment]
Great! 👍
