### ISSUE TITLE
version 3.5.1 & 3.5.2 Invalid Hook Call Warning error

### ISSUE THREAD

**Issue by wsl2001** [react-materialize/react-materialize#968]
### Description

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

### Steps to Reproduce
Error Decoder
In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.

We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original text of the error.

The full text of the error you just encountered is:

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

### Versions

**react-materialize:** 3.5.1 & 3.5.2

**Comment by alextrastero** [comment]
Thanks for reporting this, could you tell us what version of React you are using?

**Comment by CloudPower97** [comment]
@alextrastero It seems one have to declare `react` and `react-dom` as `peerDependencies` 
```json
  "peerDependencies": {
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  }
```
and not as `dependencies`

**Comment by alextrastero** [comment]
True! i'm on it now

**Comment by alextrastero** [comment]
Merged, I'll reopen if this is not solved in `3.5.3`

**Comment by alextrastero** [comment]
No, this is still an issue

**Comment by alextrastero** [comment]
Can you confirm this is also happening to you @CloudPower97 ?

**Comment by alextrastero** [comment]
Ok, I think this is solved now :D believe it or not the issue was with a wrong version of react in a devDependency `@storybook/info-addon` AFIK

**Comment by alextrastero** [comment]
Closing, please try with 3.5.5

**Comment by wsl2001** [comment]
new error with version 3.5.5

Cannot set property '_trigger' of null
