### ISSUE TITLE
Storybook needs more info!

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#972]
Currently Storybook has no info on how to render the components, what's the best approach here? we previously used `@storbook/info-addon` but at this time there's a big conflict in react versions that won't allow us to use this lib.

**Comment by christopherfowers** [comment]
Just dropped a comment on your commit before seeing this (my bad). What format was all of that in for the info addon? Is this MD? Could all of this be copied to the wiki in github maybe? 
Are there other locations for examples of usage? Ideally it'd all live with storybook (I'm currently not familiar with the usage of it to be able to advise)

**Comment by alextrastero** [comment]
Yes, I was in panic mode trying to solve the react conflict issue, i've restored it in 3.5.6, really sorry about the inconvenience.

**Comment by christopherfowers** [comment]
Sorry about complaining. Just threw me off
