### ISSUE TITLE
new error with version 3.5.5  Cannot set property '_trigger' of null

### ISSUE THREAD

**Issue by wsl2001** [react-materialize/react-materialize#973]
### Description

after updating to version 3.5.5 a new error started 

Cannot set property '_trigger' of null

### Versions

**react-materialize:** 3.5.5

**Comment by alextrastero** [comment]
Hi @wsl2001, thanks for reporting this, i've tried to reproduce but I can't see this error, could you post some example code? thx!

**Comment by wsl2001** [comment]
Hi @alextrastero, Am using a product called Powershell Universal Dashboard which rely s on  react-materialize module, when tried to update to ver. 3.5.5 or your new 3.5.6 i got the error mentioned above when starting my  dashboard. i had to go back to ver 3.5.0 and everything works fine in my dashboard. so not sure what code i can provide to help you identify the issue.

**Comment by wsl2001** [comment]
![image](https://user-images.githubusercontent.com/47834749/69957830-888ec600-14d1-11ea-93de-781dcba9e282.png)

**Comment by wsl2001** [comment]
![image](https://user-images.githubusercontent.com/47834749/69957917-b2e08380-14d1-11ea-8ae4-b29292556d45.png)

**Comment by alextrastero** [comment]
That was enough info, thx @wsl2001
