### ISSUE TITLE
Adding support for changing the color of a ProgressBar

### ISSUE THREAD

**Issue by yanickrochon** [react-materialize/react-materialize#98]
For example, the markup for `ProgressBar` does not allow setting custom styles and classes. For example

```jsx
<div className="progress">
  <div className="determinate red" style="width: 70%"></div>
</div>
```

is not possible (i.e. the `red` CSS class), thus it is impossible to change the progress bar's color. Something like

```jsx
<ProgressBar progress="70%" color="red" />
```

should be implemented.

**Comment by alextrastero** [comment]
No need for style @yanickrochon , you should be able to pass classname to component as a prop, I will have a look

**Comment by alextrastero** [comment]
@yanickrochon check out this PR
https://github.com/react-materialize/react-materialize/pull/99

**Comment by yanickrochon** [comment]
:+1:
