### ISSUE TITLE
Icon doc is not displaying correctly

### ISSUE THREAD

**Issue by ArtiomLK** [react-materialize/react-materialize#983]
### Description

open http://react-materialize.github.io/react-materialize/?path=/story/components-textarea--icon

<img width="1676" alt="Screen Shot 2019-12-20 at 11 01 05 PM" src="https://user-images.githubusercontent.com/8462791/71302721-ae92e200-237c-11ea-8f17-feb3ab7a93da.png">

**Comment by alextrastero** [comment]
Thanks @ArtiomLK for the report
