### ISSUE TITLE
Update storybook in travis

### ISSUE THREAD

**Issue by alextrastero** [react-materialize/react-materialize#986]
Currently we build the docs manually on each version bump, how about moving this task to travis?

**Comment by theashraf** [comment]
Can I work on this?

**Comment by ydax** [comment]
I'm interested in collaborating to help with docs, if needed. I have experience in managing this kind of thing.

**Comment by alextrastero** [comment]
Hi @ydax please yes :)

**Comment by ydax** [comment]
Okay, I've never used Storybook before, but I will take an hour or two in the coming week and try to train myself up on it so that I can help maintain the docs.

**Comment by ydax** [comment]
Hey @alextrastero just to be clear, would helping you update the docs involve:

1. Forking [this Storybook repo](https://github.com/react-materialize/react-materialize.github.io)
2. Finding things to fix
3. Fixing them and submitting a PR to that repo

Forgive my newbie question.

Davis

**Comment by alextrastero** [comment]
Hey @ydax, thanks for helping out!

The process of updating storybook with the latest code involves this manual process:

1. run `npm run build-storybook`
2. commit changed code

Ideally this should happen on CI level, when merging to master.

**Comment by alextrastero** [comment]
AMA! don't hesitate :)

**Comment by ydax** [comment]
CI = continuous integration?

**Comment by alextrastero** [comment]
We use [travis](https://travis-ci.com/) for continous integration, surely there must be some google results about storybook and travis :)

**Comment by ydax** [comment]
Awesome. I was wondering what you meant by travis, now I know! I'll spend a couple of hours this weekend trying to get up to speed with it.

**Comment by alextrastero** [comment]
Hi @ydax, I had some time and started working on this. Basically since npm has now been bought by github I think it's sane to move from travisci to github actions.

**Comment by alextrastero** [comment]
Feel free to have a look at the changes:
https://github.com/react-materialize/react-materialize/pull/1005

When a release is created (with `npm version patch|minor|mayor`) the storybooks are built and committed.

**Comment by alextrastero** [comment]
Let me know if you have any questions :)
