### ISSUE TITLE
Divider in dropdown is wrapped in <li> after creating a PROD build with CRA

### ISSUE THREAD

**Issue by brlnr23** [react-materialize/react-materialize#993]
### Description

I am using create-react-app for my project. On one page I am using the dropdown component with dynamically created entries including two dividers. When running the whole thing in development mode (`npm start`) everything works as expected. But as soon as a production build is created 
the divider component is wrapped in another <li> which makes the dropdown look ugly. Not sure how/if this could be connected with the react(-scripts) version, but very likely it has to do with some of the production optimization steps.

### Steps to Reproduce

*React*
```
<Dropdown options={{"coverTrigger": false, "hover": true, "constrainWidth": false}} trigger={<Button>Testme</Button>}>
<a href="abc">ABC</a>
<Divider />
<a href="abc">DEF</a>
<a href="abc">GJH</a>
</Dropdown>
```

*DEV markup*
<img width="86" alt="dev" src="https://user-images.githubusercontent.com/35556937/73864746-75d29d80-4842-11ea-82a7-739c45622734.png">
```
<ul class="dropdown-content" id="dropdown12" tabindex="0" style="">
<li tabindex="0"><a href="abc">ABC</a></li>
<li class="divider" tabindex="-1"></li>
<li tabindex="0"><a href="abc">DEF</a></li>
<li tabindex="0"><a href="abc">GJH</a></li></ul>
```

*PROD markup*
<img width="79" alt="prod" src="https://user-images.githubusercontent.com/35556937/73864751-766b3400-4842-11ea-9073-68270b5b45cf.png">
```
<ul class="dropdown-content" id="dropdown12" tabindex="0" style="">
<li tabindex="0"><a href="abc">ABC</a></li>
<li tabindex="0"><div class="divider"></div></li>
<li tabindex="0"><a href="abc">DEF</a></li>
<li tabindex="0"><a href="abc">GJH</a></li>
</ul>
``` 

**Expected behavior:** 
Divider is displayed without the wrapping <li>

**Actual behavior:** 
The divider is wrapped in a <li>

### Versions

**react-materialize:** 3.5.9
**materialize-css:** 1.0.0
**react:** 16.12.0
**react-scripts:** 3.3.1

**Comment by MauAbata** [comment]
This should've been fixed with #1164, so likely safe to close.
